### ISSUE TITLE
CREATE INDEX CONCURRENTLY is not supported for distributed tables.

### ISSUE THREAD

**Issue by saicitus** [citusdata/citus#1007]
Encountered this in 2 customer conversations. The first user uses psycopg2 as their ORM and the second uses Rails.

SQL Query which is used:
```
CREATE INDEX CONCURRENTLY
IF NOT EXISTS {table_name}_idx_a_b_c_d ON {table_name} (a, b, c, d) WHERE e='test'
```

**Comment by anarazel** [comment]
@saicitus I think it'd be useful to use labels to indicate whether you think something is a bug or a feature request.

**Comment by lfittl** [comment]
Just adding a note that we should also support `DROP INDEX CONCURRENTLY`, for easy trial and error for new indices.

**Comment by saicitus** [comment]
I wanted to drop a note here, in last ~2 weeks, came up in 3 customer/prospect engagements.

**Comment by ozgune** [comment]
We talked about this feature during our 6.2 product planning. We noted that fixing #357 also helps notably with this issue. We therefore decided to prioritize #357 together with (as a prerequisite to) this issue.

**Comment by jasonmp85** [comment]
As @ozgune points out, #357 is what we're tackling first (PR today), but that's basically an immediate stepping-stone to this (and `DROP` support).

We had a meeting about this approach last week and went over the relevant pieces, both from tech feasibility and from user experience standpoints.

Because the `CONCURRENTLY` options to `CREATE`/`DROP INDEX` prohibit use within a transaction, it is possible some nodes successfully apply the command while others fail. Rather than mark failed nodes as bad (hinted at in #357), we will emit a message to the user that the index is in an incomplete state. This is analogous to the failure mode of single-node PostgreSQL, which can itself fail to create an index using `CONCURRENTLY`.

Though it can't be performed transactionally, the race condition window is small enough that it might be worthwhile to edit the catalog to mark the created index as `INVALID`, so that `psql` inspection commands (`\d` and the like) accurate reflect the partial nature of a failed index.

To back out of such a situation, users should drop and recreate the index (or just retry `DROP` in the drop case), with appropriate `IF (NOT) EXISTS` modifiers.

The work here is relatively straightforward after #357 is complete and mostly consists of verifying the worker application command's functionality on the remotes.
