### ISSUE TITLE
How to do complex DELETE queries

### ISSUE THREAD

**Issue by HackerMD** [citusdata/citus#1041]
I have two distributed tables: table "a" and table "b", which can be joined.

How can I DELETE rows of "a" based on a criterion in "b"?

Normally, I would do

```sql
DELETE FROM a
USING b
WHERE a.id = b.a_id
AND a.name = 'foo';
```

But this results in the following error:

```
ERROR:  cannot perform distributed planning for the given modification
DETAIL:  Joins are not supported in distributed modifications.
```

I can of course also first get the IDs of rows I would like to delete

```sql
SELECT id FROM a
WHERE name = 'foo';

DELETE FROM b
WHERE a_id IN (...);
```

but this becomes extremely inefficient for large sets (millions of rows).

Are there any workarounds?

**Comment by jasonmp85** [comment]
Questions like this (rather than bug reports or feature requests) are better answered on our [mailing list](https://groups.google.com/forum/#!forum/citus-users) or [Slack channel](https://slack.citusdata.com)…

Any formulation which does this in a single command is going to hit that error, as there's no way to write that query without referencing both tables (a kind of join, even if it's a subquery).

The `DELETE FROM […] WHERE […] IN […]` approach is the workaround we typically see people using; if you have more questions about throughput or want to discuss your use-case in finer detail, feel free to start a thread on the mailing list or hit us up on Slack.

Thanks!
