### ISSUE TITLE
Convert COPY logic to use new connection api

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#1096]
this is a copy related part of #873

**Comment by marcocitus** [comment]
Me and Andres were discussing how to always use the same connection for modifications to co-located placements. This is something we do implicitly in the router executor by using a single connection per worker, and explicitly in `multi_shard_transaction.c` for DDL, INSERT..SELECT, master_modify_multiple_shards. The reason we need to do this is that we might otherwise deadlock if a transaction modifies multiple tables that have a foreign key between them. The first command in the transaction could take certain locks on a referenced table that would prevent a second command on a  referring table from completing if it used a separate set of connections.

In COPY we currently avoid this problem by committing at the end of the statement meaning all the locks on the workers are released by the time we run the second COPY statement. This allows us to run multiple COPY commands in the same transaction without a problem, except it is not actually performed as a transaction. When we make COPY transactional then the problem described above will exist for COPY as well.

For example, a user might perform a transaction in which he first copies in a set of sessions, and then a set of events for those sessions. If there is a foreign key from events to sessions on the session ID, then copying in events over a different set of connections would block until the sessions get committed, which they never will.

At some point, we may want to build a more structural solution into the connection API, but for this we'll need a faster way of looking up sets of co-located shard placements (#1098), which requires some non-trivial amount of work.

For the moment, we can use the same logic in COPY as we do with DDL, namely looking up a connection using GetShardConnections. However, the logic in GetShardConnections that maps co-located shards to the same connection is ludicrously inefficient. To avoid paying this price very often, COPY should keep using its own hash for looking up a connection for a given row and only call GetShardConnections where it currently opens a new connection.

This change will also allow COPY to appear in the same transaction as DDL and other multi-shard commands.

**Comment by anarazel** [comment]
There's no need to do any of the colocation aware stuff on the level of copy. #1120 will do that below GetPlacementConnection. So you should just use that, which will make copy aware once #1120 is merge.d

**Comment by anarazel** [comment]
Closed via #1133
