### ISSUE TITLE
Introduce a fast way of looking up a set of co-located shards/placements

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1098]
To avoid deadlocks between operations that work on co-located tables with foreign keys between them in the same transaction, we need to always use the same connection for co-located placements. To achieve this we need to be able to assign an identifier to a set of co-located shards or placements.

We currently have some fairly inefficient logic for looking up a common shard identifier in the DDL/INSERT..SELECT/master_modify_multiple_shards logic in `GetShardConnections` in `multi_shard_transaction.c`. Even without caching, this does 2 separate index scans on the database for every connection look-up.

```
    /* database look-up for a single shard */
    ShardInterval *shardInterval = LoadShardInterval(shardId);
    
    /* database look-up of all co-located tables in a co-location group and extract shard IDs */
    List *colocatedShardIds = ColocatedShardIntervalList(shardInterval);

    /* O(N) search for N co-located tables*/
    ShardInterval *baseShardInterval = LowestShardIntervalById(colocatedShardIds);
```

This code uses the lowest shard ID in a set of co-located shards as the identifier for a set of co-located placements.

As we unify our transaction management (#704) and expand it to allow a wide range of transactions, we will need to perform this mapping a lot more often. For example, to allow an INSERT on table A to follow a DDL command on a co-located table B with a foreign key from A to B, then we should perform this mapping prior to the INSERT to ensure it does not create a deadlock.

To make this mapping a lot faster, we should expand our metadata cache to include co-location information at a shard- or placement-level in a way that enables fast look-ups or assigns an identifier upfront.

Note that `GetShardConnections` assigns an identifier to a set of co-located shards, but we may only care about identifying sets of co-located placements, since the new connection API (#1079) uses placement IDs. Also note that an identifier for a set of co-located placements can always be derived from the identifier of a set of co-located shards by including the nodename and nodeport.

**Comment by anarazel** [comment]
I've spent some time thinking about how to implement this best. My conclusion is pretty much in line with Marco's above (not surprising since we'd discussed in person).   In particular:
> To make this mapping a lot faster, we should expand our metadata cache to include co-location information at a shard- or placement-level in a way that enables fast look-ups or assigns an identifier upfront.

The biggest issue with computing such an identifier is that that seems to boil down to colocationGroupId and 'shard offset' (the offset in a sorted list of shards). The offset isn't cheap to compute though, thus we don't want to do that for every LoadShardInterval() / ShardPlacementList() call (the former are hard to avoid).  Hence we need to build infrastructure to store that in the metadata cache.

It seems the best way to do so is to maintain a second hashtable in metadata_cache.c that maps from shardId -> (DistTableCacheEntry*, offset).  That table then can back LoadShardInterval(), which'll return a copy of DistTableCacheEntry->sortedShardIntervalArray[offset].   Because LoadShardInterval() now references the cache - where all intervals are loaded and sorted anyway - we can easily compute and store both the group and offset in the ShardInterval struct.

We also need the same information for placements - but that's a bit easier. Essentially we should just store an array of ShardPlacement lists in DistTableCacheEntry. As ShardPlacementList() is the only thing returning/loading ShardPlacement structs we can just make that access the metadata cache (via the shardId hash) fairly easily.

Besides providing the basis for more efficient lookup of such an 'colocation placement identifier', this will also make our metadata accesses a good bit more efficient.

I'm not sure if that leaves us with a need to implement exactly what $topic says - there'd not be any user of ColocatedShardIntervalList() left, and I'm not quite sure I see what future users would be?  I'd like to avoid having a cache that'd essentially be reloaded whenever something in any colocated table changes.

There might later be another use-case for efficiently caching/returning the set of tables in one colocation group (i.e. ColocatedTableList()/ColocationGroupTableList()), but that seems like a different topic.  With that information one could easily build the list of colocated shards / placements by returning stuff from the DistTableCacheEntry->sortedShardIntervalArray/arrayOfShardPlacementArrays/ from all the colocated tables.

**Comment by anarazel** [comment]
We discussed this some more, and decided to use a different identifier 'colocated shard placements'. The reason for reconsidering is that the above 'index' won't be stable if we add the ability to split shards.

The approach we decided to take instead is to build that identifier out of (host,port,database?,colocationGroupId, shardMinValue) for hash/range partitioned tables, (host,port,database?, shardId) for append and reference tables.  Even if a shard is split, the min value will still refer to something meaningful.  We can do that by adding custom compare/hash functions.  To avoid the issue that a range partitioned table potentially might not be hash-able, we just hash the underlying data.

**Comment by anarazel** [comment]
Hm, it seems like we can just declare that anything that's repmodel != HASH/RANGE just doesn't go through the additional hashtable; since there'd never be anything in there that's not already associated with the placement.  That simplifies the mapping logic a bit.

I'm inclined for now to exclude range partitioned tables from this consideration for now, since that requires dealing with possibly arbitrarily complex shardMinValues, instead of just a uint32.  Also it appears that they currently don't support colocation:
```
static bool
ShardsIntervalsEqual(ShardInterval *leftShardInterval, ShardInterval *rightShardInterval)
{
...
	/* append and range partitioned shard never co-located */
	return false;
```
(FWIW, a lot of the function names in colocation_utils are way to generic, the above as an example)
