### ISSUE TITLE
UPDATE on multiple shards natively works

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#1131]
When a user has the real-time analytics use case, modification commands (e.g. record.update!(field: 'value') in #595) might open transactions involving multiple tables or shards. Right now, when running in a transaction, any DML command that opens a connection to a second node will error out.

In our documentation, we ask our users to call ``master_modify_multiple_shards`` to update records across multiple shards. We talked about natively integrating this into ``UPDATE`` statements. One question however was related to users' expectations: since this operation touches across multiple shards, concurrent ``UPDATE`` commands need to run in serial to avoid deadlocks. Do we want to inform the user about this behavior? (maybe through a ``NOTICE`` message)

**Comment by lithp** [comment]
Some more questions:

- `master_modify_multiple_shards` isn't exactly performant, especially when using 2PC (soon to be the default?)
- `master_modify_multiple_shards`, when using 2PC, doesn't do any kind of automatic recovery after node-failure.
- `master_modify_multiple_shards` has the deadlock issue you already described
- If you have a replication factor > 1 and the query fails on a placement , most `UPDATE` queries will still attempts to modify the remaining placements. `master_modify_multiple_shards` doesn't care and fails the query if any of the placements fail

Will users understand that there are two kinds of queries, both called `UPDATE`, which happen through entirely different mechanisms, and which you should treat very differently?

--

If our eventual plan is to make Community absorb all of MX, this makes that eventual transition more difficult. Supporting `UPDATE` across multiple shards is a distributed transaction which we can _kind of_ cheaply get away with because we have a single master. Once that goes away this gets... tricky. Are we okay with that?

(All of the above also applies to `DELETE`, and therefore #1130)

**Comment by marcocitus** [comment]
I think the scope of this issue is mainly to provide the basic UX/compatibility for multi-shard UPDATE/DELETE, with some mechanism for informing the user about how much it sucks for short writes.

Longer-term, I have some thoughts around how to do multi-shard updates efficiently. The basic idea is to assign each multi-shard transaction a unique priority (timestamp + node ID) and use save points to be able to cancel an individual update/delete on a shard when priority inversion occurs (i.e. a high-priority transaction blocks waiting on row-level lock held by a low-priority transaction). This is a bit involved since we'll need to keep a pid -> priority mapping in shared memory, monitor pg_locks, make updates on shards that violate priority error out, and make the executor aware of all of this. The advantage is that updates run as fast as possible when there is no conflict and will typically only take a "small" latency and table bloat penalty when there is a conflict.

To avoid the overhead of opening many connections we could send all the updates over a single connection per worker. Ideally, we would have some statistics based on which the planner can make the decision whether to use a single cached connection or multiple new connections. In the absence of that we could have some basic heuristics such as: use a single connection if there is any equality filter, multiple connections otherwise.

**Comment by ozgune** [comment]
@lithp / @marcocitus -- We chatted about the requirements earlier this week, primarily for DELETE. I wanted to drop a note here for completeness. (adding inlines to @lithp's comments)

> master_modify_multiple_shards isn't exactly performant, especially when using 2PC (soon to be the default?)

I suspect this might be an issue on the ``UPDATE`` side, but not on the ``DELETE`` side. Most users who ask about ``DELETE`` support are asking how they can expire their old data. For example, I'd like to expire events from 91 days ago around midnight. In that case, their primary question revolves around vacuuming. (edited #1130 with a few examples)

> master_modify_multiple_shards, when using 2PC, doesn't do any kind of automatic recovery after node-failure.

How true is this? For example, if one of the nodes in the cluster is unavailable and then we start ``master_modify_multiple_shards``, we're going to error out. I'm guessing this scenario is more likely for data expiration -- if you're running a command around midnight, it's way likelier that you have one node failed than that node failed in the middle of your data expiration operation.

I know there's a small window where we send PREPARE to PG, get ack'ed, and then send the actual commands and one of the nodes fails during the command. That said, isn't it a bit unfair on 2PC to say that we don't do any kind of failure handling.

> If you have a replication factor > 1 and the query fails on a placement , most UPDATE queries will still attempts to modify the remaining placements. master_modify_multiple_shards doesn't care and fails the query if any of the placements fail.

With 6.1, we're using a default replication factor of 1. If we're worried about our behavior, we could emit a notice / warning in this scenario. In practice, I suspect multi-tenant apps will care about this notably more than real-time ones.

> This ticket was linked from a ticket about Rails support. The kinds of users who are going to simply plug Citus into rails without thinking about these kinds of UPDATEs are exactly the kinds of users who might be bit by something unexpected happening here.

On the DELETE side, the primary question we heard was about expiring old events data. Those users were planning to run this command through psql / cron jobs. In that sense, I think their requirements might have been different than the one mentioned in #595.

**Comment by lithp** [comment]
> I know there's a small window where we send PREPARE to PG, get ack'ed, and then send the actual commands and one of the nodes fails during the command. That said, isn't it a bit unfair on 2PC to say that we don't do any kind of failure handling.

It's not unfair at all, since there are plenty of other protocols which don't have this problem :)

But also, while the participants have a small window for failure the master node could fail at any point during the 2PC and leave some state behind which needs to be recovered manually. If the master node fails during either the first or second phase then some nodes will have `PREPARE`d transactions sitting around and holding locks.

I believe our only answer for this second problem is to have a backup master node maintained with synchronous streaming replication, which I think none of our customers do?

**Comment by marcocitus** [comment]
> I believe our only answer for this second problem is to have a backup master node maintained with synchronous streaming replication, which I think none of our customers do?

Our current answer is to call `SELECT recover_prepared_transactions()` once the master comes back or its secondary gets promoted.

**Comment by onderkalaci** [comment]
> Our current answer is to call SELECT recover_prepared_transactions() once the master comes back or its secondary gets promoted.

Just noting that with deadlock detection we've added a maintenance daemon to Citus. There is an open PR, #1574,  that periodically calls `recover_prepared_transaction()` on the daemon which should fix the issues related to 2pc that are mentioned here.

**Comment by metdos** [comment]
@marcocitus I suppose we should merge #1574 as a prerequisite of this?

**Comment by marcocitus** [comment]
@metdos not strictly necessary, they are independent code paths.

**Comment by marcocitus** [comment]
:fireworks:
