### ISSUE TITLE
MX nodes do not allow PostgreSQL sequences to be dropped

### ISSUE THREAD

**Issue by metdos** [citusdata/citus#1181]
On a synced MX node, we are not able to drop regular PostgreSQL sequences.

```sql
-- connect to coordinator
psql -d postgres

-- add nodes
SELECT master_add_node('localhost', 9700);
SELECT master_add_node('localhost', 9701);

-- make one MX node
SELECT start_metadata_sync_to_node('localhost', 9700);

-- connect to MX node
psql -d postgres -p 9700

-- create a PostgreSQL table with sequences
CREATE TABLE mx_table_with_sequence(a int, b BIGSERIAL, c BIGSERIAL);

-- try to drop it
DROP TABLE mx_table_with_sequence;
ERROR:  operation is not allowed on this node
HINT:  Connect to the coordinator and run it again.
CONTEXT:  SQL statement "SELECT master_drop_sequences(sequence_names)"
PL/pgSQL function citus_drop_trigger() line 35 at PERFORM
```

**Comment by aamederen** [comment]
This is an interesting bug from the user perspective: you create a sequence but cannot drop it. The reason of that behavior is this:

On MX workers there are 3 types of sequences:
1. Sequences created by the user explicitly, like in the case of the given example
2. Sequences as part of the serial columns of shards, in this case they are not used but necessary for shard tables.
3. Sequences as part of the MX tables, these sequences are used for inserts from workers.

Ideally we should allow the `DROP SEQUENCE` in the first case but prevent user to drop the sequence on case 2 and 3. Currently, we don't allow users to drop any sequences on workers because we cannot distinguish between these three cases easily. 

We can detect the case 3 by checking the MIN/MAX value of the sequence, since they are set to non-overlapping regions in each worker. I don't know if there is an easy way to detect case 2. One other option could be introducing metadata about distributed sequences but I am not sure if it is worth it.

@ozgune @marcocitus Do we expect users (or @samay-sharma and @saicitus) to connect to a data node and create a sequence for some reason? I think it is unlikely since we advertise data nodes as for DML and SELECT operations only?

**Comment by anarazel** [comment]
On 2017-01-31 09:21:49 -0800, Eren Başak wrote:
> This is an interesting bug from the user perspective: you create a sequence but cannot drop it. The reason of that behavior is this:
> 
> On MX workers there are 3 types of sequences:
> 1. Sequences created by the user explicitly, like in the case of the given example
> 2. Sequences as part of the serial columns of shards, in this case they are not used but necessary for shard tables.
> 3. Sequences as part of the MX tables, these sequences are used for inserts from workers.
> 
> Ideally we should allow the `DROP SEQUENCE` in the first case but prevent user to drop the sequence on case 2 and 3. Currently, we don't allow users to drop any sequences on workers because we cannot distinguish between these three cases easily. 
> 
> We can detect the case 3 by checking the MIN/MAX value of the sequence

That sounds very fragile.

> , since they are set to non-overlapping regions in each worker. I don't know if there is an easy way to detect case 2. One other option could be introducing metadata about distributed sequences but I am not sure if it is worth it.

We could just do it via dependencies of those sequences to the citus extension.


> @ozgune @marcocitus Do we expect users (or @samay-sharma and @saicitus) to connect to a data node and create a sequence for some reason? I think it is unlikely since we advertise data nodes as for DML and SELECT operations only?

Seems not that unlikely actually, because of workarounds around our
distributed queries limitations and such, where you create temp tables
and everything.

**Comment by marcocitus** [comment]
We should just remove the EnsureCoordinator() call in master_drop_sequences. If the sequence belongs to a distributed table then the uset won't be able to drop it on the worker anyway.

**Comment by aamederen** [comment]
>We should just remove the EnsureCoordinator() call in master_drop_sequences. If the sequence belongs to a distributed table then the uset won't be able to drop it on the worker anyway.

We leave the responsibility to the user in case of `DROP SEQUENCE ... CASCADE` then?

**Comment by marcocitus** [comment]
Wouldn't that hit an EnsureCoordinator() call in the drop table trigger? If not that's another bug :).

**Comment by aamederen** [comment]
> Wouldn't that hit an EnsureCoordinator() call in the drop table trigger? If not that's another bug :).
The `DROP TABLE` is prevented in `master_drop_all_shards` step for the tables :).

I was thinking about the prevention of dropping sequences which the shards depend, but we actually have no safety check for shard deletion. Since the issue is bigger that the sequences, maybe we can fix it by just removing `EnsureCoordinator()` call in `master_drop_sequences` as you mentioned and think this in a broader context.

**Comment by marcocitus** [comment]
> The DROP TABLE is prevented in master_drop_all_shards step for the tables :).

So if we remove the EnsureCoordinator call from `master_drop_sequences` and the user does a DROP SEQUENCE .. CASCADE on a sequence that belongs to an MX table from a worker, then that would cascade to the distributed table and thus error out in `master_drop_all_shards`, as expected. I don't think we need to worry about the user dropping a sequence that has *only* shards depending on it when there is a mixture of MX and non-MX tables.

**Comment by marcocitus** [comment]
Btw, I think it's pretty critical that we fix this, since custom Citus solutions might rely on sequences (e.g. to generate a unique staging table name) and we might be prohibiting certain extensions if they perform a DROP SEQUENCE in one of their upgrade scripts.
