### ISSUE TITLE
master_append_table_to_shard does not support transactions

### ISSUE THREAD

**Issue by byucesoy** [citusdata/citus#1188]
If we use master_append_table_to_shard in a transaction then ROLLBACK, we are not removing the copied data from the shard.

```sql
CREATE TABLE local_table(column1 int);
INSERT INTO local_table VALUES(1);

CREATE TABLE distributed_table(column1 int);
SELECT create_distributed_table('distributed_table', 'column1', 'append');
SELECT master_create_empty_shard('distributed_table');
 master_create_empty_shard 
---------------------------
                    102008

BEGIN;
SELECT master_append_table_to_shard(102008, 'local_table', 'localhost', '5432');
ROLLBACK;

-- shard still contains the data
 SELECT * FROM distributed_table;
 column1 
---------
       1
```

Similarly if an error occurs during transaction, shard still contains copied data.

**Comment by lithp** [comment]
hmm...

**Comment by marcocitus** [comment]
Seems we forgot to add a RemoteTransactionBeginIfNecessary after getting the connection, which prevents it from rolling back.

**Comment by lithp** [comment]
Why doesn't the `ROLLBACK;` command generate an error? Shouldn't the worker say it's not in a transaction?

**Comment by marcocitus** [comment]
Currently, the command is executed in the same way as single-statement DML, in which case we don't send  commit/rollback to the workers at all; we just send a single statement that immediately commits.

**Comment by lithp** [comment]
Okay, figured it out. I was confused because [our callback for the `ROLLBACK` command](https://github.com/citusdata/citus/blob/master/src/backend/distributed/transaction/transaction_management.c#L190) actually sends `ROLLBACK` to the workers. But it turns out it doesn't, because `CoordinatedRemoteTransactionsAbort` only propagates to connections which have had `RemoteTransactionBegin` called on them.

Some solutions for solving this in the general case:
- Methods which return connections should call `RemoteTransactionBeginIfNecessary` automatically.
- Methods which return connections should add them to `InProgressTransactions` automatically?
- `CoordinatedRemoteTransactionsAbort` should propagate to all connections this session used / sent DML commands down, not just ones in `InProgressTransactions`?

**Comment by marcocitus** [comment]
Well, we should still be able to support router executor without transaction blocks, connections outside of the coordinated transaction, and asynchronous connection establishment.

I would like an approach where we can do something like `GetPlacementConnection(FOR_DML | IN_TRANSACTION, nodename, nodeport)`, which automatically ensures that the connection has a transaction block open that gets committed at the end. This flag would only be supported by GetPlacementConnection, not by StartPlacementConnection.

Similarly, I would like us to avoid the need for calling MarkTransactionCritical by having a flag like `GetPlacementConnection(CRITICAL | FOR_DML | IN_TRANSACTION, nodename, nodeport)`.

**Comment by lithp** [comment]
A `IN_TRANSACTION` param doesn't really win us anything, not even line count! You still have to remember to pass it in. Preferably it'd be impossible to accidentally make this mistake.

> Well, we should still be able to support router executor without transaction blocks, connections outside of the coordinated transaction, and asynchronous connection establishment.

If you want to use something outside of a transaction block, don't call `BeginOrContinueCoordinatedTransaction`.

A connection outside of the current transaction sounds like the exception, so create an additional method called `GetNonTransactionalPlacementConnection`. (Or, as you're suggesting, a `NOT_IN_TRANSACTION` param)

I think async connection establishment already uses `StartPlacementConnection`, instead of `GetPlacementConnection`. Although I suppose making `GetPlacementConnection` automatically start a transaction but not `Start...` would be a confusing inconsistency.

**Comment by marcocitus** [comment]
NOT_IN_TRANSACTION could also work, that seems logically equivalent. The goal is not to reduce line count, but to reduce complexity and set better examples. Function calls like BeginOrContinueCoordinatedTransaction, RemoteTransactionBeginIfNecessary, and MarkTransactionCritical end up being scattered and it's easy to forget one and not obvious which ones you need and how they interact. If you reduce that to one or 2 binary decisions that you always make in the same place, it becomes a lot more obvious.
