### ISSUE TITLE
Allow Custom Aggregates

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus#120]
We currently have a hard-coded white-list for aggregates. For commutative/associative aggregates, we overload the `sum` function definition. We'd like to allow people to define their own transition/final functions and define them for use and pushdown in Citus.

**Comment by lithp** [comment]
This just came up in a call with a client

**Comment by lithp** [comment]
This appeared again in engage@

**Comment by ozgune** [comment]
This feature request recently came up in citus-users (and a related email thread to engage@). I'm capturing it here for reference purposes: https://groups.google.com/forum/#!topic/citus-users/5Jd2zbxAs3Q

**Comment by lithp** [comment]
This came up again in the form of #1419

**Comment by lithp** [comment]
We should be able to support both of these cases:
- Any aggregate of the form `f: a, a -> a`
- On pg 9.6 and higher, any aggregate which sets a combinefunc (Has a "[partial mode](https://www.postgresql.org/docs/9.6/static/functions-aggregate.html)" )

Unfortunately, there are useful aggregates this doesn't include:
- `[hll_union_agg](https://github.com/aggregateknowledge/postgresql-hll/blob/master/hll--2.10.0.sql#L465)`
- `jsonb_agg`

**Comment by lithp** [comment]
- Both `hll_union_agg` and `jsonb_agg` support can be added by the user by creating a custom aggregate which includes a combinefunc.
- Any functions which use the `internal` transtype must specify a `serialfunc` and `deserialfunc`
- We still need to special-case count-distinct but code which specifially handles "count", "min", "max", "avg", etc, can be removed.

**Comment by lithp** [comment]
Tasks:
- [ ] WorkerAggregateExpressionList no longer needs to special case `AGGREGATE_AVERAGE`, averages can simply be pushed down

**Comment by lithp** [comment]
- [ ] Test that this works for #1419, we should be able to automatically pickup and pushdown enum_smaller

**Comment by lithp** [comment]
(Note: this is all wrong and this change is a lot more work than I expected, going to delete these comments and add a new one with a more fleshed out proposal)

**Comment by lithp** [comment]
**Proposal**

Create two aggregates;
- `worker_run_agg(aggregate oid, anyelement value)`,
-  and `coord_run_agg(aggregate oid, anyelement value)`.

These functions only work when passed aggregates which have a `combinefunc`. In worker queries the aggregate is replaced with a call to `worker_run_agg(aggregate, col)`, and in coordinator queries the aggregate is replaced with a call to `coord_run_agg(aggregate, intermediate_result.col)`, Internally, the functions emulate this behavior:

- worker: `serialfunc(Aggref(sfunc, col))`
- coord: `finalfunc(Aggref(combinefunc, deserialfunc(col)))`

In this way we can remove our code which special cases support for `count`, `average`, `min`, `max`, and `sum` and in the same commit add support for nearly every aggregation postgres provides!

**Motivation**

Starting with postgres 9.6 aggregates expose [how to combine intermediate results](https://www.postgresql.org/docs/9.6/static/xaggr.html#XAGGR-PARTIAL-AGGREGATES), even for aggregates which are not usually associative. They do this by defining a `combinefunc` which can be used to merge multiple `internal-state` fields.

The special functions are necessary for two reasons:
1. We need to generate plan trees which can be deparsed into SQL which the workers run. This precludes directly calling functions like `int8_avg_serialize`.
2. The only other way to represent the `Aggref(sfunc` from above is by creating new aggregates on the fly.

**Details**

- Since we're passing `stype` over the wire, if `stype` is `internal` there must also be a `serialfunc` and `deserialfunc`!

There are a few supporting functions:

- `worker_agg_sfunc(internal, aggregate oid, anyelement value)`
- `worker_agg_ffunc(internal)`
- `master_agg_sfunc(internal, aggregate oid, anyelement value)`
- `master_agg_ffunc(internal)`

Internal will have to be a struct which includes the oid of the aggregate we're using, so that we know which `serialfunc` and `finalfunc` to use.

---

Unfortunately, some aggregations which don't have a `combinefunc` seem pretty important: `array_agg`, `json_agg`, `jsonb_agg`, `hll_union_agg`, `hll_add_agg`. Even more unfortunately, the user can't just create new ones because those all use an `internal` stype. I can think of two ways to support them?
1. create and distribute our own `combinefuncs` for these important functions, which can be used to create more friendly aggregates.
2. Somehow support pushing down one aggregate and merging with another aggregate? If it were possible to call the `finalfunc` on the value the workers return we could then use a user-written `combinefunc` which merged those arrays, jsonbs, or hlls.

**Questions**

- [ ] How do we support aggregates like `jsonb_agg`?
- [ ] MasterAggregateExpression turns `count(col)` into `COALESCE(Aggref(sum, collected_results.counted_col)::bigint, 0)`. Why does it do the cast? Is this still necessary, or can we remove this special case? (line 1529 of multi_logical_optimizer)
- [ ] Does this actually solve #1419? we should be able to automatically pickup and pushdown `enum_larger`, but Metin points out that means we need to lookup aggregates by equivalence class instead of exact match, which might be independent of this change

**Comment by marcocitus** [comment]
> MasterAggregateExpression turns count(col) into COALESCE(Aggref(sum, collected_results.counted_col)::bigint, 0). Why does it do the cast? Is this still necessary, or can we remove this special case? (line 1529 of multi_logical_optimizer)

Sum returns NULL for 0 rows, but count should return 0. I imagine the combinefunc would take care of this.

**Comment by marcocitus** [comment]
> How do we support aggregates like jsonb_agg?

I think we can just keep special-casing them, e.g. https://github.com/citusdata/citus/commit/ad1824fea2458bea03c577d4b59f3c33a700acfb

**Comment by lithp** [comment]
Recording another option which came up in our call. We could create a new metadata table `pg_dist_aggregate` which contained this kind of compatibility information. It'd look something like

```
CREATE TABLE pg_dist_aggregate (
    aggregation oid,
    intermediate_finalfunc oid,
    combinefunc oid,
    dist_finalfunc oid
);
```

When planning a query, if the coordinator saw an entry in `pg_dist_aggregation` matching the aggregate which is being used it would still generate the `worker_run_agg` and `coord_run_agg` functions, but they would represent slightly different plantrees:

- worker: `intermediate_finalfunc(Aggref(sfunc, col))`
- coord: `dist_finalfunc(Aggref(combinefunc, col))`

This would allow us to support `jsonb_agg`. Our `intermediate_finalfunc` would be `jsonb_agg_finalfunc`, the finalfunc which already exists and turns that nasty internal type into a serializable jsonb. The combinefunc would be `||` (concatenation). There's no need for a `dist_finalfunc`.

I believe this also enables support for `hll_union_agg` and `ST_Union`, the user just has to add a few entries to `pg_dist_aggregate` which reference functions which already exist.

**Open question**: In order for `worker_run_agg` to know to run the `intermediate_finalfunc` it either needs to also have a copy of `pg_dist_aggregate` or include another parameter which tells it what to do. I'm not sure how that should look.

**Comment by jasonmp85** [comment]
For `hll` we can just add the necessary functions to the extension ourselves, since our package has long been building from a `citusdata`-owned fork!

**Comment by jasonmp85** [comment]
(Assuming we know how to write them)

**Comment by marcocitus** [comment]
Something worth considering for an upcoming release. Worth noting that PostGIS added combinefuncs for all their aggregates.

**Comment by saicitus** [comment]
The following aggregates have surfaced up in customer conversations:
```
hll_add_agg
hll_union_agg
topn_add_agg
topn_union_agg
bool_or
ST_Union (in postgis extension)
```

**Comment by seamusabshere** [comment]
```
first
last
ST_Collect
```

please please please

**Comment by fdr** [comment]
This has caused some distress on account of `ALTER EXTENSION postgis UPDATE;` with PostGIS 2.5.

**Comment by serprex** [comment]
`combinefunc` implementation pull requests have been created for [hll](https://github.com/citusdata/postgresql-hll/pull/73) & [topn](https://github.com/citusdata/postgresql-topn/pull/31)

**Comment by serprex** [comment]
So until we have `oid` being synchronized across workers/coordinator, we may need to setup a metadata table for which aggregates support cross database aggregation: array serialization assumes type oids match on process that's deserializing

**Comment by marcocitus** [comment]
Is the OID problem specific to things like array_agg(custom_type) or something we need in general?

I don't think we'll ever fully synchronize OIDs because a lot of custom types will be created by extensions over which we have little control.

**Comment by serprex** [comment]
It depends on the serialize/deserialize. For an array of ints we're fine because builtin types have consistent OIDs. Essentially code is allowed to assume that OIDs translate between postgresql processes. I don't expect PostGIS to leverage that assumption
