### ISSUE TITLE
Decouple replication of reference tables from master_add_node

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#1200]
We had an internal meeting related to decoupling the replication of reference tables from ``master_add_node()``. We decided to do the following:

* We're revising our upgrade policy with 6.2 onwards. Starting with this release, we'll add columns to our metadata tables (system catalogs) and force users to Alter Extension Upgrade.
* Since we can now add a column to metadata tables, we can implement this UDF in a more intuitive way (Marco's email below). We add this column and implement the UDF accordingly right after the 6.1 release. (Uninformed minor question: We will have two boolean columns to indicate status -- are these better represented as enum fields?)
* @fdr noted that he could do one of two things: (1) pick up a 6.1-cloud release that has the above system catalog changes or (2) wait until 6.2 anticipating that reference tables won't be a big problem. The first one is more ideal and we'll likely do a small release called 6.1-cloud for the Cloud.

--

I'm also copy/pasting @marcocitus' email on how we decouple metadata propagation from adding nodes in Citus MX.

Arguing with myself: While there might not be a clean way, it is pretty much necessary to do add_node before the node is running for things like auto-HA. e.g. in the original MX prototype we would first
add a node to decide whether it would be primary/secondary and in which group *before* we could start the node. In that case, there's no way we could replicate the reference tables to that node on
master_add_node or use it for anything else.

In MX there was a second step called cluster_activate_node. A node would not be used for anything before it was activated (reflected by an isactive column in pg_dist_node), and when it got activated it also got a copy of the metadata. In Citus 6.1, we opted for decoupling metadata syncing and node activation, which allowed us to make MX optional and simplified pg_dist_node syncing.

In this case, it seems that what we would really want is for the activate step to come back in order to replicate reference tables before we use a node. While a node is inactive, we can assume it to be
not yet up-and-running and would not assign any new shards to it. This avoids any situation where reference tables are under-replicated. At some point, we will also want to replicate global objects such as roles, schemas, and functions upon node activation. We probably don't want to change the API again in the next release, so it might be a mistake to make it very reference table-specific.

Strictly speaking, we would need a new column in pg_dist_node (isactive), but we've more or less decided not to do metadata changes in 6.1. With our current feature set, we could live with a situation
in which reference tables are temporarily under-replicated so we could add that later.

**Comment by ozgune** [comment]
I'm also noting #1159 as a related old pull request. Instead of this approach, we decided to move forward with adding a column to system catalogs and follow an approach that's similar to MX's.

**Comment by onderkalaci** [comment]
> I'm also noting #1159 as a related old pull request. Instead of this approach, we decided to move forward with adding a column to system catalogs and follow an approach that's similar to MX's.

Note that the PR is already implementing similar approach with MX where we have `master_add_node()` and `master_activate_node()`. The only missing part is that in the PR to understand the `activeness` of the node, we check whether all the reference tables are replicated to that node. So, I could say that the PR is `~75` ready 😄

**Comment by metdos** [comment]
@byucesoy, I guess you didn't hear back from @ozgune, @samay-sharma, @fdr. @byucesoy, could you set up a meeting with @ozgune, @samay-sharma and @fdr early next week and finalize the requirements?

@byucesoy, I think you're blocked on requirements for this task, am I right?

**Comment by byucesoy** [comment]
I already wrote to our internal e-mail but I will also write here;

# Problem
With the introduction of reference tables in Citus 6.0, we started to replicate reference tables to the newly added nodes with master_add_node UDF. This approach caused some problems;

- Replicating reference tables is not a cheap operation. It may take long time and have higher probabilty to fail than just adding new node to metadata.
- master_add_node started to contain too much logic.
- Citus Cloud needs a way to add new node to the cluster without doing costly reference replication.

Therefore we decided to decouple master_add_node and replicating reference tables.

However that means there will be times where some newly added nodes will not have reference tables replicated. In that case, we should not send queries using reference tables to that nodes, moreover we should not create new shards on those nodes. This is necessary because, since reference tables are not replicated on those nodes, many functionalities will not work as expected such as JOINs with reference tables.

# Design Proposal
**Proposal:** _We will have notion of explicit active/inactive node. To indicate whether a node is active or inactive it we will add nodestate column to pg_dist_node which. We will not mark a node as active until all reference tables are replicated to this node. If a node is inactive we will not create a shards on it and we will not use it during query execution._

As an implementation detail this column will be in int type. Using boolean is not feasible because we may want to add new states in the future. Using ENUM is not feasible too because citus.sql script runs in s transaction and it is not possible to modify ENUM type in transaction (PostgreSQL’s limitation)

**Proposal:** _Add new UDFs for Citus Cloud’s needs._

**master_add_inactive_node(nodename, nodeport)**

This UDF will add the node to the pg_dist_node without activatinng(i.e. without replicating reference tables)

**master_activate_node(nodename, nodeport)**

This UDF will activate previously added nodes.

Apart from that we will not change behaviour of master_add_node. Because current user’s of it expects automatic replication of reference tables. We will just its internal so that master_add_node will use internals of master_add_inactive_node and master_activate_node, so that master_add_node will not contain extra logic. On higher level, it will still perform more than one task but this is necessary to have backward compability.

# Additional Notes
Cuurently we also have master_disable_node UDF, which removes a node from pg_dist_node. We implemented this UDF so that it will be possible to put a node to a maintanence mode by preventing issuing SELECT queries on that node. As a future improvement of this proposal, it makes sense to change master_disable_node to set nodestate from active to inactive in pg_dist_node instead of removing the node. Then we should not send SELECT queries to that node.

# Overall Evaluation
Problems we solved with this proposal:
- Citus Cloud team will have a UDF to add a node without replicating reference tables
- We will add nodestate column to identify active/inactive nodes. This will be also useful in our other features like auto-HA.
- master_add_node will be backwards compatible. We do not need to release major version
- master_add_node will not have a flag parameter(as Ozgun suggested referencing this and this)

Areas we improved:
- master_add_node will still perform more than one operation but at least it will delegate most of the logic to other functions.

Problems we did not solve:
- Citus Cloud will need to do a version check to decide which function they will call (master_add_node or master_add_inactive_node). It seems that there are already similar version checks in the script which creates cluster. Therefore I think this is minor issue.
