### ISSUE TITLE
DDL commands, with high shard counts, fail with an uninformative error message

### ISSUE THREAD

**Issue by lithp** [citusdata/citus#1211]
(Old title: `ALTER TABLE` opens a connection for every placement)

An example error:

```
ec2-user=# ALTER TABLE replicate_this DROP COLUMN kets;
WARNING:  connection error: 10.192.0.165:5432
DETAIL:  no connection to the server

ERROR:  failure on connection marked as essential: 10.192.0.165:5432
```

This is closely related to #709, however that ticket is about the failure. This ticket is merely about the error message we give upon failure.

The error on the worker side is: `FATAL: sorry, too many clients already`, which is better but not as understandable as it could be.

**Comment by anarazel** [comment]
That's a 6.0 decision/change, not a 6.1 one, right?  And made consciously.  In other words, not a bug, but a missing feature.

If so, could you rename the issue?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ozgune** [comment]
@lithp -- We have an open issue on erroring out early when this happens, with an error message that's easy to understand. We currently track that in #709 (or #710 in another scenario).

It looks like #709 and #1211 overlap. What do you think?

**Comment by lithp** [comment]
@ozgune, I looked at that ticket and you're right it's a duplicate, but I didn't see any mention of making the error message more descriptive. Changed the title and description of this ticket, what do you think of it now?

**Comment by metdos** [comment]
> @ozgune, I looked at that ticket and you're right it's a duplicate, but I didn't see any mention of making the error message more descriptive. Changed the title and description of this ticket, what do you think of it now?

Aha, I knew that I remember the issue from somewhere as being the writer of the original issue :)

**Comment by ozgune** [comment]
@lithp -- I think we have two options on fixing this.

1. We either look at our current max_connections. If the DDL message is going to touch notably more shards, we error out early with a descriptive error message (#709).
2. We ran the DDL command. Once we start running into a warning or error, we then check against our current max_connections, infer that we ran into the connection limit, and error out with a descriptive message.

In either case, we should produce an error that's more descriptive than what we have (since we don't have any logic right now).

I'll add to #709 that we should display a descriptive error message and then close this issue. If that doesn't work, could you reopen this one?

**Comment by lithp** [comment]
The error message is different because that ticket was opened before the new connection API had been merged in. If it were opened today it would have the same message.
