### ISSUE TITLE
Composite fields in INSERT/UPDATE column list causes Assert failure or not handled properly

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1293]
Example from PostgreSQL regression tests:

```
create type insert_test_type as (if1 int, if2 text[]);
SELECT run_command_on_workers('create type insert_test_type as (if1 int, if2 text[]);');

create table inserttest (f1 int, f2 int[], f3 insert_test_type, f4 insert_test_type[]);
SELECT create_distributed_table('inserttest','f1');

insert into inserttest (f1,f3.if1, f3.if2) values (0,1,'{foo}');

TRAP: FailedAssertion("!(list_length(fstore->fieldnums) == 1)", File: "utils/ruleutils_96.c", Line: 7077)
```

**Comment by jasonmp85** [comment]
Not sure this is called indirection: think it's "field access". Updating title.

**Comment by anarazel** [comment]
On 2017-03-28 13:22:31 -0700, Jason Petersen wrote:
> Not sure this is called indirection: think it's "field access". Updating title.

It's called indirection in the code - and also works for arrays, so
field access wouldn't be a whole lot more descriptive.

**Comment by jasonmp85** [comment]
Ah, TIL (I thought the period token had a special name like that but didn't go look at the code).

"Indirection" is certainly the better word for searching mailing lists, e.g. [this](https://www.postgresql.org/message-id/CAFjFpRcJjqmbrRCgRiZG=WixdHjzEfQknwxP6-nN4f1ubhLbEg@mail.gmail.com).

**Comment by onurctirtir** [comment]
https://github.com/citusdata/citus/blob/a58a4395abec1e38d83629b66d1b33766c040897/src/backend/distributed/deparser/ruleutils_13.c#L7888-L7915

Debugged the issue a bit.

Realized that this function normally is called when creating insert/update definition for rule/trigger objects.
(For example, when action of rule/trigger object is to do per-field insertion)

And, the way postgres records such field inserts/updates in rule/triggers is different than how it actually executes such inserts/updates.

For rules/triggers, postgres records such field field accesses as is, in separate `FieldStore` objects so `processIndirection` works.

But when executing such inserts/updates, postgres combines field accesses (regarding the same column) into one so that `processIndirection` function assert fails. Postgres does that combining stuff somewhere in rewrite step:
https://github.com/postgres/postgres/blob/de3bbfcc962f24c1a20a17b76c604e5973a05817/src/backend/rewrite/rewriteHandler.c#L1042..L1051.

Also see: 
https://github.com/postgres/postgres/blob/41efb8340877e8ffd0023bb6b2ef22ffd1ca014d/src/include/nodes/primnodes.h#L784..L787

Actually more of the assertion failure, currently we don't properly handle such field accesses.

----

1- We can simply error out for such field insert/updates in planner or
2- We can perform separation of such accumulated `FieldsStore`s in those two functions in ruleutils `get_insert_query_def` & `get_update_query_targetlist_def` before calling `processIndirection.`
