### ISSUE TITLE
Improve shard pruning performance for deployments with 10K+ shards

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#1305]
When a query comes to the Citus coordinator node, the coordinator applies partition and join pruning logic. A few Citus deployments have over 100K+ shards, and our current partition pruning logic may introduce planning overhead on the order of seconds.

This issue tracks reducing that planning time for Citus deployments that have large shard counts.

**Comment by anarazel** [comment]
The underlying reasons for slowness in pruning performance is essentially fourfold:

1. Shard pruning for SELECTs is currently `O(#shards)`, because `PruneShardList` calls `predicate_refuted_by()` for every shard.  Obviously using an `O(N)` type algorithm for general pruning isn't good.
2. `predicate_refuted_by()` is quite expensive on its own right.  That's primarily because it's optimized for doing a single refutation proof, rather than performing the same proof over and over. 
3.  `predicate_refuted_by()` does not keep persistent state (see 2.) for function calls, which means that a lot of syscache lookups will be performed. That's particularly bad if the partitioning key is a composite key, because without a persistent FunctionCallInfo `record_cmp()` has to repeatedly look-up the type definition of the composite key. That's quite expensive.
4. `CoPartitionedTables()` does not use knowledge about colocation, instead comparing all shards.

The solution to these (except 4, which is trivial to fix) is not to use postgres' predicate proofing mechanism for pruning, but instead use an approach that first analyzes the predicates, and then either use binary search to search for the right shards (if possible), or use a more efficient (due to the separated extraction of predicates) linear search over the predicates.   I'll explain my current approach to this in more details in a prototype PR.
