### ISSUE TITLE
Add support for SAVEPOINT / ROLLBACK TO SAVEPOINT

### ISSUE THREAD

**Issue by lfittl** [citusdata/citus#1493]
The following pattern will currently not work with Citus, since we don't support rolling back to a savepoint in distributed transactions:

```
citus=> CREATE TABLE my_savepoint_test(id int);
CREATE TABLE
citus=> SELECT create_distributed_table('my_savepoint_test', 'id');
 create_distributed_table 
--------------------------
 
(1 row)

citus=> BEGIN;
BEGIN
citus=> SAVEPOINT my_savepoint;
SAVEPOINT
citus=> INSERT INTO my_savepoint_test(id) VALUES (123);
INSERT 0 1
citus=> ROLLBACK TO SAVEPOINT my_savepoint;
ROLLBACK
citus=> COMMIT;
ERROR:  cannot ROLLBACK TO SAVEPOINT in transactions which modify distributed tables
```

This is a common pattern in some frameworks (e.g. ActiveRecord), in particular for unit tests where savepoints are used to model nested transactions (i.e. the unit test has one big wrapping transaction, and explicit transactions in the application code are modeled as savepoints)

Whilst good to have both for single-shard and cross-shard use cases, for now this mostly seems to be a problem for the typical multi-tenant application use case where only a single shard (or tenant) is modified in the larger wrapping transaction.

**Comment by anarazel** [comment]
I think what we'd have to do is roughly the following:

In our, already existing, subtransaction handler we'd have to maintain an accurate stack of in-progress subtransactions - unfortunately we can't access the internal postgres datastructures for that. 

When a new savepoint is started (`SUBXACT_EVENT_START_SUB`) we have to push that onto our internal stack, send a `SAVEPOINT $n` to all connections that already have transactions started. When a worker transaction starts to participate in a coordinated transaction, we have to push a savepoint for all the in-progress subtransactions on our stack (otherwise we can't properly roll them back).  Whenever SUBXACT_EVENT_COMMIT_SUB / SUBXACT_EVENT_ABORT_SUB is received we have to send a `ROLLBACK TO SAVEPOINT $n` to all worker connections w/ transactions, and then pop the relevant subtransactions from our stack.

There might be one or two commands that we'll have to forbid from being executed with a non-empty subtransaction stack, particularly things that start worker transactions, but that are not bound to the scope of the "sql level" transaction. But perhaps we can do better there too.

**Comment by ozgune** [comment]
I'm adding to this thread another example just for reference. This example includes a transaction across two distributed tables (teams and step_groups) and one reference table (users), and the transaction includes SAVEPOINTs.

I was hoping @lfittl would open the savepoint issue after we close the Rails ticket 😄 

```
BEGIN
SAVEPOINT active_record_1
SELECT nextval('teams_id_seq'::regclass)
INSERT INTO "teams" ... RETURNING "id"
SELECT DISTINCT "step_groups".* FROM "step_groups" ...
RELEASE SAVEPOINT active_record_1
SAVEPOINT active_record_1
SELECT  "users".* FROM "users" WHERE ...
INSERT INTO "users"...
ROLLBACK TO SAVEPOINT active_record_1
ROLLBACK
```
