### ISSUE TITLE
Support cstore tables in citus_table_size

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1513]
`citus_table_size` always returns 0 for cstore_fdw tables

```
CREATE EXTENSION cstore_fdw;
CREATE SERVER cstore_server FOREIGN DATA WRAPPER cstore_fdw;
CREATE FOREIGN TABLE                                        
test_cstore (x int, y int) SERVER cstore_server
OPTIONS(compression 'pglz');
SELECT  create_distributed_table('test_cstore', 'x');
INSERT INTO test_cstore SELECT s, s FROM generate_series(1, 1000000) s;

SELECT citus_table_size('test_cstore');
 citus_table_size 
------------------
                0
(1 row)
```

Workaround:
```
SELECT sum(result::bigint) FROM run_command_on_placements('test_cstore', $$SELECT cstore_table_size('%s')$$);
   sum   
---------
 8260100
(1 row)
```

**Comment by mtuncer** [comment]
cstore_fdv v2.+ would support pg_table_size() which would resolve this as well.

However, before that happens, suggested workaround it the only way unless we send cstore_table_size instead of pg_table_size to workers when we see that the table is a cstore table. 

We already do similar things in create/drop table commands specific to cstore tables.

**Comment by pykello** [comment]
I wonder why haven't we used PL/SQL or PL/pgSQL instead of C to implement `cstore_table_size()` for regular distributed tables using a similar query that Marco suggested?

**Comment by mtuncer** [comment]
Offending code is here
https://github.com/citusdata/citus/blob/master/src/backend/distributed/master/master_metadata_utility.c#L111

We could check the relation id to see if it is a cstore table and send ```cstore_table_size()``` instead of ```pg_table_size()``` to relation shards.

We are already doing exact same thing in function ```WorkerShardStats()```, see https://github.com/citusdata/citus/blob/master/src/backend/distributed/master/master_stage_protocol.c#L750

**Comment by marcocitus** [comment]
> I wonder why haven't we used PL/SQL or PL/pgSQL instead of C to implement cstore_table_size() for regular distributed tables using a similar query that Marco suggested?

PL/pgSQL functions are a pain to maintain because we need to redefine them every time we want to make a change (e.g. there are 5 different implementations of `citus_drop_trigger` in the Citus codebase), they're difficult to change in a patch release because we'd have to deal with multiple upgrade paths, they tend to make rebasing considerably more painful, and we don't have a way of playing nicely with  Citus' connection API and locking infrastructure in PL/pgSQL.
