### ISSUE TITLE
Random crash in distributed deadlock detection

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1563]
While running regression tests, I randomly ran into the following assert failure:
```
TRAP: FailedAssertion("!(list_length(deadlockPath) > 1)", File: "transaction/distributed_deadlock_detection.c", Line: 139)
LOG:  worker process: Citus Maintenance Daemon: 16384/10 (PID 21214) was terminated by signal 6: Aborted
LOG:  terminating any other active server processes
WARNING:  terminating connection because of crash of another server process
```

**Comment by onderkalaci** [comment]
> While running regression tests

is that the isolation test?

**Comment by marcocitus** [comment]
No, just one of the regular regression tests. Didn't write down which one unfortunately.

**Comment by onderkalaci** [comment]
Now that I'm curious whether a self-deadlock could fail the assertion `(list_length(deadlockPath) > 1)`. I'll check in detail

**Comment by onderkalaci** [comment]
Is the test `check-full` or `check-multi`, do you remember that?

**Comment by marcocitus** [comment]
`check-multi`

**Comment by onderkalaci** [comment]
Well, when I run `check-multi`, the log prints (recurring)
```
LOG:  starting maintenance daemon on database 18237 user 10
CONTEXT:  Citus maintenance daemon for database 18237 user 10
FATAL:  database 18237 does not exist
CONTEXT:  Citus maintenance daemon for database 18237 user 10
LOG:  worker process: Citus Maintenance Daemon: 18237/10 (PID 26710) exited with exit code 1
```

How did you manage to run the daemon with `check-multi` ?

**Comment by onderkalaci** [comment]
(Btw, that seems another bug as well)

**Comment by marcocitus** [comment]
We start a maintenance daemon for every database in which the extension is created. In my `postmaster.log` I see one for database `16384` which keeps running for a while, and one for database `18237`, which keeps giving that error.

**Comment by onderkalaci** [comment]
(I've been running the regression tests for hours on both my local machine and an amazon instance, no lock -- the tests always succeeds.)


Reading the code in detail, at the moment I see two potential ways of getting into that assertion failure.

* A self-deadlock: Which seems quite unlikely since if such thing exists in our regression tests, we'd already have found hanging tests at some point.

* Uninitialized memory: We don't initialize the backend data per backend, which may lead to some unexpected behaviors. In this case, the patch would look like: https://github.com/citusdata/citus/compare/fix_random_crash?expand=1. In any case, it'd be nice to check-in the above PR?  (The bug might be happening while we get the wait graph from the remote nodes such that at this [line](https://github.com/citusdata/citus/blob/45957e568896cf2f963b13e4fc82e2914efc85cf/src/backend/distributed/transaction/lock_graph.c#L440) we accidentally add a wait edge on the worker)

I'm also considering that hitting this [line](https://github.com/citusdata/citus/blob/45957e568896cf2f963b13e4fc82e2914efc85cf/src/backend/distributed/utils/maintenanced.c#L213) in some cases may lead to the crash. I'm trying to understand that as well.

**Comment by onderkalaci** [comment]
I think #1595 fixes this issue. 

I suspect that one of the worker nodes found a deadlock on itself, caused by a multi-shard modification, which saw only a single distributed deadlock.

Now that we're disabling the deadlock checks on the workers, we shouldn't hit that. We've already foreseen this for MX and added `transactionOriginator` flag.

@marcocitus Any thoughts on closing the issue?

**Comment by marcocitus** [comment]
Thanks for the rigorous testing. I think we can close this particular issue given that it specifically relates to the Assert and @metdos opened other issues for valgrind.
