### ISSUE TITLE
 INSERT INTO … RETURNING ... results in error for multi-row inserts.

### ISSUE THREAD

**Issue by pykello** [citusdata/citus#1596]
Following succeeds:

```sql
INSERT INTO researchers
 VALUES
 (2, 1, 'Knuth Donald')
 RETURNING id;
```

But following generates error:

```sql
INSERT INTO researchers
 VALUES
 (2, 1, 'Knuth Donald'),
 (10, 6, 'Lamport Leslie')
 RETURNING id;

ERROR:  missing FROM-clause entry for table "researchers"
CONTEXT:  while executing command on localhost:9702
```

```researchers``` is created in the same way as in multi_modifying_xacts.sql.

**Comment by marcocitus** [comment]
I was kind of wondering why this worked for me before, and in fact I gave a demo that include multi-row INSERT with RETURNING yesterday. 

Turns out it does work for upserts because we set `citus_table_alias` under the covers:
`INSERT INTO test VALUES (6,2), (5,2) ON CONFLICT (x) DO NOTHING RETURNING *;`

deparsed query:
`INSERT INTO public.test_102124 AS citus_table_alias (x, y) VALUES (6,2) ON CONFLICT(x) DO NOTHING RETURNING citus_table_alias.x, citus_table_alias.y`
