### ISSUE TITLE
Replicate reference tables to coordinator

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1615]
For applications that require joins with local postgres tables it would be useful if reference tables could (optionally) have an additional shard placement on the coordinator. In that case the replica on the coordinator can be directly joined with the local table. 

To hide the shard ID, we could additionally create a view (e.g. `CREATE VIEW reftable_view AS SELECT * FROM reftable_102008`). A more advanced alternative is rewrite queries that only contain reference tables that have a local replica and local tables to use the local shard placements instead.

**Comment by samay-sharma** [comment]
Another user had requested this, copy pasting context (After modifying it a bit to obfuscate)

"The idea is that for display purposes, our smaller tables will need to be joined against the large tables, so they would need to be distributed. However, during ingestion, the rows need to be classified against the smaller tables prior to inserting them. This process requires queries against just the smaller tables to get the correct ids to add to the distributed record when it is eventually inserted.  So, making them local to the coordinator makes those inventory queries much faster."

**Comment by lfittl** [comment]
+1 for this, it has come up a few times in my conversations as well.

**Comment by ozgune** [comment]
I'm noting #364 as a semi-related related issue.

@samay-sharma and @lfittl -- I have a clarification question on requirements. Is the customer request here to replicate the reference table on the coordinator node - so that they can reduce the look up time on reference table's row (by avoiding an additional network hop)?

**Comment by lfittl** [comment]
@ozgune Yes, thats how I've seen this usually come up - for very frequent fast queries that go to reference tables (e.g. lookup a given `user_id` in my `users` table so I can get the `organization_id` which is my partition key) the cost of the network hop is noticeable.

**Comment by cyxgun** [comment]
+1 for this one!
Need to join both against many smaller tables on the coordinator (with complicated schema and FK relationships) and against the large, sharded tables.

**Comment by cmelville42** [comment]
We would definitely benefit from this.

**Comment by medington** [comment]
👍

**Comment by pykello** [comment]
Initial API proposal:
1. Introduce `pg_dist_cluster_metadata` catalog table with single `jsonb` column, which similar to `pg_dist_node_metadata` (which contains node specific metadata) contains exactly one row, but unlike it is synced across the cluster. This will be used to store coordinator hostname and port number. We need this because we can do DML from metadata workers, and if a reference table has a replica on the coordinator it should be kept consistent with other nodes.
2. Introduce the `set_coordinator(hostname, port)` UDF, which updates the coordinator address in `pg_dist_cluster_metadata` and syncs it across the cluster. This can only be called from the coordinator.
3. Introduce the `replicate_reference_table_to_coordinator(relation)` UDF, which replicates the given reference table to the coordinator. This can only be called from the coordinator. Errors if `set_coordinator()` hasn't been called yet.

Additionally, we could also add a GUC to replicate reference tables to the coordinator by default, but this requires `set_coordinator` to be called first, I'm more inclined to not doing this and just allowing selective replication via calls to `replicate_reference_table_to_coordinator`.

@marcocitus any thoughts?

**Comment by marcocitus** [comment]
Fixed by #3155 

To enable, use `SELECT master_add_node('coordinator-hostname', 5432, groupid := 0);`
