### ISSUE TITLE
concurrent alter/drop table and select may cause undetected deadlock in mx workers

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#1779]
I slowed down alter table command using an event trigger on an mx worker prior to running this test.

- coordinator issues alter table add column command, waits for worker operation to complete
- another connection to coordinator issues drop table command, gets blocked by alter table command
- a worker connection issues select command on the table being dropped, gets blocked.

- alter table command completes after a while, drop and select commands keep blocking each other

- dump_global_wait_edges() shows that node (0) blocked by on node(2) (who issued select) 
- dump_local_wait_edges() on node(2) shows node(0) blocked on node(2).

- killing select query unblocks drop command

**Comment by mtuncer** [comment]
I used following to slow down alter table command

```sql
create or replace function create_event() returns event_trigger  language plpgsql as $$
begin
 if (TG_TAG = 'ALTER TABLE'::text) THEN
   raise notice 'sleep a bit';
   perform pg_sleep(30);
 END IF;
 return; 
 end; 
$$;



create event trigger create_event on ddl_command_start execute procedure create_event();
```

**Comment by onderkalaci** [comment]
To add my notes:

* A DDL from the coordinator starts a distributed transaction with distributed transaction id and open connections to the placements
* A concurrent multi-shard SELECT from the worker opens connections to the placements
* Since there is no ordering among the accesses, they might end up with a distributed deadlock. That is not surprising.
* Distributed deadlock detection cannot detect this because the multi-shard SELECT queries don't have a distributed transaction id. It only sees that one distributed transaction (i.e., `DDL`) is waiting on something.

This seems to be a missing piece in distributed deadlock detection. 

One another note is that we already allow this in MX, before the deadlock detection.

(I cannot think of any other scenarios like this.)

**Comment by marcocitus** [comment]
I think the problem is that the DROP TABLE (`citus_drop_trigger`) drops/locks the shards before it drops/locks the distributed tables on the workers. It should probably be the other way around.
