### ISSUE TITLE
Feature regression on subquery pushdowns with reference tables from Citus 7 to 7.1

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#1815]
@saicitus just reported that three queries that used to work in Citus 7, but that #no longer do on Citus 7.1. All queries are related to subquery pushdowns in reference tables in Citus.

@saicitus will share more details in the upcoming days.

<pre>
SELECT
    DBE.id,
    DBE.event,
    DBE.userid,
    EXTRACT(EPOCH FROM FSE.timestamp) AS my_time,
    DBE.pointid,
    NULL AS info

FROM database_event AS DBE

INNER JOIN (
    SELECT DISTINCT test.id
    FROM testpoint AS test
    WHERE test.unique_id IN ('00cfdd')
) AS TEST_NAMES ON TEST_NAMES.id = DBE.pointid

ORDER BY DBE.my_time DESC
LIMIT 20
OFFSET 0;
</pre>

The `database_event` table is distributed on `pointid`. The `testpoint` table is a reference table.

In Citus 7, this query executes nicely. In Citus 7.1, we see the following error message:

<pre>
psql:q_distinct.sql:31: ERROR:  cannot push down this subquery
DETAIL:  Distinct on columns without partition column is currently unsupported
</pre>

Removing the `DISTINCT` clause also doesn't help. We then get this error message in Citus 7.1

<pre>
psql:q.sql:31: ERROR:  cannot push down this subquery
DETAIL:  Group by list without partition column is currently unsupported
</pre>

**Comment by mtuncer** [comment]
not a solution but  as a workaround, could you re-write query to be

```sql
SELECT DISTINCT
    DBE.id,
    DBE.event,
    DBE.userid,
    EXTRACT(EPOCH FROM FSE.timestamp) AS my_time,
    DBE.pointid,
    NULL AS info

FROM database_event AS DBE

INNER JOIN (
    SELECT test.id
    FROM testpoint AS test
    WHERE test.unique_id IN ('00cfdd')
) AS TEST_NAMES ON TEST_NAMES.id = DBE.pointid

ORDER BY DBE.my_time DESC
LIMIT 20
OFFSET 0;
```

notice that distinct is moved from the second query to the first one

**Comment by onderkalaci** [comment]
> @saicitus just reported that three queries that used to work in Citus 7, but that #no longer do on Citus 7.1. All queries are related to subquery pushdowns in reference tables in Citus.

That's bad, sorry for the inconvenience :/  

I already opened a PR for fixing the issue: #1816. @saicitus Could you make sure that it fixes the problems you've observed?


The only limitation in the PR is that if a subquery contains only reference tables, the `GROUP BY` or `DISTINCT` clause could only be columns (i.e., arbitrary expressions are not allowed). See the example below:

```SQL
SELECT 
  distinct_users, event_type, time
FROM
(SELECT user_id, time, event_type FROM events_table) as events_dist INNER JOIN
(SELECT DISTINCT user_id as distinct_users FROM users_reference_table) users_ref ON (events_dist.user_id = users_ref.distinct_users)
ORDER BY time DESC
LIMIT 5
OFFSET 0;
```

The above is supported since DISTINCT in the subquery is on a column (i.e., `user_id`). However, the following is not supported where `DISTINCT` is an expression (i.e.,  `2 * user_id `):
```SQL
SELECT 
  distinct_users, event_type, time
FROM
(SELECT user_id, time, event_type FROM events_table) as events_dist INNER JOIN
(SELECT DISTINCT 2 * user_id as distinct_users FROM users_reference_table) users_ref ON (events_dist.user_id = users_ref.distinct_users)
ORDER BY time DESC
LIMIT 5
OFFSET 0;
```

That's a trade-off for a simpler implementation. It seems like an acceptable limitation to me. @saicitus does that make sense to you as well?

**Comment by saicitus** [comment]
Yes I think the above limitation makes sense to me @onderkalaci
