### ISSUE TITLE
Investigate supporting hash distribution and time partitioning use-case

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#183]
(updated the issue) A common question that receive from users is whether they could _shard_ their tables on hash, and then use table inheritance on each shard to further _partition_ the shard by time.

This way, they can expire old data quickly by dropping old partitions. They can also optionally convert old partitions into cstore tables to benefit from 3-4x compression.

In this issue, we intent to further investigate (in user emails, SO, etc.) this use-case and its requirements.

**Comment by ozgune** [comment]
I'm copy and pasting an example scenario to reproduce this issue.

<pre>
create table test_base3( col_b int );   
create table test_derived3 (col_d int) inherits(test_base3);

select * from master_create_distributed_table('test_base3', 'col_b', 'hash');
select master_create_worker_shards('test_base3', 16, 2);

select * from master_create_distributed_table('test_derived3', 'col_b', 'hash');
select master_create_worker_shards('test_derived3', 16, 2);
all seems to work ok but then

select * from test_derived3;

WARNING:  could not receive query results from 192.168.50.11:9701
DETAIL:  Client error: column "col_b" does not exist
ERROR:  failed to execute job 6
DETAIL:  Failure due to failed task 14
</pre>

**Comment by mrjgreen** [comment]
Its a shame this doesn't work - it would allow for hash distribution of tables by something like customer ID for fast colocated joins, with the inheritance providing a mechanism for removing cold data after a given time period.

Would it ever be feasible to support inheritance on distributed tables?

**Comment by ozgune** [comment]
@mrjgreen -- thanks for your input.

We might have a workaround to make this work. We're also evaluating whether we should show "hash distribution of tables on customer_id with time partitioned tables" as part of a reference application. That said, we'd ideally fix the issue itself.

If you have a use-case in mind, could you elaborate on it a bit more? What type of data (user, time-series, events, etc.) did you have in mind? What type of queries were you planning to run on them?

**Comment by mrjgreen** [comment]
Thanks for the reply! A workaround would be great, and a reference application would be fantastic.

The use-case is indeed time series events, split by something like "customer_id", where almost all queries are constrained to a single customer. These queries often include complex joins across multiple fact tables and dimension tables (e.g how many events of type A, where there were > 10 related events of type B within the last 6 months, with a geographic location near place X etc...). It seems from my initial tests of citusDB, that a hash distribution on "customer_id" with the real-time executor is the most performant way to do this kind of query.

The challenge though is that due to the volumes of data, it is necessary to be able to remove "cold" data after a period of time. Without being able to "de-inherit" or drop a partition from a hash distributed table, a routine would need to iterate through each shard and execute a very expensive delete. 

Hopefully that adds some clarity to the problem I am hoping this fix could solve, but I'd be happy to hear alternative ways of achieving a similar result if I'm looking at this in the wrong way!

**Comment by ozgune** [comment]
@mrjgreen -- thanks for the quick reply. I'll update this comment with more info in the following days.

I'm also adding the following Stack Overflow question to compile questions of similar type within this issue: http://stackoverflow.com/questions/35645347/is-table-partitioning-being-supported-in-citusdb

**Comment by ozgune** [comment]
I'm noting use of pg_partman here for documentation purposes: https://github.com/citusdata/pg_shard/issues/151

**Comment by ozgune** [comment]
I wanted to drop a quick update in this thread with a high level approach of enabling hash distribution + time partitioning. (We're also looking to codify and document this approach in #573.)

The basic question we're looking to answer is "I'd like to shard my data on one column, and then use Postgres to partition the shard on time".

1. Create table on the master node, distribute by hash, and create distributed table's shards
2. Go to worker nodes, and change shards' table definitions to inherited tables through a script
3. For each shard (inherited table), have a _current_ inherited table and route Insert/Updates into the _current_ table
4. After a certain time period (24 hours), run a command to convert the _current_ partition into a _historical_ partition

**Comment by koeninger** [comment]
Is there a reason not to make a new distributed table for every time period and use a UNION ALL view for the time partitioning?  Especially if you have only a few recent tables?  

Seems like that would allow things like master_copy_shard_placement to continue working unmodified, and even possibly allow for increasing partition count over time.

Or would that not play well with the distributed changes to the query planner?

**Comment by ozgune** [comment]
@koeninger -- yes, this approach could also work depending on your use-case. I can think of three points to consider:

1. (as you noted) How many distributed tables are you going to end up with? If you're going to create a new table for each minute's worth of data, you'll end up with too many tables. As a result, query performance will degrade.
2. Citus doesn't yet support ``UNION ALL``. For now, our customers use ``CREATE TEMP TABLE ... AS`` to pull query results to the coordinator node and then merge the results there. This is one of the candidate features for v6.2 and we're tracking it in #359.
3. With hash distribution, you can more easily roll-up data. That is, let's say that you shard your data on device_id and then you wanted to capture hourly aggregate stats for devices. You could then create an hourly aggregate table sharded on device_id. Citus will [colocate these tables](https://docs.citusdata.com/en/v6.0/tech_soln/real_time_dashboards.html) and you could then call ``INSERT INTO ... SELECT`` to roll up from the source table into the aggregate one.

**Comment by ozgune** [comment]
This issue recently came up in a conversation in our [Slack channel](https://citus-public.slack.com/archives/general/p1478889921001755). I wanted to make a note of it here.

**Comment by krburkhart** [comment]
Ozgune pointed me here from this citus-users thread: https://groups.google.com/d/topic/citus-users/9uAwdZrQnxw/discussion

We would love to be able to create a distributed cstore table by append on a timestamp column AND by hash on a secondary column.

We are storing stock quotes.  Each row contains a timestamp, a ticker symbol and a bunch of other stuff.  Each day there are several hundred million rows.  We would like to keep the most recent N days (or weeks etc.) of data which obviously requires us to delete old data as we acquire new data.  An ideal solution for us would be to distribute by append on timestamp and have each "shard" be further distributed by hash on the ticker symbol.

This would allow:

- Automatic shard creation based on newly inserted data.  Number of append shards grows dynamically, hash (sub?)-shards could be fixed number based on config.
- Delete old rows by deleting old shards via master_apply_delete_command.  The limitation of only being able to completely delete a shard is OK.
- Avoid the complication of creating postgres partitions (which doesn't currently work with cstore anyway).
- Avoid the overhead and the query complexity of using union on daily tables.

**Comment by ozgune** [comment]
@krburkhart -- Thank you for your comment. I had a quick clarification question.

Our current plan is to enable hash distribution on one column and then further partition this data on a secondary column (timestamp). Would this setup help with your use case?

**Comment by metdos** [comment]
Some notes from an existing customer on the slack channel:

In short, you want something where, either during `create_distributed_table()` or after, you can specify:

1. The column name to use for partitioning on time
2. The size of each partition, as a time interval
3. The maximum number of partitions to keep (or 0 for all of them).

You also would want tooling so that you can change the number of partitions later, or drop partitions older than some time, not unilke the existing tooling you guys have (and that we use) for dropping old append-distribution shards.

**Comment by krburkhart** [comment]
Ozgun,

Sorry for missing this earlier.  This setup helps as long as I can delete
all partitions containing data not newer than a specific date (thereby
purging old records).

Our most common queries will qualify on symbol (or a list of symbols)
within a time range.

-K

**Comment by ozgune** [comment]
@mrjgreen, @koeninger, and @krburkhart -- I wanted to provide a quick update on this issue. We decided to prioritize this feature for Citus 7.0; and we're tracking its requirements and implementation in #573.

**Comment by krburkhart** [comment]
Thank you, that's great news.  Do you have a guess as to when Citus 7 will
happen?  (this summer?  this year?  unknowable future time?)

-K

**Comment by marcocitus** [comment]
As of Citus 7.2, pg_partman works on distributed tables with native PG10 partitioning.

**Comment by ozgune** [comment]
@mrjgreen, @koeninger, and @krburkhart -- I wanted to add a quick note to Marco's comment.

Citus 7 supports declarative partitioning that comes with PostgreSQL 10. This way, you can hash distribute your tables on one dimension and further partition them on time.

Citus 7.2 makes further improvements to support pg_partman. pg_partman automatically manages Postgres partitions for users (by creating new partitions and dropping old ones). You can read more about Citus and pg_partman here: https://www.citusdata.com/blog/2018/01/24/citus-and-pg-partman-creating-a-scalable-time-series-database-on-PostgreSQL/
