### ISSUE TITLE
Master plan may cause out of memory issues due to HashAggregate

### ISSUE THREAD

**Issue by byucesoy** [citusdata/citus#1932]
For real-time queries, **Postgres predicts that Custom Scan Node will return 0 rows** and creates its plans according to that. This issue becomes problematic when there is a memory heavy aggregation after custom scan node such as HLL union.

Each HLL intermediate data structure uses about 130KB of memory.  Since PostgreSQL thinks Custom Scan Node will return 0 rows, it prefers to use HashAgg. However, if the query returns ~1.5 million HLL objects, HashAgg requires about 200GB of memory.

A solution could be giving Postgres more realistic estimates about number of rows returning from Custom Scan Node, I am not sure if it is not easy thing to do.

```sql
EXPLAIN SELECT hll_cardinality(SUM(column1))::int FROM table_name GROUP BY column2;
                                     QUERY PLAN                                                                         
-------------------------------------------------------------------------------------------------
 HashAggregate  (cost=0.00..0.00 rows=0 width=0)
   Group Key: remote_scan.worker_column_2
   ->  Custom Scan (Citus Real-Time)  (cost=0.00..0.00 rows=0 width=0)
         Task Count: 64
         Tasks Shown: One of 64
         ->  Task
               Node: host=ec2-13-126-13-116.ap-south-1.compute.amazonaws.com port=5432 dbname=citus
               ->  GroupAggregate  (cost=5050.08..5050.18 rows=8 width=40)
                     Group Key: column2
                     ->  Seq Scan on table_name_102000 table_name  (cost=0.00..4364.72 rows=137072 width=25)
(10 rows)

```

**Comment by mtuncer** [comment]
We prepare the plan for postgres in ```multi_master_planner.c``` see function  ```BuildSelectStatement()``` and  ```BuildAggregatePlan()```

We literally hard code the plan type there.  Perhaps we should add a check to see if there is hll aggregate and force aggregation strategy to ```AGG_SORTED``` . We used this one to plan ```select count(distinct)``` queries.

**Comment by samay-sharma** [comment]
I saw a similar issue with another customer. They have a query like below where neither a nor b are the partition column and they have 250M rows in the table.

```
Select a, b, sum(c), count(*) from table group by a,b having count(*) > 1
```

Citus exhausts all the memory on the coordinator node irrespective of what work_mem we set.

**Comment by byucesoy** [comment]
@mtuncer that is one possible solution but that would cause;
- not using hash aggregation even if it can fit in memory (performance penalty)
- would not fix this problem for other possible costly aggregates (like topn)

Would it be possible to give somewhat more realistic estimation? I know we do not keep statistics, so I am not sure how we can do this.

**Comment by ozgune** [comment]
@byucesoy / @onderkalaci -- We had two recent engagements where we observed this issue. I had two questions on timeline estimates:

* If we wanted to offer a quick fix (say by having a config setting to force `AGG_SORTED` on the coordinator), how long would the fix take?
* How long would the proper fix for this issue take?

**Comment by byucesoy** [comment]
* quick fix with a GUC variable would take 2-3 days.
* About proper fix, we first need to decide on what is proper fix :smile:. If it is collecting statistics and using `AGG_SORTED` depending on it, that would take much much longer (2-3 weeks would be my first guess). More importantly do we want to start collecting shard statistics? I think it would be overkill to collect statistics for just fixing this. But eventually having that info available would be handy for other features as well, I guess.

**Comment by sumedhpathak** [comment]
Look at this with Marco, we also realized a bug here:
https://github.com/citusdata/citus/blob/master/src/backend/distributed/planner/multi_master_planner.c#L292. That shouldn't call grouping_is_hashable.

**Comment by ozgune** [comment]
@onderkalaci / @byucesoy -- I have two questions.

> Another possible proper fix can be re-planning coordinator part of the plan after getting the data from worker nodes. I think that would be easier.

How long do you think this type of proper fix would take?

We ran into this issue again in a separate customer conversation. Could we prioritize a fix for this that would take 2-3 days?

**Comment by onderkalaci** [comment]
@ozgune We've chatted with @byucesoy and below are our notes:

> Another possible proper fix can be re-planning coordinator part of the plan after getting the data from worker nodes. I think that would be easier.

I don't think changing the plan during the execution is something viable. So, I'm skipping that option at all.

> If we wanted to offer a quick fix (say by having a config setting to force AGG_SORTED on the coordinator), how long would the fix take?

That should take 2-3 days including review + testing. However, I'd like to note that asking users to pick the query plan seems a very poor user experience. I don't think there are any databases that do this? I'd only go that way unless its a very urgent/critical user request.

A slightly more complicated GUC scenario that avoids asking the plan from the user would be to ask the `expected aggregate result row count` from the user. Later, we'd mimic what Postgres does such as [here](https://github.com/postgres/postgres/blob/2f178441044be430f6b4d626e4dae68a9a6f6cec/src/backend/optimizer/plan/planner.c#L3895).

In the end, this would be the same as asking the plan type and maybe a worse user experience, but, at least avoids asking the plan type from the user. Note that I'd expect this to take 4-5 days since we'd need to use something like [AggClauseCosts](https://doxygen.postgresql.org/structAggClauseCosts.html) or something like that. Even though it has many drawbacks, I'd slightly prefer it to avoid asking the plan type directly from the user. It'd be nice to hear other thoughts on this. 

Another alternative we've discussed, which seems a better way for the longer term, is to keep some statistics about the shard placements (i.e., fetch the table statistics that Postgres keeps on the workers) and potentially aggregate that statistic for distributed tables. Later, use that information for our planning purposes (again relying on Postgres functions to evaluate the statistics). This is a good example where such statistics could help. We could probably benefit from such statistics in other places in the optimizer as well.  However, that seems like a huge task requires more thinking for sure. 
(We could use maintenance daemon for fetching the stats).

**Comment by marcocitus** [comment]
Shouldn't we at minimum honour the enable_hashagg GUC? It's weird that we're still doing a hash aggregate even if it's disabled.

**Comment by onderkalaci** [comment]
> Shouldn't we at minimum honour the enable_hashagg GUC? It's weird that we're still doing a hash aggregate even if it's disabled.

Yes, that makes sense and avoids adding a new GUC. 

@ozgune / @samay-sharma would that help to solve your problems?

**Comment by saicitus** [comment]
@ozgune 2 customers ran into this again.
Can we mark this as high priority.

**Comment by metdos** [comment]
@saicitus, @ozgune are okay with the approach Maroc suggested, honoring the enable_hashagg GUC. The user will need to set enable_hashagg to false for this type of queries.

If yes, we can prioritize and implement this. Most likely, we can also backport it.

**Comment by ozgune** [comment]
> @saicitus, @ozgune are you okay with the approach Marco suggested, honoring the enable_hashagg GUC.

@saicitus, what's your take on this approach?

I can see one drawback with this approach, but I'm not sure about its implications. Citus users would disable this setting on the coordinator to resolve an obvious OOM issue. If they also have regular Postgres tables on the coordinator node, disabling hash aggregates for the OOM issue could also impact unrelated queries.

That said, we need to have a workaround on this issue asap (let's prioritize it immediately), and I don't have strong preferences. @saicitus -- Does the proposed workaround sound good to you?

**Comment by marcocitus** [comment]
I guess one other issue is that we wouldn't be able to build on Windows if we used `enable_hashagg` because it's not marked as PGDLLIMPORT.

**Comment by saicitus** [comment]
@ozgune I think Im okay with this work around of honoring "enable_hashagg" to decide the plan on the coordinator. I think it is a session level setting i.e it can be set per query. So this makes it better usable. The customers would set it to **off** only for those queries which pull a lot (for ex. say > million). I'd assume that by default we'd have this setting **on**, hence the queries on coordinator tables shouldn't get affected right?

**Comment by byucesoy** [comment]
We had another instance of this bug in one of our Cloud customers.

**Comment by onderkalaci** [comment]
> We had another instance of this bug in one of our Cloud customers. We used enable_hasagg workaround as we decided here, but it would be nice if we fix this issue eventually.

As far as I can see, this will completely be fixed with PG 13 as hash agg honors `work_mem`
