### ISSUE TITLE
task_assignment_policy not working well when target at a specific shard

### ISSUE THREAD

**Issue by jilongs** [citusdata/citus#2081]
The issues is that when I run a query only targeted at a single shard, no matter which policy I choose, it always hit the first worker node. Which is not balanced at all.

**Comment by samay-sharma** [comment]
This came up again for another customer.

**Comment by jilongs** [comment]
@samay-sharma Thanks for the update. Can you please shed more light on the meaning of this setting? Will it have any other side effects?

**Comment by linwalth** [comment]
Same for me, when I run 2 nodes with only reference tables traffic only ever hits the first node, no matter which setting I use. Even turning off router execution does not help. Is there anything specific I can do to work around this?

**Comment by linwalth** [comment]
@samay-sharma Is there a workaround for this in Citus 7.5? Round Robin and Greedy Settings did not work, neither with nor without router execution turned off.

My Setup was 1 Coordinator and 3 Data nodes, and the whole database was simply set up as reference tables. The tables did distribute to all 3 nodes, but only one node ever got hit by master traffic.

I also tried to distribute a sharded table to the three nodes, just to see if something would change, but since my query was based on the reference table it again only hit one node.

This one node was always the same node, except for when I shut it down, then another node stepped up. Still, the coordinator sent me connection errors, as it tried to connect to the then shut down node that it had been sending traffic to before.

Hopefully this will be helpful in solving the bug. Please keep me posted. :)

**Comment by ozgune** [comment]
@metdos / @sumedhpathak -- Could you provide an update on our progress on this issue?

**Comment by metdos** [comment]
I think this issue is fixed with this PR https://github.com/citusdata/citus/pull/2472. @thanodnl ?

**Comment by thanodnl** [comment]
Yes!

Should have mentioned the fix of this issue on that PR, would have auto closed. Closing now as it is implemented in #2472 .

Now when `citus.task_assignment_policy` is set to `'round-robin'` it will alternate between different shard placements.
