### ISSUE TITLE
"Unrecognized node type" error on rollups

### ISSUE THREAD

**Issue by colton-citus** [citusdata/citus#2217]
Customer has identified a rollup function that reliably throws an "Unrecognized node type" message when attempting to INSERT INTO from a distributed table. 

Client has provided a gist that can automatically reproduce this on 7.3 (client version) and 7.4 (verified to reproduce behavior in my testing). 

https://gist.github.com/tbug/9b8cc6715964569e9dba0f15f690873f

**Comment by onderkalaci** [comment]
I'm still looking into this. But, I'd like to share my initial investigation notes.

The issue seems to be related `PARAM` type nodes in the `SELECT` query and saving the query plan (via a function or prepared statement). We seem to be not properly handling those nodes.

For example, if you create a prepared statement with a `PARAM` node (e.g., Postgres represent subqueries in `WHERE` clause as a param as well), we can reproduce it with simpler steps:

```SQL
PREPARE citus_bug AS 
	INSERT INTO users_table 
	SELECT * FROM users_table 
		where value_1 IN (SELECT value_2 FROM events_table OFFSET 0);
EXECUTE citus_bug;
EXECUTE citus_bug;
EXECUTE citus_bug;
EXECUTE citus_bug;
WARNING:  could not dump unrecognized node type: 2139062143
WARNING:  could not dump unrecognized node type: 2139062143
WARNING:  could not dump unrecognized node type: 2139062143
ERROR:  badly formatted node string "} :jointree {} :targetList {} :o"...
postgres=# 

```

Somehow the jointree of the query becomes `NULL` and plan serialization fails.
