### ISSUE TITLE
Provide a UDF for cleaning up metadata on nodes for MX

### ISSUE THREAD

**Issue by aamederen** [citusdata/citus#2326]
When a user issues `start_metadata_sync_to_node` command, the coordinator sends metadata clearing commands, followed by metadata creating commands to the target node. 

When a user issues `stop_metadata_sync_to_node`, coordinator just marks the node and does nothing else. 

It would be good to have a way to clear the metadata after `stop_metadata_sync_to_node` command. 

This can be done via wrapping the clear steps of `start_metadata_sync_to_node` and expose it via a UDF.

**Comment by onderkalaci** [comment]
One idea that came-up with @marcocitus is to add a `clear bool DEFAULT false` parameter to the `stop_metadata_sync_to_node `. This seems to cause less trouble compared to having another UDF because otherwise we'd need to think about the edges of what happens operation X happens in between these calls etc.
