### ISSUE TITLE
EXPLAIN ANALYZE error while inserting in a distributed or reference table 

### ISSUE THREAD

**Issue by louiseGrandjonc** [citusdata/citus#2347]
I'm working with the dataset of the tutorials and while trying to use `EXPLAIN ANALYZE` in `INSERT` queries I ran into errors.

```
postgres=# SELECT * FROM companies WHERE id=5005;
 id | name | image_url | created_at | updated_at | something_unique | country
----+------+-----------+------------+------------+------------------+---------
(0 rows)

postgres=# EXPLAIN ANALYZE INSERT INTO companies (id, name, created_at, updated_at) VALUES (5005, 'citus', NOW(), NOW());
WARNING:  duplicate key value violates unique constraint "companies_pkey_102024"
DETAIL:  Key (id)=(5005) already exists.
WARNING:  could not commit transaction for shard 102024 on any active node
ERROR:  could not commit transaction on any active node
postgres=# SELECT * FROM companies WHERE id=5005;
  id  | name  | image_url |         created_at         |         updated_at         | something_unique | country
------+-------+-----------+----------------------------+----------------------------+------------------+---------
 5005 | citus |           | 2018-08-22 18:51:10.193422 | 2018-08-22 18:51:10.193422 |                  |
(1 row)
```

In this case the row is still inserted.

I ran into a similar error while inserting in a reference table. Here are the steps to reproduce:

```
CREATE TABLE countries (id serial, name varchar(250), CONSTRAINT countries_pkey PRIMARY KEY (id));

INSERT INTO countries (name) VALUES ('France');

select create_reference_table('countries');
```

Here is the error

``` 
postgres=# EXPLAIN ANALYZE INSERT INTO countries (name) VALUES ('Germany');
WARNING:  duplicate key value violates unique constraint "countries_pkey_102104"
DETAIL:  Key (id)=(3) already exists.
WARNING:  prepared transaction with identifier "citus_0_2762_6_67" does not exist
WARNING:  failed to commit transaction on citus_worker_1:5432
WARNING:  failed to roll back prepared transaction 'citus_0_2762_6_67'
HINT:  Run "COMMIT PREPARED 'citus_0_2762_6_67'" on citus_worker_1:5432
                                               QUERY PLAN
--------------------------------------------------------------------------------------------------------
 Custom Scan (Citus Router)  (cost=0.00..0.00 rows=0 width=0) (actual time=0.914..0.914 rows=0 loops=1)
   Task Count: 1
   Tasks Shown: All
   ->  Task
         Error: Could not get remote plan.
 Planning time: 0.068 ms
 Execution time: 1.029 ms
(7 rows)
```

In this case the row wasn't inserted:

```
postgres=# SELECT * FROM countries;
 id |  name
----+--------
  1 | France
(1 row)
```

In both cases using `EXPLAIN` or no `EXPLAIN` solves the problem.

Here is the result for the distributed table:

```
postgres=#  EXPLAIN INSERT INTO companies (id, name, created_at, updated_at) VALUES (5006, 'citus', NOW(), NOW());
                                QUERY PLAN
---------------------------------------------------------------------------
 Custom Scan (Citus Router)  (cost=0.00..0.00 rows=0 width=0)
   Task Count: 1
   Tasks Shown: All
   ->  Task
         Node: host=citus_worker_1 port=5432 dbname=postgres
         ->  Insert on companies_102030  (cost=0.00..0.01 rows=1 width=96)
               ->  Result  (cost=0.00..0.01 rows=1 width=96)
(7 rows)
```

And for a reference table:

```
postgres=#  EXPLAIN INSERT INTO countries (name) VALUES ('Germany');
                                 QUERY PLAN
----------------------------------------------------------------------------
 Custom Scan (Citus Router)  (cost=0.00..0.00 rows=0 width=0)
   Task Count: 1
   Tasks Shown: All
   ->  Task
         Node: host=citus_worker_1 port=5432 dbname=postgres
         ->  Insert on countries_102104  (cost=0.00..0.01 rows=1 width=520)
               ->  Result  (cost=0.00..0.01 rows=1 width=520)
(7 rows)
```

**Comment by marcocitus** [comment]
Good catch. I think we're neglecting to open a transaction block and/or send a savepoint that we can roll back to, which is how we normally deal with the fact EXPLAIN ANALYZE INSERT first runs the EXPLAIN ANALYZE on a shard placement to get the EXPLAIN output and then also executes the INSERT.

**Comment by sumedhpathak** [comment]
@marcocitus What's your estimate for the fix?

**Comment by onderkalaci** [comment]
I looked into this a bit, and let me share my findings for the future owner of this task.

- When a user does an `EXPLAIN ANALYZE`, in the first phase on `ExplainOnePlan`, Postgres calls `ExecutorStart()/ExecutorRun()/ExecutorEnd()` which calls Citus executor and the query is actually executed via Citus.
- In the second phase (e.g., on the Citus' EXPLAIN hook via custom scans), Citus implemented a workaround via savepoints to skip applying the same command again. See the related [PR](https://github.com/citusdata/citus/pull/1361). Basically, we do the following `Execute the command`, `Create a savepoint`, `Execute the command & get the EXPLAIN ANALYZE output`, `rollback to the savepoint`

- Our logic for `EXPLAIN ANALYZE` actually works expected here as well. The problem here is that even though we create a savepoint, the second execution violates the unique constraint because we're actually running the same command again. In this case, we're violating unique constraints, but we could have violated other constraints as well such as foreign keys.

- It is probably not simple to change the order (e.g., first execute the command with savepoint & rollback, later actually execute it) due to custom scan APIs we're using.
- I've tried some hacks such as disabling/deferring the constraints (e.g., messing `pg_constraint`) right after the savepoint, but for example unique constraints cannot be disabled. I even tried `DELETE FROM pg_constraint` just before the second command execution, which didn't help 😄 
- I've tried exporting the snapshot of just before the first phase and then importing right after savepoint. However, that is not supported by Postgres.

Hopefully we can find a simple solution to this.

**Comment by mtuncer** [comment]
@onderkalaci do we need to execute the query separately at all ? in the end we are forwarding the modify query to workers who do their own processing of explain analyze.  Wonder if we can just block the modify query if we find that it is for explain.

**Comment by marcocitus** [comment]
@mtuncer I think the problem this is that we cannot choose whether we want to execute the query. It has already been executed before we realise an EXPLAIN ANALYZE is going on. In fact, it may already have been committed. 

We may need to use the top-level explain hook.

**Comment by mtuncer** [comment]
I tracked down what happens when explain analyze is run.
We have a possible lead looking at EState->es_instrument. This is always zero except the query is run with explain analyze.  

We could detect that we are running under explain analyze by checking value here in 
 `CitusModifyBeginScan`

When `RouterModifyExecScan` is called, we no longer have access to EState
But CustomScanState.ss.ps.instrument contains the instrumentation object. It is null when running with regular commands. It becomes non-null when run with explain analyze

We should be able detect that we are under explain analyze, and not run this modify queries in workers.

**Comment by mtuncer** [comment]
I modified `multi_router_executor.c::RouterModifyExecScan()` and added 
```c
	if (node->ss.ps.instrument != NULL)
	{
		scanState->finishedRemoteScan = true;
	}
```

To the very top of the function. That prevented the remove execution when run in explain analyze.

However, now due to rollback at the end of explain processing no change is committed to remote node.

I we can drop the rollback, and make sure to forward explain analyze query to all shards we could be okay here.

**Comment by marcocitus** [comment]
Sounds good to me. It does have a slight drawback in no longer reporting the number of rows in case of RETURNING.

**Comment by mtuncer** [comment]
implemented a prototype using explain hook
https://github.com/citusdata/citus/tree/explain_analyze_insert

**Comment by mtuncer** [comment]
During our discussion with @anarazel he mentioned explain hook approach would not work, and create more problems. He suggested running actual explain part before executor run, store results in custom scan node, and return results afterwards.

Will create a prototype for that.

**Comment by colton-citus** [comment]
Any updates or ETA on this?

**Comment by metdos** [comment]
> Any updates or ETA on this?

For the moment, we prioritized this for the next release, 9.0.

**Comment by serprex** [comment]
As an experiment I copied this the first bit of [ExecuteQuery](https://github.com/postgres/postgres/blob/e2e02191e23379502a38a6b0436ab7f41b2efc08/src/backend/commands/explain.c#L154) in order to synthesize an `ExplainState` from an `ExplainStmt` in `commands/utility_hook.c`. `CitusExplainScan` only depends on the distributed plan & explain state. So passing ExplainStmt's query through distributed_planner means I have the two pieces to execute EXPLAIN logic before we enter `standard_ProcessUtility`. My goal at this point was only to `elog(WARNING, es->str->data)` after running through logic. Unfortunately the EXPLAIN logic in CitusExplainScan was somehow causing `EXPLAIN ANALYZE INSERT INTO countries (name) VALUES ('Germany');` to come through as `INSERT INTO countries (id, name) VALUES (NULL, 'Germany');` even when I copyObject the query before planning. Seems like there's potential in this approach, but that's where it's currently at

Alternative would be to try handle paying attention to instrumentation throughout executor logic. This is nice in that it means what ANALYZE reports back will be what actually happened
