### ISSUE TITLE
FIRST() and LAST() aggregates

### ISSUE THREAD

**Issue by seamusabshere** [citusdata/citus#2397]
## What

As far as I understand it [0], citus ⭐️ **hardcodes a whitelist** 🌟  of allowed aggregates - please add 2 more, `FIRST()` and `LAST()`

```
CREATE OR REPLACE FUNCTION public.first_agg ( anyelement, anyelement )
RETURNS anyelement AS $$
        SELECT CASE WHEN $1 IS NULL THEN $2 ELSE $1 END;
$$ LANGUAGE SQL STABLE;

CREATE AGGREGATE public.first (
        sfunc    = public.first_agg,
        basetype = anyelement,
        stype    = anyelement
);

CREATE OR REPLACE FUNCTION public.last_agg ( anyelement, anyelement )
RETURNS anyelement AS $$
        SELECT $2;
$$ LANGUAGE SQL STABLE;

CREATE AGGREGATE public.last (
        sfunc    = public.last_agg,
        basetype = anyelement,
        stype    = anyelement
);
```

(thanks to Mike Rylander [1])

## Why

First of all, because you added pg_cron [2] to Citus Cloud and then listed all the other clouds that _didn't_ provide this incredibly useful system tool, so you have a history of one-upping non-citus situations :)

<img width="356" alt="screen shot 2018-09-20 at 2 33 05 pm" src="https://user-images.githubusercontent.com/15787/45839353-1ffb6500-bce2-11e8-976b-cfbbbcae854b.png">

Second, because the list of approved aggregates is hardcoded, so if you don't do it, nobody can - not even if I apply it to each of my worker nodes manually.

Third, because `FIRST()` is _faster_ and _much_ simpler to use than the alternatives that Tom Lane lists here [3]. Faster because ... it's complicated. Simpler because you don't have to come up with a complex `OVER` to use it.

## Horrible alternatives

Here's one way to implement `LAST(foo)` if you don't have it already: `(jsonb_object_agg('a', foo) ->> 'a')::text`. Gross!

## Footnotes

[0] https://github.com/citusdata/citus/blob/master/src/backend/distributed/planner/multi_logical_optimizer.c#L1702
[1] https://www.postgresql.org/message-id/b918cf3d0603311735v5dde21d4pfcd613c09d80cf57@mail.gmail.com
[2] https://github.com/citusdata/pg_cron
[3] https://www.postgresql.org/message-id/10345.1508510311%40sss.pgh.pa.us

**Comment by seamusabshere** [comment]
@marcocitus is it true that citus hardcodes a whitelist of allowed aggregates?

**Comment by jasonmp85** [comment]
_Hardcodes a whitelist_ is a bit of a simplification. I'd say we "detect certain aggregates and do the right thing for them". It's not just a whitelist; for instance, `AVG` might become a `SUM` and `COUNT` with some division occurring later on on the master. So, sure, there is a list of aggregates that receive this kind of treatment, but it's not quite as straightforward as _the aggregate is on the list, it goes through unmodified_.

We've often looked into using the pieces of a parallel aggregate to auto-support this for aggregates which correctly implement parallel support, but so far the internal transition types have proved a burden (they'd need to be de/ser'd across node/coordinator boundaries).

**Comment by anarazel** [comment]
On 2018-10-15 21:53:38 +0000, Jason Petersen wrote:
> We've often looked into using the pieces of a parallel aggregate to auto-support this for aggregates which correctly implement parallel support, but so far the internal transition types have proved a burden (they'd need to be de/ser'd across node/coordinator boundaries).

There's aggserialfn/aggdeserialfn, so that shouldn't be much of a
problem.

**Comment by jasonmp85** [comment]
> There's aggserialfn/aggdeserialfn, so that shouldn't be much of a problem.

Are they _required_/guaranteed to be lossless? Admittedly I haven't personally looked into this recently…

**Comment by anarazel** [comment]
On 2018-10-15 15:01:47 -0700, Jason Petersen wrote:
> > There's aggserialfn/aggdeserialfn, so that shouldn't be much of a problem.
> 
> Are they _required_/guaranteed to be lossless? Admittedly I haven't personally looked into this recently…

What do you mean? Whether they actually work? How'd a non-lossless
version be useful? Postgres uses these for parallel aggregates (mainly
for INTERNAL types), so they better work...

- Andres

**Comment by seamusabshere** [comment]
@jasonmp85 ok so this issue is invalid?

**Comment by marcocitus** [comment]
I think the issue is fine. These aggregates seem useful. There is a question of whether Citus should be adding SQL functionality that is not supported in PostgreSQL itself, but we could see it as a temporary workaround until Citus distributes the full window function syntax. There is probably a question around what defines the ordering for `first` and `last`. They are not deterministic. 

We could also consider adding "first" and "last" to the list of aggregates that get treated like "sum", without including their definitions in Citus as we do with HLL aggregates if that helps your use case.

**Comment by seamusabshere** [comment]
@marcocitus 

> We could also consider adding "first" and "last" to the list of aggregates that get treated like "sum", without including their definitions in Citus as we do with HLL aggregates if that helps your use case.

⬆️ this would be great

i included ![this image](https://user-images.githubusercontent.com/15787/45839353-1ffb6500-bce2-11e8-976b-cfbbbcae854b.png) because i know you guys like to have features that other clouds have, but i admit it could be pretty esoteric :)

**Comment by serprex** [comment]
This falls under #120

**Comment by serprex** [comment]
https://github.com/citusdata/citus_docs/issues/894

This is mostly resolved. It'd be nice if `FIRST(x ORDER BY y)` pushed down to worker so that we only pull up an (x, y) pair which could then have `FIRST(x ORDER BY y)` pick the correct choice on master, but that's pretty involved. If someone really wants Citus to implement a fast `FIRST` for them they can implement specialized versions with COMBINEFUNC that has a non-pseudotype to hit #2921. Hopefully we can make this better in the future for aggregates with multiple arguments so that you could create a specialized function which takes the order by as a second parameter & achieve the idealized (item, rank) intermediate state for parallel execution
