### ISSUE TITLE
Updates using recursive planning (with CTEs) error out when run in multiple threads

### ISSUE THREAD

**Issue by saicitus** [citusdata/citus#2418]
When Updates with CTEs are run in parallel using multiple threads, the below error is seen. 3 customers have run into it. I am in the process of reproducing this, will update if I am able to repro it.

```
"pq: could not open file \"base/pgsql_job_cache/16384_4_1050909/3_1.data\": No such file or directory"
```

**Comment by marcocitus** [comment]
do you happen to know the (type of) statement on the worker which caused this error? In particular, was it an UPDATE or a COMMIT?

**Comment by onderkalaci** [comment]
Hey @saicitus are there any more details that you could share?

This seems like an MX cluster since the `nodeId` = `4` in the error message. 

For example, are the queries are long-running? Or, as marco noted above, do we see the errors on the `UPDATE` or `COMMIT` etc? Lastly, do you know how many concurrent queries are running, is it only 2 or a lot more?

**Comment by saicitus** [comment]
hey @onderkalaci, im sorry for the late reply. Missed the message.
So yeah the cluster which I pasted the above report from is an MX cluster. But this appeared even in a non-MX cluster on other customer deployment.

No the queries were not long running. Probably <1second. I'm not 100% sure whether we see it on UPDATE or commit. Will check and get back. The scenario when a customer saw the issue had 5 threads running in parallel.

**Comment by ChenHuajun** [comment]
The Citus7.4.1 we used encountered the same error message in the production environment. 
```
 ERROR:  could not open file "base/pgsql_job_cache/16405_18_22177818/190961_1.data": No such file or directory
```
Our environment deployed pgbouncer between the coordinator and the worker, and pool_mode was set to transaction.
I suspect that the value of the CreatedResultsDirectory variable was not cleaned up correctly when pgbouncer reused the connection, because of bug #2420.  However, this problem could not be reproduced in the test environment.
Do you also use pgbouncer ? @saicitus

**Comment by saicitus** [comment]
@onderkalaci @marcocitus any thoughts on this issue? We have close to 4 resources before we last saw this. Should the latest versions of citus, fix this issue?
