### ISSUE TITLE
citus_lock_waits does not show waiting locks on multi-shard update

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#2451]
Hit this during release testing.  citus_lock_waits failed to show waiting process id when multi-shard update command is waiting for another multi-shard update.

[PR description](https://github.com/citusdata/citus/pull/2381) states it could not catch single shard modifications outside of transaction block, however this is nothing like it.

Have two tables t1(a int, b int), r1(a int, b int). t1 is hash distributed r1 is references.

# Test 1

### Session 1:
```sql
begin;
update t1 set b=1 where b = 2;
```

### Session 2:
```sql
begin;
update t1 set b = 3 where b = 2;
--> blocked
```

### Session 3:
```sql
select * from citus_lock_waits;
--> shows nothing
```

# Test 2: repeat of test 1 on a reference table

### Session 1:
```sql
begin;
update r1 set b=1 where b = 2;
```

### Session 2:
```sql
begin;
update r1 set b = 3 where b = 2;
--> blocked
```

### Session 3:
```sql
select * from citus_lock_waits;
--> shows session 2 query blocked on session 1
```

**Comment by onderkalaci** [comment]
That's not good.

The processes are blocked on the shard advisory locks on the coordinator and we're not considering those locks in `citus_lock_waits` given that we rely on `dump_global_wait_edges()` which ignores those locks since those transactions are not yet in distributed transactions.

I think we can fix this by simply swapping the lines that acquires the advisory locks and the one that starts the coordinated distributed transaction:

```C
diff --git a/src/backend/distributed/executor/multi_router_executor.c b/src/backend/distributed/executor/multi_router_executor.c
index 32f62223..c5d7f483 100644
--- a/src/backend/distributed/executor/multi_router_executor.c
+++ b/src/backend/distributed/executor/multi_router_executor.c
@@ -1351,6 +1351,8 @@ ExecuteModifyTasks(List *taskList, bool expectResults, ParamListInfo paramListIn
                LockPartitionRelations(firstShardInterval->relationId, RowExclusiveLock);
        }
 
+       BeginOrContinueCoordinatedTransaction();
+
        /*
         * Ensure that there are no concurrent modifications on the same
         * shards. In general, for DDL commands, we already obtained the
@@ -1362,8 +1364,6 @@ ExecuteModifyTasks(List *taskList, bool expectResults, ParamListInfo paramListIn
         */
        AcquireExecutorMultiShardLocks(taskList);
 
-       BeginOrContinueCoordinatedTransaction();
-
        if (MultiShardCommitProtocol == COMMIT_PROTOCOL_2PC ||
                firstTask->replicationModel == REPLICATION_MODEL_2PC)
        {
```

That should be fine in terms of the deadlock detection purposes as well (e.g., these transaction cannot be part of distributed deadlocks due to these advisory locks, but, having one more line in `dump_global_wait_edges()` shouldn't be a problem and even be more correct).

@marcocitus and @velioglu do you have any comments/notes on the above?


(@mtuncer, a side note:  we probably overlooked this bug since we've mostly tested these views in MX where you can initiate these queries concurrently from different worker nodes. But, this is equivalent to executing these commands from a single worker node.)

**Comment by marcocitus** [comment]
+1 on making that fix.

Are there any other locks we might miss? I guess metadata locks? Is there any risk of false positives in the deadlock detection?

**Comment by onderkalaci** [comment]
> Are there any other locks we might miss?  I guess metadata locks?

I think we also miss relation locks on `DDL`s such as the following:

```
-- session 1
BEGIN;
ALTER TABLE test ADD COLUMN x;
```

```
-- session 2 could be any operation on the test table
BEGIN;
UPDATE test SET value_1 = 15;
```

Just thinking loudly: We could maybe move `BeginOrContinueCoordinatedTransaction ()` to utility hook for certain DDLs that we want to show in these views, before `standardProcess_Utility` is called. But that seems like an invasive change for the last minute.

> Is there any risk of false positives in the deadlock detection?

The common source of the false positive deadlocks we've had in the past was that they were all locks that cannot be part of a distributed deadlock, see [IsProcessWaitingForSafeOperations()](https://github.com/citusdata/citus/blob/master/src/backend/distributed/transaction/lock_graph.c#L491-L509).

These advisory locks sounds like having the same behaviour in that manner, but with a major difference from an other perspective. Those locks are acquired and released as soon as possible within a single statement, and that could happen multiple times while running the same statement. However, Citus holds these advisory locks until the transaction is finished. So, there is no `hold->release->hold->release->...` pattern, which was the origin of false positives.

So, I cannot see any risk of false positives. Do you also agree that the above description is OK and we should be fine?
