### ISSUE TITLE
Can not run run_command_on_workers to create citus extension after ssl is made required

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#2534]
I used to configure my local cluster with something like below

```
- create extension on coordinator
- do master add node for each worker on the coordinator
- run run_command_on_workers to create extension on workers
```

Now we require ssl after creating extension, I can no longer use run_command_on_workers to create extension on workers. Each connection fail with `server does not support SSL, but SSL was required`

Workaround is to make separate connection to each worker, and create extension one by one. 
We should either create a proper workaround, or mention this in documentation.

**Comment by metdos** [comment]
@marcocitus @thanodnl is this something we want to fix for 8.1?

**Comment by thanodnl** [comment]
I don't think this is anything we can fix without introducing a security risk.

The work around described is the official documented way of installing a citus cluster on our docs for:
- [debian single node](http://docs.citusdata.com/en/v8.0/installation/single_machine_debian.html) 
- [redhat single node](http://docs.citusdata.com/en/v8.0/installation/single_machine_rhel.html)
- [debian multi machine](http://docs.citusdata.com/en/v8.0/installation/multi_machine_debian.html)
- [redhat multi machine](http://docs.citusdata.com/en/v8.0/installation/multi_machine_rhel.html)

All these pages let the user execute `CREATE EXTENSION` on the nodes individually before adding them to the cluster.

If you'd specifically want this to work you can set `citus.node_conninfo` to `sslmode=prefer` before creating the extension. But in that case you will not be testing with ssl from coordinator to the workers.

In future releases we might want to rethink how a cluster is build. IMHO it would be good to have some basic checks when adding/activating a node. Eg. connecting to the node and checking Citus is installed. Adding a node without creating the extension __only__ worked because the cluster was empty. If there was a reference table it would start creating its shard which I suspect will fail because of missing UDF's.

**Comment by metdos** [comment]
> don't think this is anything we can fix without introducing a security risk.

Then, can we close the issue?
