### ISSUE TITLE
Fix spurious NOTICE messages generated with the ANY clause while querying hash partitioned tables

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus#258]
When using the ANY clause in a query on a hash partitioned table (created using pg_shard), we get a NOTICE like the following
"NOTICE:  cannot use shard pruning with ANY (array expression)
HINT:  Consider rewriting the expression with OR clauses."

This issue occurs even if the column being referenced in the ANY column is not the distribution column.

For eg. the query "select count(*) from github_events where event_id = ANY ('{1,2,3}')" generates this WARNING, even though github_events is distributed by the repo_id column.

**Comment by mtuncer** [comment]
@sumedhpathak note that there are cases that we can not address with this work.
If query where clause looks like the following
```... where partition_column in (1,2,3) or other_column = 5```

We detect that partition_column is involved in the first clause, report the notice message suggesting shard pruning might be possible if the user re-writes the query. However, the second part of where clause prevents shard pruning since it has an OR filter on a non-partition column.

@aamederen did a preliminary investigation on how to address this problem. He reported that the required fix is much more complicated. 

We could accept the fix as it is now, and open an another issue to track this.

**Comment by aamederen** [comment]
Merged the pull request #392, which fixes the original case.
