### ISSUE TITLE
Shard interval issue only when using subquery

### ISSUE THREAD

**Issue by tomcashman** [citusdata/citus#2771]
I've currently using union all statements for some complex queries on append mode tables. However, I'm finding an issue when I try to use these queries as a subquery. Below is a basic query I could reproduce the issue with.

Initially I thought my shard intervals were overlapping based on the error. However, if I run just the union queries it'll work fine:
```sql
(SELECT * FROM messages_logs_2019_02_18 WHERE _timestamp >= 1550361600000 AND _timestamp <= 1550534100000) UNION ALL (SELECT * FROM messages_logs_2019_02_17 WHERE _timestamp >= 1550361600000 AND _timestamp <= 1550534100000)
```

If I try using this in a subquery I get the error below.
```sql
SELECT * FROM ((SELECT * FROM messages_logs_2019_02_18 WHERE _timestamp >= 1550361600000 AND _timestamp <= 1550534100000) UNION ALL (SELECT * FROM messages_logs_2019_02_17 WHERE _timestamp >= 1550361600000 AND _timestamp <= 1550534100000)) AS hit_results;
```

```
ERROR:  cannot push down this subquery
DETAIL:  Currently append partitioned relations with overlapping shard intervals are not supported
```

**Comment by onderkalaci** [comment]
@tomcashman This doesn't mean that the shard intervals are not overlapping. Because, the first query doesn't go through the push down planner (see related issue #1913).

In the first case, Citus recursively plans each subquery separately, but in the latter case, it tries to go through the more optimal case where the whole query is executed across all the related shards in a single step. So, in the first case, there is no requirement for non-overlapping shards.

I think the obvious problem here is that Citus should have tried the recursive planning once the pushdown is not applicable. So, instead of erroring out [here](https://github.com/citusdata/citus/blob/59e54de54dc5ffc914246dc76f7a6954f5e8ede8/src/backend/distributed/planner/multi_physical_planner.c#L2301) the planner should have deferred the error and continued with the recursive planning.

**Comment by tomcashman** [comment]
Thanks for the quick response @onderkalaci :) I'll double check the shard intervals again. Just to check, this means that the shardminvalue and shardmaxvalue should not overlap between shards correct?

**Comment by tomcashman** [comment]
After much digging, I found one shard that was overlapping. Thanks for the help @onderkalaci :)

**Comment by tomcashman** [comment]
After fixing the shard, the issue still occurs and I think it may be related to empty shards as the table I've isolated it to has 2 empty shards. Are empty shards considered as overlapping?

**Comment by tomcashman** [comment]
After further testing I've confirmed that the push down planner considers empty shards as overlapping.

**Comment by marcocitus** [comment]
That sounds right. Initially the shardminvalue and shardmaxvalue are NULL, which actually means the shard could contain any value and thus overlaps with everything. You could update the metadata in the same transaction as master_create_empty_shard to avoid the problem.

**Comment by tomcashman** [comment]
I didn't think of updating the metadata. That will solve the issue, thank you :)
