### ISSUE TITLE
One task failure causes whole query to fail in adaptive executor even when replication factor > 1

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#2823]
Had a 64 shard table t3(a,b,c) with replication factor = 2 distributed on column a, total 100M rows

run 
```sql
select count(distinct a) from t3;
```

using default settings (adaptive executor). and killed a random worker process.
```
postgres=# select count(distinct a) from t3;
ERROR:  terminating connection due to administrator command
CONTEXT:  while executing command on localhost:9701
```

set `set citus.task_executor_type to 'real-time'` and run the same query again.
killed a random worker task, this time query completed.
```
postgres=# select count(distinct a) from t3b;
WARNING:  terminating connection due to administrator command
WARNING:  SSL connection has been closed unexpectedly

  count  
---------
 1000001
(1 row)
```

**Comment by marcocitus** [comment]
This change in behaviour is by design.  We decided to give hard errors for failures that occur after a command was sent because a) for performance reasons we no longer store results in intermediate files which means we can no longer tolerate getting back the same rows from multiple placements due to a failover, and b) we can give more meaningful error messages to the client by throwing a hard error immediately.
