### ISSUE TITLE
backend crash by user command

### ISSUE THREAD

**Issue by thanodnl** [citusdata/citus#2828]
During testing I ran into this query that will crash the backend by any user.

```
postgres=# SELECT worker_hash_partition_table(42,1,'SELECT a FROM generate_series(1,100) AS a', 'a', 23, ARRAY[0]);
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
Time: 8.579 ms
!>
```

Crux is probably in the length of the array.
Low priority

**Comment by serprex** [comment]
This is caused by a binary search in `SearchCachedShardInterval` over the array returning -1 (not found) which is then used as `partitionId` in `FilterAndPartitionTable`

We currently map `NULL` partition keys to `0`. We could also map `-1` to `0`. However we also only allocate as many files as there are partitions, so in this case we'd still be out of bounds

There's probably an out where we allocate an additional file which we can then map `NULL` & `-1` to

Alternatively we're probably better off raising an error when an empty array is passed to `worker_hash_partition_table`
