### ISSUE TITLE
pg_dist_colocation doesn't maintain uniqueness on replication/shardcount/type

### ISSUE THREAD

**Issue by serprex** [citusdata/citus#2873]
This is causing the last 3 test failures in #2844

```
In multi_metadata_sync I added some select * from pg_dist_colocation lines

CREATE TABLE mx_ref (col_1 int, col_2 text);
SELECT create_reference_table('mx_ref');
+WARNING:  COLO SEARCH 1 1 0
+WARNING:  CREATECOLO
+WARNING:  reftblcolo 10005 1 1 0
  create_reference_table
---------------------------------------------------------------------

 (1 row)

+select * from pg_dist_colocation;
+ colocationid | shardcount | replicationfactor | distributioncolumntype
+---------------------------------------------------------------------
+        10001 |          7 |                 1 |                     23
+        10002 |          3 |                 1 |                     23
+        10003 |          4 |                 1 |                     23
+        10004 |          1 |                 2 |                      0
+        10005 |          1 |                 1 |                      0
+(5 rows)
+
SELECT shardid, nodename, nodeport
FROM pg_dist_shard NATURAL JOIN pg_dist_shard_placement
WHERE logicalrelid='mx_ref'::regclass;
  shardid | nodename  | nodeport
---------+-----------+----------
  1310072 | localhost |    57637
(1 row)

 \c - - - :worker_1_port
SELECT shardid, nodename, nodeport
@@ -1436,10 +1487,20 @@
(1 row)

 RESET citus.shard_count;
RESET citus.shard_replication_factor;
RESET citus.replication_model;
RESET citus.multi_shard_commit_protocol;
ALTER SEQUENCE pg_catalog.pg_dist_groupid_seq RESTART :last_group_id;
ALTER SEQUENCE pg_catalog.pg_dist_node_nodeid_seq RESTART :last_node_id;
ALTER SEQUENCE pg_catalog.pg_dist_colocationid_seq RESTART :last_colocation_id;
ALTER SEQUENCE pg_catalog.pg_dist_placement_placementid_seq RESTART :last_placement_id;
+select * from pg_dist_colocation;
+ colocationid | shardcount | replicationfactor | distributioncolumntype
+---------------------------------------------------------------------
+        10001 |          7 |                 1 |                     23
+        10002 |          3 |                 1 |                     23
+        10003 |          4 |                 1 |                     23
+        10004 |          1 |                 2 |                      0
+        10005 |          1 |                 2 |                      0
+(5 rows)
+

This duplicate 1/2/0 entry between 10004/10005 stick around for the test suite, causing differences when pg11 picks 10004 & pg12 picks 10005. Both selects are happening on master_port

Same goes for multi_remove_node_reference though haven’t dug into why we’re creating 1370004/1370005 ids when 10004/10005 are available
```

This state happens here: https://github.com/citusdata/citus/blob/e88cb8335fc0c692cf514505125959804abad7ae/src/backend/distributed/utils/reference_table_utils.c#L185

In test we update the 1-shard 1-replication to 1-shard 2-replication, meanwhile such a colocation already exists

Possible approaches:
- Introduce a new function which deduplicates colocations (ie deletes duplicates & updates all references to refer to the surviving record)
- Have UpdateColocationGroupReplicationFactor check for conflict & if there’s a conflict leave the existing colocation as is while updating everything to point to existing record
- Never update. Insert-if-not-there a colocation with the desired replication factor & update references to the new record
- Have reference tables use a colocation entry with a NULL replication factor
- @onderkalaci suggests we shouldn't have reference tables use colocation

**Comment by onderkalaci** [comment]
Could it be possible that this is happening because we're manually editing the metadata in `multi_metadata_sync `? Because I couldn't reproduce it without manual metadata changes.

**Comment by onderkalaci** [comment]
> Could it be possible that this is happening because we're manually editing the metadata in multi_metadata_sync ? Because I couldn't reproduce it without manual metadata changes.

If you can come up with the minimal steps to reproduce the issue, we'd be able to understand the bug thoroughly?

**Comment by serprex** [comment]
```
-- workers on port 5433/5434
create table rf1(id int);
create table rf2(id int);

select create_reference_table('rf1');
select * from pg_dist_colocation; -- (id 1, rf 3)
select master_disable_node('localhost', '5434');
select * from pg_dist_colocation; -- same
select create_reference_table('rf2');
select * from pg_dist_colocation; -- new record: (id 2, rf 2)
select master_activate_node('localhost', '5434');
select * from pg_dist_colocation; -- same
select master_remove_node('localhost', '5434');
select * from pg_dist_colocation; -- both are rf 2
```

**Comment by onderkalaci** [comment]
Thanks. `master_disable_node()` has been a not well designed/documented [function](https://github.com/citusdata/citus_docs/issues/487) for a while.

So, if `master_disable_node()` does something similar to `ReplicateAllReferenceTablesToNode()`, are we going to be OK?

```C
	/*
	 * After replicating reference tables, we will update replication factor column for
	 * colocation group of reference tables so that worker count will be equal to
	 * replication factor again.
	 */
	workerCount = list_length(workerNodeList);
	firstReferenceTableId = linitial_oid(referenceTableList);
	referenceTableColocationId = TableColocationId(firstReferenceTableId);
	UpdateColocationGroupReplicationFactor(referenceTableColocationId, workerCount);
```

**Comment by serprex** [comment]
`UpdateColocationGroupReplicationFactor` is called from two locations, but always for reference tables. This issue is prevented if we never have two records with 0 typeid & same shard count, but different replication factor

**Comment by onderkalaci** [comment]
> UpdateColocationGroupReplicationFactor is called from two locations, but always for reference tables.

Aren't we also talking about reference tables here? Both your example above and the regression tests you point are reference tables.

> This issue is prevented if we never have two records with 0 typeid & same shard count, but different replication factor

When we first implemented reference tables**, we designed it in a way that all the reference tables would have only a single colocationId - as expected. And, have the node metadata changing  (`master_activate_node()`, `master_disable_node()` etc) functions update this colocation group's replication factor when necessary.

What I see here is that, the same logic for `master_disable_node()` has been forgotten and thus we end up with multiple entries for your above set of steps. We should have the same logic there.


The regression tests you've shared doesn't have `master_disable_node()`. In that case, the issue is different because we've a bug in our implementation. What's happening is the following (and semi-related with  #953 where if you remove node metadata manually, you'd get into other weird cases):


```SQL


SELECT master_add_node('localhost', 9700);
SELECT master_add_node('localhost', 9701);


create table rf1(id int);
select create_reference_table('rf1');
SELECT * FROM pg_dist_colocation;

┌──────────────┬────────────┬───────────────────┬────────────────────────┐
│ colocationid │ shardcount │ replicationfactor │ distributioncolumntype │
├──────────────┼────────────┼───────────────────┼────────────────────────┤
│            3 │          1 │                 2 │                      0 │
└──────────────┴────────────┴───────────────────┴────────────────────────┘
(1 row)

DROP TABLE rf1;

-- dropping the only reference table followed by remove node
-- keeps the colocationId in the pg_dist_colocation
-- instead, we should have removed it
SELECT master_remove_node('localhost', 9701);

SELECT * FROM pg_dist_colocation;
┌──────────────┬────────────┬───────────────────┬────────────────────────┐
│ colocationid │ shardcount │ replicationfactor │ distributioncolumntype │
├──────────────┼────────────┼───────────────────┼────────────────────────┤
│            3 │          1 │                 2 │                      0 │
└──────────────┴────────────┴───────────────────┴────────────────────────┘
(1 row)

-- now, the replication factor is 1
create table rf2(id int);
select create_reference_table('rf2');


-- we end up with multiple colocation entries
SELECT * FROM pg_dist_colocation;
┌──────────────┬────────────┬───────────────────┬────────────────────────┐
│ colocationid │ shardcount │ replicationfactor │ distributioncolumntype │
├──────────────┼────────────┼───────────────────┼────────────────────────┤
│            3 │          1 │                 2 │                      0 │
│            4 │          1 │                 1 │                      0 │
└──────────────┴────────────┴───────────────────┴────────────────────────┘
(2 rows)

```

So, the following logic in the `master_remove_node()` looks wrong, we should have checked `pg_dist_colocation` to find the reference table colocationId, not the existing reference tables because we might not have it any (alternatively DROP table should have removed the colocationId for reference tables if that's the last one -- but drop trigger is tricky to touch):

```C

	/*
	 * After deleting reference tables placements, we will update replication factor
	 * column for colocation group of reference tables so that replication factor will
	 * be equal to worker count.
	 */
	if (WorkerNodeIsPrimary(workerNode))
	{
		referenceTableList = ReferenceTableOidList();
		if (list_length(referenceTableList) != 0)
		{
			Oid firstReferenceTableId = linitial_oid(referenceTableList);
			uint32 referenceTableColocationId = TableColocationId(firstReferenceTableId);

			List *workerNodeList = ActivePrimaryNodeList();
			int workerCount = list_length(workerNodeList);

			UpdateColocationGroupReplicationFactor(referenceTableColocationId,
												   workerCount);
		}
	}
```

So, basically we should fix the logic for this code-block and also add something similar to `master_disable_node()`.

I see two quick ways to fix. Either change the regression tests in a way that, we at least have one reference table in the cluster, so that new reference tables could always co-locate themselves with it. Otherwise,  fix the issue in the above logic. I'm inclined to go with the former because this is a really edge case that could very unlikely to happen in production systems. Still, if you want to fix the issue, I'd be happy to review. 


** we can obviously argue whether is it a good idea to have a colocationId for reference tables or not, but this is how it is designed as of now. So, we should either fix the bug, or the design. I'd go for the former because we've already got too many things to work on for now and dealing with that would require lots of discussion :) See #962 and please comment on with any suggestions/thoughts you have.
