### ISSUE TITLE
Reference table may not be replicated if created during master_add_node

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#2909]
Creating a reference table and master_add_node currently do not block each other, which means that reference tables created while adding a node may not be replicated to the new worker node.

Session 1:
```sql
BEGIN;
set citus.multi_shard_modify_mode to 'sequential';
CREATE TABLE ref (a int, b int);
SELECT create_reference_table('ref');
```

Session 2:
```sql
SELECT master_add_node(...);
```

Session 1:
```sql
CREATE TABLE test (x int, y int);                                                                                                                                       
SELECT create_distributed_table('test','x');                                                                                                      
SELECT * FROM test JOIN ref ON (a = x);
ERROR:  relation "ref_102072" does not exist
```

**Comment by serprex** [comment]
MultiTaskTrackerExecute:
- s1: add node
- s2: task tracker modify
- s1: node out of sync?

broadcast_intermediate_result
- s1: add node
- s2: broadcast_intermediate_result
- s1: node doesn't have file (only matters if afterwards we expect file)

master_create_empty_shard
- We acquire lock

citus_create_restore_point
- OpenConnectionsToAllNodes, RemoteTransactionListBegins, now we lock. Too late?

master_create_shards.c
- CreateShardsWithRoundRobinPolicy acquires lock
- CreateReferenceTableShard
    - This may be the better place to acquire the lock in create_reference_table

reference_table_utils.c
- ReplicateShardToAllWorkers acquires lock
- CreateReferenceTableColocationId does not. Potential way to create two reference table colocation groups? Potential fix without locking: update to search for type=invalidoid

resource_lock.c
- IsFirstWorkerNode is getting complicated to figure out because now we're trying to get nodes to agree on one node so as long as locking elsewhere is correct this should be fine?
    - That said, would be nice to replace SortList with an O(N) ListMinimum

metadata_sync.c
- HasMetadataWorkers:
    - s1: create metadata worker
    - s2: think there aren't any metadata workers

schema.c
- s1: add node
- s2: EnsureSchemaExistsOnAllWorkers
- s1: new node doesn't have schema

RecoverTwoPhaseCommits
- shouldn't care about new nodes, so looks okay

get_global_active_transactions
- don't think missing a node is relevant here

SendCommandToFirstWorker
- should be fine unless we rely on SendCommandToFirstWorker being the same worker next time
- SendBareCommandListToWorkers: primarily used for concurrent indexing. Possible to miss creating index on new node?
- SendCommandToWorkersParams: may miss new nodes, or new metadata workers, etc

CitusStatActivity: okay missing some
GetLocalNodeDistStat: okay missing some

create_distributed_table
- PR adds lock for CreateReferenceTableShard here, moving down could open up weird case of create_reference_table thinking there's non-zero workers alongside master_remove_node

AcquireDistributedLockOnRelations
- citus_truncate_trigger won't have all the locks it assumes it has if node table updated between ProcessTruncateHook & trigger
