### ISSUE TITLE
Custom aggregates throw permission denied error when run as non-superuser

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#3222]
When using a custom aggregate as non-superuser, Citus throws a permission denied error:
```
ALTER TABLE test ADD COLUMN z geometry;
SELECT ST_MemUnion(z) FROM test; 
ERROR:  permission denied for schema citus
```

**Comment by serprex** [comment]
Right, I was originally putting the support functions in `pg_catalog` & found that non-superuser could use `citus` namespace, but then we recently revoked access to `citus` namespace

Since I'm wanting to dynamically generate these support functions eventually, I'd rather not pollute the `pg_catalog` space. Does it make sense to create a `citus_public` schema?

**Comment by marcocitus** [comment]
I think for now the pg_catalog schema is fine, though I agree that's not where we would want auto-generated functions to be. We probably need to rethink our schemas a bit.
