### ISSUE TITLE
ERROR:  citus cache lookup failed for aggregate <num>

### ISSUE THREAD

**Issue by will** [citusdata/citus#3295]
I don’t know if this is a real problem or not, but it is fairly easy to cause this error when calling `worker_partial_agg` and `coord_combine_agg`. I don’t have an examples of this happening without an `_agg` function in the query. But I figured I'd report it in case it's still a problem.

```sql
select
     pg_catalog.worker_partial_agg(
       cast(pg_catalog.pg_my_temp_schema() as oid),
       cast(pg_catalog.pg_stat_get_checkpoint_sync_time() as anyelement)) over (partition by sample_0.objoid order by sample_0.classoid,sample_0.objoid) as c3
 from
   pg_catalog.pg_description as sample_0
```
ERROR:  citus cache lookup failed for aggregate 0

```sql
 select
     pg_catalog.coord_combine_agg(
       cast(sample_0.dbid as oid),
       cast(cast(null as cstring) as cstring),
       cast(sample_0.dbid as oid)) over (partition by sample_0.classid order by sample_0.classid) as c5
 from
   pg_catalog.pg_shdepend as sample_0 tablesample bernoulli (3.6)
```
ERROR:  citus cache lookup failed for aggregate 16385

There is some previous discussion on https://github.com/citusdata/citus/commit/495c0f5117218d340e60a4b56f1ff8fed40f608e#commitcomment-36338668 with @serprex

**Comment by serprex** [comment]
These aggregates are meant to be called by Citus generated SQL. The first oid is expected to be an aggregate oid. So raising errors here is good, since we'd only want to make sure we don't have permission issues going awry or segfaults

I think there may be an issue with passing an aggregate oid which requires different inputs than what's being supplied to the `worker_partial_agg`, but that's a separate issue I hope to look into soon

**Comment by serprex** [comment]
I've created #3328 to outline the type safety issue I mentioned here. Closing this issue
