### ISSUE TITLE
Incorrect behavior while creating indexes of same name on different tables

### ISSUE THREAD

**Issue by samay-sharma** [citusdata/citus#350]
Steps to reproduce:

```sql
postgres=# create index new_index on b_dist (b);
CREATE INDEX

postgres=# create index new_index on a_dist (b);
ERROR:  relation "new_index" already exists
```

In the second command, even though we get the error, the create index command is propagated to the worker node and the indexes are created on the worker nodes. This is because the names on the worker nodes don't contradict because of shardids being appended to index names.

However, when the command is being applied to the master table, this check is performed and we error out as both indexes have the same name. Hence, the master table does not have the indexes, but the worker tables do.

To fix this, we should add a check for verifying that the index with that name does not exist before propagating the command to the worker nodes.

This works properly if we create the index with same name on the same table.
```sql
postgres=# create index a_index on a_dist (b);
WARNING:  could not receive query results from localhost:9700
DETAIL:  Client error: relation "a_index_102011" already exists
ERROR:  could not execute DDL command on worker node shards
```

**Comment by lithp** [comment]
Agreed that #357 is a much better fix, this change doesn't fix the root problem.

postgres checks for a lot more than whether the name already exists in the catalog, I read through the code and couldn't find anything else which would obviously work on the workers and fail on the master, but this would feel less brittle (and more efficient!) if the master made sure commands were okay first. Right now a command which creates an index on a system catalog, for instance, will waste time failing on every worker.

Statements like `CREATE INDEX ON a (b);` currently fail and are difficult for us to support, because the autogenerated index name is created by some static methods in postgres' `backend/commands/indexcmds`. To add support we would have to copy the code over and keep it in sync. If we create the index locally before propagating we can instead read out the index name which was used.

**Comment by lithp** [comment]
Is this the kind of thing I should also add a regression test for?

**Comment by sumedhpathak** [comment]
@lithp We decided to continue fixing this via the current temporary approach, primarily since #357 is going to take a fair bit longer. We may schedule that for 5.2.
