### ISSUE TITLE
Confusing WARNING message on DROP EXTENSION citus

### ISSUE THREAD

**Issue by samay-sharma** [citusdata/citus#367]
```
postgres=# drop extension citus ;
WARNING:  could not clean the metadata cache on DROP EXTENSION command
HINT:  Reconnect to the server again.
ERROR:  cannot drop extension citus because other objects depend on it
DETAIL:  table github_events depends on extension citus
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```

In this case, even if the extension isn't dropped, we ask the user to reconnect. This causes a confusion as to the cause of the problem is. People familiar with Postgres might understand why they're seeing the `ERROR` message (dependency on the tables), others might not.

Also, the error message

```
WARNING:  could not clean the metadata cache on DROP EXTENSION command
HINT:  Reconnect to the server again.
```

might not be very understandable to new users. We were chatting with @begriffs and he mentioned that he didn't understand what the metadata cache is and why it couldn't be cleaned up.

**Comment by lithp** [comment]
After talking with anarazel:

The metadata cache has a static flag [extensionLoaded](https://github.com/citusdata/citus/blob/52eacd29bb33859b1393de05cfb7df23b2b7c3bc/src/backend/distributed/utils/metadata_cache.c#L308) which is cached (checking whether the extension is still around for every insert would be pretty slow). If you DROP EXTENSION and then run a query we still think citus is loaded but then error out because we can't find the metadata tables.

What we should instead do is reset that flag (and preferably all state in the cache) when the extension is dropped. @anarazel suggested watching for pg_dist_shard_placement in [`InvalidateDistRelationCacheCallback`](https://github.com/citusdata/citus/blob/52eacd29bb33859b1393de05cfb7df23b2b7c3bc/src/backend/distributed/utils/metadata_cache.c#L653) but why can't we do it in the same path as the [`WarnIfDropCitusExtension`](https://github.com/citusdata/citus/blob/52eacd29bb33859b1393de05cfb7df23b2b7c3bc/src/backend/distributed/executor/multi_utility.c#L210) which emits the error?

The last wrinkle is that we have some other state which would likely cause problems if you tried to DROP EXTENSION and then CREATE EXTENSION in the same session and started running queries. So we should either add yet another flag `hasExtensionEverBeenLoaded` and prevent reloading, or do a better job of emptying all state.

**Comment by anarazel** [comment]
On 2016-03-30 08:57:36 -0700, Brian Cloutier wrote:
> After talking with anarazel:
> 
> The metadata cache has a static flag [extensionLoaded](https://github.com/citusdata/citus/blob/52eacd29bb33859b1393de05cfb7df23b2b7c3bc/src/backend/distributed/utils/metadata_cache.c#L308) which is cached (checking whether the extension is still around for every insert would be pretty slow). If you DROP EXTENSION and then run a query we still think citus is loaded but then error out because we can't find the metadata tables.
> 
> What we should instead do is reset that flag (and preferably all state in the cache) when the extension is dropped. @anarazel suggested watching for pg_dist_shard_placement in [`InvalidateDistRelationCacheCallback`](https://github.com/citusdata/citus/blob/52eacd29bb33859b1393de05cfb7df23b2b7c3bc/src/backend/distributed/utils/metadata_cache.c#L653) but why can't we do it in the same path as the [`WarnIfDropCitusExtension`](https://github.com/citusdata/citus/blob/52eacd29bb33859b1393de05cfb7df23b2b7c3bc/src/backend/distributed/executor/multi_utility.c#L210) which emits the error?

Because that'd only take effect in the session you're doing the check
in, not in others.

**Comment by sumedhpathak** [comment]
@lithp Do you have an estimate on time taken to fix?

**Comment by lithp** [comment]
@sumedhpathak This feels like it's a day away from being ready for review, depending on how far off base the current approach is.
