### ISSUE TITLE
Consider merging single-shard SELECT planning back to modify_planner

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#387]
When we integrated pg_shard into the Citus extension, we made changes so that ``SELECT`` logic always went through our logical and physical planner. We later deleted parts of ``SELECT`` related code from the modify_planner.c.

This issue proposes merging single-shard ``SELECT`` logic into modify_planner and renaming modify_planner to router_planner. We'd then move the logic to pick between the logical/physical and router planner for ``SELECT`` statements into the planner.

This change brings the following benefits:

1. We're working on #368 to improve partition pruning performance for hash partitioned tables. Once we have this improvement checked in, we expect that bypassing the logical and physical planner will improve simple ``SELECT`` throughput by 2x.
2. On a smaller note, the router executor currently can't execute all queries planned by the logical/physical planners. We therefore need to switch to using the real-time executor for those queries. Until we schedule #352 and #372, we'll get better throughput from the router executor.
3. We scattered single-shard ``SELECT`` logic into our executors and modify_planner. With this change, we will keep those codepaths more uniform.

**Comment by mtuncer** [comment]
@ozgune  We can not address this query with router executor since there is no where clause on the rows. We specifically look for ``<partition_column> = <some scalar value> `` in where clause. 

This query looks like ``SELECT ... FILTER (...) FROM ... WHERE true``. It fails our  router plannable criteria and goes through regular planner/executor path.

we could only execute this query if it has equality match on the partition column of hash partitioned table.

**Comment by ozgune** [comment]
@mtuncer, I copy pasted this query from another issue and forgot to add ``<partition_column> = <some scalar value>``. The original customer query has an equality clause on the partition column, and hits a single shard.

**Comment by mtuncer** [comment]
Fixed by https://github.com/citusdata/citus/pull/427
