### ISSUE TITLE
Executor crash with empty result set from workers

### ISSUE THREAD

**Issue by thanodnl** [citusdata/citus#3953]
An issue has been reported from the backend crashing under a users workload. The minimum viable reproduction seems to be:

```sql
CREATE TABLE t1 (a int PRIMARY KEY);
SELECT create_distributed_table('t1','a');
SELECT 'foo' as foo, string_agg(distinct a::character varying, ',') FROM t1;
```

With this query the workers respond with an empty result set. However during the execution of the aggregate an assertion is done to verify the tuple is not empty. In production their query caused a segfault.

Strangely without the string in the select clause of the query the query works as intended :).

**Comment by SaitTalhaNisanci** [comment]
When we return a constant with an aggregation that returns empty resultset, we get a crash.

Also we get incorrect result with a query like this:

```sql
SELECT string_agg('asd', ',') FROM t1;
 string_agg
------------

(1 row)
```

However if we insert a value to `t1` it returns correct result:

```sql
 insert into t1 values (1);
SELECT string_agg('asd', ',') FROM t1;
 string_agg
------------
 asd
(1 row)
```

**Comment by pykello** [comment]
I explained the reason for this crash in #3955, but it needs more work before becoming a reasonable solution. I'll update here.

Summary is that we change the constant in the coordinator query to a `Var` referencing worker tuples. Since there are no worker tuples in this case, and coordinator query needs to fetch the value of that ex-`Const`, now `Var`, it crashes when trying to.

In such cases we shouldn't push-down the constant to the worker. But I need some time to figure out how to detect such cases.
