### ISSUE TITLE
if i want drop a worker,how do i do ?

### ISSUE THREAD

**Issue by snmfkrqw** [citusdata/citus#409]
now, i have a master and two workers,i distributed a table two shards and there is no replication , there is one shards on per workers, now i want drop a worker,how do i do ?

**Comment by sumedhpathak** [comment]
Hi @snmfkrqw 

To understand your scenario a bit better, you created a master and two worker nodes, with a single shard per worker node. Now you want to drop a worker node, and have only a single master and a single worker node? You would get limited parallelism benefits because of that setup.

If your general question is how you decommission nodes after creating them, there are a few options. (a) Our enterprise edition has the shard re-balancer, which makes this operation easy for you. See this [link](https://www.citusdata.com/docs/citus/5.0/reference/user_defined_functions.html#cluster-management-and-repair-functions) for more information on the rebalancing functions. This utility will automatically manage this operation for you.

The other option is to do it manually. You'd have to pause writes, use a worker node UDF to copy the shard from one node to another, and then update the metadata on the master manually. E.g:
If the node to be decommissioned (say ``node-2``) contains the shard ``customer_reviews_100208``, and you want to move it to ``node-1``, you would run this command on ``node-2``:

``` SQL
SELECT worker_fetch_regular_table('customer_reviews_100208', 0, '{node-2}'::text[], '{5432}'::int[]);
```

The above command basically fetches the shard from ``node-2`` (which is running postgres on port ``5432``), and copy it to ``node-1``. 

After this is done, you'd want to update the shard placement metadata on the *master* node, specifically ``pg_dist_shard_placement``, and change the nodename, nodeport information from ``node-2`` to ``node-1``. See our documentation [here](https://www.citusdata.com/docs/citus/5.0/reference/metadata_tables.html#shard-placement-table) for information on the shard placement table.

Once you've moved all the shards over and updated the metadata, you are free to drop the worker node. 

What use-case did you have in mind when considering dropping nodes?

**Comment by snmfkrqw** [comment]
when the database low load, and saving cost, i think i will be drop some worker nodes.
now ,i have an other question ,
i create a table:
 CREATE TABLE sms_reply                                            
(
  id bigserial NOT NULL, -- 流水号
  accountno character varying(30), -- 企业号
  uid character varying(256), -- 用户自定义唯一id。最大长度不超过256的字符串。
  sid character varying(50), -- 短信发送唯一标示
  spid character varying(50), -- 唯一序列号，由通道返回
  mobile character varying(50), -- 回复短信的手机号
  reply_time timestamp with time zone, -- 回复短信的时间
  message text, -- 回复的短信内容
  extend character varying(50), -- 您发送时传入的扩展子号，未申请扩展功能或者未传入时为空串
  base_extend character varying(50), -- 系统分配的扩展子号
  createtime timestamp with time zone DEFAULT now(), -- 创建时间
  reply_data text                   
)                                           
WITH (
  OIDS=FALSE
);

and I shards it .

SMSLOG=# SELECT master_create_distributed_table('sms_reply','id','hash');                
 master_create_distributed_table 
---------------------------------
 
(1 row)

SMSLOG=# SELECT master_create_worker_shards('sms_reply',2,2);              
 master_create_worker_shards 
-----------------------------
 
(1 row)

but ,when i insert one raw date, i got a error,and i can't insert the data to my database.

SMSLOG=# INSERT INTO sms_reply(accountno, uid, sid, spid, mobile, reply_time, message, extend, base_extend, reply_data) VALUES ('quxytest', '', '', '', '13163907532', '2016-02-16 09:29:02+08', 'sasa', '', '', '');
ERROR:  cannot plan sharded modification containing values which are not constants or constant expressions

**Comment by snmfkrqw** [comment]
when i created table use command 'create table sms_reply2 as select * from sms_reply ' ;
and shard it :
SELECT master_create_distributed_table('sms_reply2', 'id', 'hash');                  
 master_create_distributed_table 
---------------------------------
 
(1 row)

SMSLOG=# SELECT master_create_worker_shards('sms_reply2', 2, 2);               
 master_create_worker_shards 
-----------------------------
 
(1 row)

if i inserted a rows data ,i got a error.

 INSERT INTO sms_reply2(accountno, uid, sid, spid, mobile, reply_time, message, extend, base_extend, reply_data) VALUES ('quxytest', '', '', '', '13163907532', '2016-02-16 09:29:02+08', 'sasa', '', '', '');
ERROR:  cannot plan INSERT using row with NULL value in partition column

**Comment by snmfkrqw** [comment]
@sumedhpathak

**Comment by marcocitus** [comment]
@snmfkrqw 

> ERROR: cannot plan sharded modification containing values which are not constants or constant expressions

Citus currently prevents you from using functions such as now() or serial types in DML statements, since they would translate to different values on different replicas. In this case they are implied by the default values specified in the create table statement.

> ERROR: cannot plan INSERT using row with NULL value in partition column

A current limitation is that you need to specify an explicit value for the partition key. Would it be possible to partition the table by a value that is always present such as accountno?

**Comment by snmfkrqw** [comment]
@marcocitus 
thank you。

**Comment by sumedhpathak** [comment]
@snmfkrqw Closing this issue. 

For future reference, for such questions about the product you can send an email to our [citus-users mailing list](https://groups.google.com/forum/#!forum/citus-users).
