### ISSUE TITLE
Cannot rename table to have a name >56 characters in length

### ISSUE THREAD

**Issue by colton-citus** [citusdata/citus#4211]
Error message is observed when renaming a distributed table to have a name greater than 56 characters in length. This does not affect creating tables with names of that length. 

Error message observed:

```
psql:rename_issue.sql:5: ERROR:  shard name this_table_name_is_carefully_padded_for_precise_16fc88b7_104057 exceeds 63 characters
CONTEXT:  while executing command on 10.0.0.23:5432
```

Reproduction script:

```
drop table if exists rename_test;
drop table if exists this_table_name_is_carefully_padded_for_precisely_57_char;
create table rename_test(col1 int);
select create_distributed_table('rename_test','col1');
alter table rename_test rename to this_table_name_is_carefully_padded_for_precisely_57_char;

--Proving that same table name is valid when created
create table  this_table_name_is_carefully_padded_for_precisely_57_char (col1 int);
select create_distributed_table('this_table_name_is_carefully_padded_for_precisely_57_char','col1');
```

**Comment by isabel-potgieter** [comment]
We ran into this issue recently when we tried to rename some partition tables, this is our error: 

```
ERROR: shard name lishistorydetailhist_13ebe59e_aa19_11ea_ba9c_0a_91632916_122770 exceeds 63 characters
  Where: while executing command on 10.0.0.172:5432 [Failed SQL: alter table raven.lishistorydetailhistory_aggregationrefactortest rename to lishistorydetailhist_13ebe59e_aa19_11ea_ba9c_0a580a823c54]
```

As you can see in the error above the table name we are trying to rename is 57 chars, the shard name trimmed some of our table name and then added some numbers at the end, but even that has a length of 63 and does not exceed 63. 

When we try to add a new partition table with 63 chars this does not give us any issues, so this issue seems to be with renaming of the tables. (any table name larger than 55 chars fails when trying to rename it with the shard error)

This is a rather urgent issue and we will appreciate some help on the matter. 

Please let us know if you require any additional information.

**Comment by onderkalaci** [comment]
Looks same as https://github.com/citusdata/citus/issues/1664

**Comment by onderkalaci** [comment]
@colton-citus @isabel-potgieter 

The reason is documented here: https://github.com/citusdata/citus/blob/master/src/backend/distributed/relay/relay_event_utility.c#L474-L496

So, I don't know  how easy to fix it.

**Comment by colton-citus** [comment]
Thanks @onderkalaci . 

Can't we use whatever logic lets us create tables with names of that length normally? We've clearly got something to handle that, not sure why it isn't called on rename.

**Comment by burtonks** [comment]
@colton-citus @onderkalaci @isabel-potgieter 
Just a note this same thing happens on renaming indexes but only on indexes that are distributed, regular table indexes just truncates and renames the index with no error.
