### ISSUE TITLE
Parallel Append not working at coordinator in a Time Series (partitioned) scenario

### ISSUE THREAD

**Issue by SanyoMoura** [citusdata/citus#4314]
I am testing a scenario of a partitioned table per day and remote access via fdw.
My external repository has approximately 4 billion records per day and is kept compressed in the cloud.
The solution is already working well, except that when a query is executed in the coordinator, the query sent to the node (worker) is not being parallelized in the partitions by PostgreSQL.
It is interesting that the EXPLAIN in the coordinator shows that the PARALLEL APPEND will be done, but when the query executes (EXPLAIN ANALYZE), the plan does not show me that the PARALLEL APPEND is carried out. 
The time difference between direct execution on a node (worker) and the coordinator is quite large.
Any idea why the EXECUTOR in the coordinator doesn't generate a parallelized query in the worker?

EXPLAIN at Coordinator:
https://explain.depesz.com/s/mOvX

EXPLAIN ANALYZE at Coordinator:
Planning Time: 1.871 ms
Execution Time: 9055.347 ms
https://explain.depesz.com/s/nwiz

EXPLAIN ANALYZE at Node (worker):
Planning Time: 13.011 ms
Execution Time: 1228.698 ms
https://explain.depesz.com/s/tech

**Comment by onderkalaci** [comment]
> My external repository has approximately 4 billion records per day and is kept compressed in the cloud.

This is impressive.

> Any idea why the EXECUTOR in the coordinator doesn't generate a parallelized query in the worker?

To give some information, Citus does not interfere with the Postgres' executor on the workers. Citus simply generates query strings for the shards, and lets Postgres execute it on the shards. 

So, append/parallel append decision is given by the Postgres planner on the shards. [This](http://docs.citusdata.com/en/v9.5/get_started/concepts.html) might give some more insights to you.

> EXPLAIN ANALYZE at Coordinator:

and

>EXPLAIN ANALYZE at Node (worker):

Seem to have different number of partitions involved. We had a minor bug on EXPLAIN ANALYZE (https://github.com/citusdata/citus/issues/4169), which is fixed in Citus 9.4.2 (you can use `SELECT citus_version() to see the exact version number)`. Can you make sure that you are on 9.4.2?


Other than that, concurrency could have an effect. As you might know, Postgres has a buffer of parallel workers allowed, see [here](https://www.postgresql.org/docs/10/runtime-config-resource.html#GUC-MAX-PARALLEL-WORKERS). If a query is executed alone, it is very likely to use the parallel workers. However, if there are concurrent queries going on the workers, some shard queries will be able to use Postgres parallelism.

In multi-shard Citus queries where multiple shards are hit by one distributed query, this is a pretty common case. However, in your case the distributed query has a single task, meaning that hitting a single shard, so no Citus parallelism involved. 

I still wanted to bring this up in case there are other distributed queries going on at the same time, which might be using the `max_parallel_workers `

**Comment by SanyoMoura** [comment]
Seem to have different number of partitions involved. We had a minor bug on
EXPLAIN ANALYZE (#4169 <https://github.com/citusdata/citus/issues/4169>),
which is fixed in Citus 9.4.2 (you can use SELECT citus_version() to see
the exact version number). Can you make sure that you are on 9.4.2?

I was running on 9.4.0. So I have updated to 9.4.2 and the problem
truncating EXPLAIN was solved, but still not running with parallel when
submitted by coordinator.

Other than that, concurrency could have an effect. As you might know,
Postgres has a buffer of parallel workers allowed, see here
<https://www.postgresql.org/docs/10/runtime-config-resource.html#GUC-MAX-PARALLEL-WORKERS>.
If a query is executed alone, it is very likely to use the parallel
workers. However, if there are concurrent queries going on the workers,
some shard queries will be able to use Postgres parallelism.

I am testing in a LAB, with a stand alone query. The curiosity is that the
EXPLAIN shows planned workers and EXPLAIN ANALYZE not. When you run a query
and Postgres doesn't have parallel workers left on the pool, EXPLAIN
ANALYZE shows:
Planned Workers: 6
Launched Workers: 0

But in this case it shows nothing. It's like that for some reason the
executing submitted by EXECUTOR at coordinator is being prevented from
running in parallel by workers.

Best regards,

Sanyo Capobiango

Em sex., 13 de nov. de 2020 às 05:57, Önder Kalacı <notifications@github.com>
escreveu:

**Comment by marcocitus** [comment]
Could you share the explain output after running `set citus.explain_all_tasks to on;`?

**Comment by SanyoMoura** [comment]
Ok, but I have just 1 task because in this scenario I am searching for 1 "served_msisdn" (my distribution key), but many partitions days (that should be scanned in parallel by PostgreSQL).

https://explain.depesz.com/s/BN9O

**Comment by onderkalaci** [comment]
To be fair, I cannot understand why this could happen. If you don't use EXPLAIN, just execute the queries, do you see similar performance behavior?

I'm asking this because Citus does some additional things when EXPLAIN ANALYZE is executed. I'm curious if this has an effect or not.

Also, as a workaround for now, we can always consider reducing parallel_setup_cost or parallel_tuple_cost.   see here: https://www.postgresql.org/docs/11/parallel-plans.html#PARALLEL-APPEND

**Comment by SanyoMoura** [comment]
BINGO!!! The problem is just with EXPLAIN ANALYZE, not executing in parallel.
I logged results from my fdw executions and was able to certify that.

Thank you a lot @onderkalaci , may be you have a fix to EXPLAIN ANALYZE in near future, but I can deal without it by this time.

**EXPLAIN ANALYZE: I've just got 1 process**

`================================================================
******** LEADER 7257: Time: 630.399 (100.00%) ********
--------------------------------------------------------------------------------
Cloud Run Time: 629.123 (99.80%)
--------------------------------------------------------------------------------
Tuples Total Time  : 1.276 (0.20%)
      Process Registers Time: 0.010 (0.00%)
      Make Tuples Time      : 1.266 (0.20%)
            Make Tuples From Result Dora Time : 1.256 (0.20%)
            Heap Form Tuple (PostgreSQL) Time: 0.010 (0.00%)
--------------------------------------------------------------------------------

Scanned Relations: gprs_20190601_102492_dora gprs_20190602_102524_dora gprs_20190603_102556_dora Size: 2048
`

**NORMAL EXECUTION: I've got workers**

`================================================================
******** WORKER 8427: Time: 230.530 (100.00%) ********
--------------------------------------------------------------------------------
Cloud Run Time: 230.212 (99.86%)
--------------------------------------------------------------------------------
Tuples Total Time  : 0.318 (0.14%)
      Process Registers Time: 0.013 (0.01%)
      Make Tuples Time      : 0.305 (0.13%)
            Make Tuples From Result Dora Time : 0.302 (0.13%)
            Heap Form Tuple (PostgreSQL) Time: 0.003 (0.00%)
--------------------------------------------------------------------------------

Scanned Relations: gprs_20190601_102492_dora Size: 2048
=================================================================

=================================================================
******** WORKER 8429: Time: 279.412 (100.00%) ********
--------------------------------------------------------------------------------
Cloud Run Time: 279.112 (99.89%)
--------------------------------------------------------------------------------
Tuples Total Time  : 0.299 (0.11%)
      Process Registers Time: 0.014 (0.01%)
      Make Tuples Time      : 0.285 (0.10%)
            Make Tuples From Result Dora Time : 0.281 (0.10%)
            Heap Form Tuple (PostgreSQL) Time: 0.004 (0.00%)
--------------------------------------------------------------------------------

Scanned Relations: gprs_20190602_102524_dora Size: 2048
=================================================================

=================================================================
******** LEADER 7257: Time: 245.035 (100.00%) ********
--------------------------------------------------------------------------------
Cloud Run Time: 244.620 (99.83%)
--------------------------------------------------------------------------------
Tuples Total Time  : 0.415 (0.17%)
      Process Registers Time: 0.003 (0.00%)
      Make Tuples Time      : 0.412 (0.17%)
            Make Tuples From Result Dora Time : 0.409 (0.17%)
            Heap Form Tuple (PostgreSQL) Time: 0.003 (0.00%)
--------------------------------------------------------------------------------

Scanned Relations: gprs_20190603_102556_dora Size: 2048
=================================================================`

**Comment by onderkalaci** [comment]
> Thank you a lot @onderkalaci , may be you have a fix to EXPLAIN ANALYZE in near future, but I can deal without it by this time.

@SanyoMoura it turns out that this is a bug on Citus, see #4325. 

On the next minor/patch release, we'll include the bugfix.
