### ISSUE TITLE
COPY produces error when using hstore[]

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#463]
COPY on distributed tables throws an error when ingesting data into an hstore[]. A single hstore and other array types don't seem to have this issue.

    postgres=# CREATE TABLE test (key int, data hstore[]);
    CREATE TABLE
    postgres=# SELECT master_create_distributed_table('test','key','hash');
     master_create_distributed_table 
    ---------------------------------
     
    (1 row)
    
    postgres=# SELECT master_create_worker_shards('test',4,1);
     master_create_worker_shards 
    -----------------------------
     
    (1 row)

    postgres=# COPY (SELECT 0, ARRAY[hstore(ARRAY['key'],ARRAY['value'])]) TO '/tmp/test';
    COPY 1
    postgres=# COPY test FROM '/tmp/test';
    ERROR:  wrong element type

**Comment by onderkalaci** [comment]
The same test works with \STAGE.

**Comment by anarazel** [comment]
On 2016-04-22 10:14:15 -0700, Önder Kalacı wrote:
> The same test works with \STAGE.

Hrmpf. I bet the problem doesn't exist for arrays of builtin types, and
that if you were to use binary input/output with stage it'd error out
the same.  For unbeknownst to me, and I think anyone, reasons the
send/recv format for arrays (and composites) includes the oid of the
contained type.  If hstore is created separately on workers/master it's
possible that the hstore type has different oids.  Fun.

**Comment by dorianj** [comment]
> For unbeknownst to me, and I think anyone, reasons the
> send/recv format for arrays (and composites) includes the oid of the
> contained type.  If hstore is created separately on workers/master it's
> possible that the hstore type has different oids.  Fun.

We've run into the same tough issue. The only work-around we found was to use the text format when doing dumps of `hstore[]` between different machines.

**Comment by marcocitus** [comment]
For COPY, I guess the fix would be to use the text format between master and workers. We can perhaps make it configurable with the existing citus.binary_master_copy_format setting.

**Comment by onderkalaci** [comment]
@anarazel 
> Hrmpf. I bet the problem doesn't exist for arrays of builtin types

Yes, array of integers and text works fine.

**Comment by byucesoy** [comment]
I skimmed trough PostgreSQL source and also did not understand why oid is added. I also removed lines which write and read oid and all PostgreSQL and citus tests worked fine. COPY with hstore array also worked with no problem.

@anarazel would it be possible to send a patch to PostgreSQL to remove oid in send/recv format for arrays? If it is possible, I think that would be much neater solution. Because in other case, I do not have any other idea apart from sending data in text format, which I think may not be clean solution.

**Comment by anarazel** [comment]
@byucesoy Sure, it makes sense to send a patch to postgres. But it'll be applied to the next major version (9.7) at the earliest; and the development window for that hasn't yet opened. such behaviour modifying changes are unlikely to be accepted into a bugfix only release.

**Comment by sumedhpathak** [comment]
@byucesoy Apart from modifying Postgres code, do we have other thoughts on fixing this for the short term? Thanks.

**Comment by marcocitus** [comment]
I think the two possible fixes are:

- override the array parsing function in the catalog when installing Citus
- allow users to switch to text format (e.g. using binary_master_copy_protocol)

**Comment by byucesoy** [comment]
I think we can go one of the @marcocitus's suggestions for short term then we can send a patch to postgres for 9.7 release.

**Comment by byucesoy** [comment]
At first I thought first option was easier to implement and cleaner solution but I encounter some problems;

We need to override array_send and array_recv. However array_recv returns polymorphic type(anyarray) while none of its parameters is polymorphic(internal, oid and integer). However postgres standard does not allow this type of functions.

> It is permitted to have polymorphic arguments with a fixed return type, but the converse is not.
> -[PostgreSQL Documentation](https://www.postgresql.org/docs/9.6/static/xfunc-sql.html#AEN59016)

Therefore we cannot define new function for array_recv with CREATE FUNCTION. I am not sure how array_recv itself can be defined. I think since it is created by postgres itself, they skip parameter checks and create required metadata manually(?). If this is the case, we can do similar thing and create the metadata manually.

Overriding array_send is much easier. We just need a create our output function then run an UPDATE query on pg_type table;

```sql
UPDATE pg_type SET typsend = oid_of_new_function WHERE typsend = 2401
```

When we want to COPY something, postgres checks pg_type table to find which function to use to serialize that particular type. In this table there are separate rows for the type itself and the array of that type. Input, output functions of type itself is specified by user while issuing CREATE TYPE command. On the other hand, input, output functions of array of that type is assigned by postgres which are always array_recv and array_send(or array_in and array_out if copy format is text). The SQL query I wrote simply sets output function to our new function if output function for that row is array_send(whose oid is 2401).

Still there are two problems of this approach;

- Changing typsend manually may have some side effects or there can be some other rows in other tables which we need to change also. I am not aware of them at the moment. More inspection is needed in this matter.
- We can add this SQL query to citus.sql file, but in that case when new type is created its output function will still be original array_send. Therefore we need to  hook CREATE TYPE commands and run that SQL query after each type creation.

By considering all these problems and more importantly our intention of not keeping this fix permanently(If we can send patch to postgres). **I think using text format is better option.**

Also for documentation purposes;
I found [this](http://postgresql.nabble.com/overriding-current-timestamp-td5507701.html) and [this](https://www.postgresql.org/message-id/1393426627566-5793703.post@n5.nabble.com) for overriding built-in postgres functions. Both suggests defining new input/output functions in a new schema and putting that schema before pg_catalog in search_path. However this will not work since the way we call built-in functions is hardcoded to call from pg_catalog.

**Comment by metdos** [comment]
> By considering all these problems and more importantly our intention of not keeping this fix permanently(If we can send patch to postgres), I think using text format is better option.

@byucesoy, thanks for the detailed explanation. I also think that we can go with text format option.

@marcocitus, @anarazel any objections?

**Comment by marcocitus** [comment]
No objections. Thanks for the detailed analysis.

**Comment by anarazel** [comment]
On 2016-06-15 23:41:26 -0700, Metin Döşlü wrote:
> > By considering all these problems and more importantly our intention of not keeping this fix permanently(If we can send patch to postgres), I think using text format is better option.
> 
> @byucesoy, thanks for the detailed explanation. I also think that we can go with text format option.
> 
> @marcocitus, @anarazel any objections?

Generally sane. I think we should automatically switch to text
though. Barely more work, and a lot better for the user.  Switch if
there's any column with a composite type, or with an array type that's
not builtin.
