### ISSUE TITLE
rebalancer can become "permanently" confused if it gets interrupted

### ISSUE THREAD

**Issue by admilazz** [citusdata/citus#4955]
In Citus 10.0, we've been doing some testing with killing the coordinator in the middle of a rebalance and it doesn't always recover. The repro steps are:

1. Set up a citus cluster with several nodes and add some distributed tables with data.
2. Set shouldhaveshards = false on one or more nodes.
3. Run "SELECT rebalance_table_shards(shard_transfer_mode := 'force_logical');" on the coordinator to begin rebalancing the shards.
4. While the coordinator node is rebalancing, kill it without doing a graceful shutdown.
5. After a few seconds, start the coordinator node back up and let it recover.
6. Rerun "SELECT rebalance_table_shards(shard_transfer_mode := 'force_logical');" to resume the rebalancing.

We've seen two kinds of errors when doing this:

- "22023: shard 102008 already exists in the target node" - This error is more common and will eventually go away (after a minute or two) if we keep retrying the rebalancing operation.
- "55006: replication slot 'citus_shard_move_subscription' is active for PID 1173" - This error is less common, but when it occurs it does not go away with repeated rebalance attempts. (We retried the rebalancing operation repeatedly for 10 minutes and kept getting the same error.)

This second error was seen repeatedly by @kothapavan35 although I haven't seen it myself.

We are using these postgres settings:

````
citus.defer_drop_after_shard_move = on
citus.defer_shard_delete_interval = 60s
citus.enable_statistics_collection = off
wal_level = logical
wal_receiver_status_interval = 1s
wal_retrieve_retry_interval = 1s
````

We'll update with more details if we can get them.

**Comment by onderkalaci** [comment]
> "22023: shard 102008 already exists in the target node" - This error is more common and will eventually go away (after a minute or two) if we keep retrying the rebalancing operation.

This error seems due to `citus.defer_drop_after_shard_move = on` and `citus.defer_shard_delete_interval = 60s`. The idea is that when a node is successfully moved, Citus keeps it the same shard on the source node for `citus.defer_shard_delete_interval` duration. At that point, if you try to move the same shard to the source node, you'd get the error mentioned. Is that the case in your test?

`citus.defer_drop_after_shard_move ` is useful to prevent deadlocks in case there are already running SELECT queries on the source node. Citus skips dropping the shard on the source node immediately after shard move so that the already running queries on the source shard can continue. 


> "55006: replication slot 'citus_shard_move_subscription' is active for PID 1173" - This error is less common, but when it occurs it does not go away with repeated rebalance attempts. (We retried the rebalancing operation repeatedly for 10 minutes and kept getting the same error.)

I'll see if I can repro this

**Comment by admilazz** [comment]
For "22023: shard 102008 already exists in the target node", yes I think that's the cause. It doesn't worry me because it eventually goes away (after a minute, when Citus performs the deferred drop).
