### ISSUE TITLE
pq: canceling the transaction since it was involved in a distributed deadlock

### ISSUE THREAD

**Issue by arashkhavari** [citusdata/citus#4985]
Sometimes raise this error in highload CRUD request. I checked the queries and only one update.
The status of my citus database distributed is 10 Shards and 2 Replicas and postgres version is 11, citus 95.
where is the problem from?

**Comment by onderkalaci** [comment]
Are the queries targeting single shard? In other words, do all queries have a distribution key filter? It is really hard to understand what is triggering the deadlocks with little information.

> I checked the queries and only one update.

Can the same update be executed concurrently by multiple sessions?

It is typically concurrent transactions run in parallel and have accesses in different orders like:

tx1:
```
BEGIN;
update touches row-1
delete touches row-2
ROLLBACK;
```
and tx2:
```
BEGIN;
update touches row-2
delete touches row-1
ROLLBACK;
```

So, please make sure that all the transactions touches the same rows in the same order, so that deadlocks are prevented.

We typically move discussions that require back and forth into our slack channel: https://slack.citusdata.com/  Github is mostly used for bug/feature tracking.

So, I'm closing this issue and please move the discussion over slack. Thanks!
