### ISSUE TITLE
Distributed queries called from within SQL functions fail to replace variables?

### ISSUE THREAD

**Issue by lithp** [citusdata/citus#499]
``` sql
CREATE TABLE origin (x BIGINT, y VARCHAR, z VARCHAR);
SELECT master_create_distributed_table('origin', 'x', 'hash');
SELECT master_create_worker_shards('origin', 2, 1);

CREATE FUNCTION the_proc(BIGINT) RETURNS BIGINT
  AS 'SELECT count($1) FROM origin WHERE x = 1;' LANGUAGE SQL;

SELECT the_proc(1);
```

fails with:

```
[master]
DETAIL:  Remote message: there is no parameter $1

[worker]
ERROR:  there is no parameter $1 at character 14
STATEMENT:  SELECT count($1) AS count FROM ONLY origin_102018 WHERE (x = 1)
```

It fails with the same error if you use a query which doesn't go through the router executor.

**Comment by marcocitus** [comment]
As a workaround, you can use PL/pgSQL:

    CREATE OR REPLACE FUNCTION the_proc(BIGINT) RETURNS BIGINT
    AS $BODY$
    DECLARE
      result BIGINT;
    BEGIN
      SELECT count($1) INTO result FROM origin WHERE x = 1;
      RETURN result;
    END;
    $BODY$ LANGUAGE plpgsql;

**Comment by anarazel** [comment]
Without using execute you'll run into similar errors after 5 executions.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by marcocitus** [comment]
True, the more robust workaround would be:

    CREATE OR REPLACE FUNCTION the_proc(BIGINT)
    RETURNS BIGINT
    AS $BODY$
    DECLARE
      result BIGINT;
    BEGIN
      EXECUTE format('SELECT count(%s) FROM origin WHERE x = 1', $1) INTO result;
      RETURN result;
    END;
    $BODY$ LANGUAGE plpgsql;

**Comment by lithp** [comment]
That's super cryptic and I can't find a reference to things like "5 executions" anywhere in google groups. What's going on?

**Comment by marcocitus** [comment]
See #306 

https://github.com/postgres/postgres/blob/ee943004466418595363d567f18c053bae407792/src/backend/utils/cache/plancache.c#L1027

**Comment by phongmh307** [comment]
This is an example query that caused error (actually the error happens to select/insert/update on any distributed after 5 executions), this is for reference:

```sql
SELECT c0."id", c0."snippet", c0."from", c0."type", c0."message_count", c0."unread_count", 
c0."seen", c0."tag", c0."is_combined", c0."is_removed", c0."last_sent_by", c0."has_phone",
c0."recent_phone_number", c0."reply_paging", c0."sync_succeed_at", c0."page_id", c0."post_id",
c0."inserted_at", c0."updated_at" FROM "conversations" AS c0 WHERE ((c0."page_id" = $1) 
AND (c0."id" = $2)) ["486846964777728", "858802540915500_859915347470886"]
```

log from `elixir-lang/ecto`
```elixir
** (exit) an exception was raised:
    ** (Postgrex.Error) ERROR (internal_error): failed to execute job 36

Failure due to failed task 2
```

logs from docker
```shell
citus_master | WARNING:  could not receive query results from pancakev2_pg_worker_1:5432
citus_master | DETAIL:  Client error: there is no parameter $1
citus_master | ERROR:  failed to execute job 36
citus_master | DETAIL:  Failure due to failed task 2
citus_master | STATEMENT:  SELECT c0."id", c0."snippet", c0."from", c0."type", c0."message_count",
c0."unread_count", c0."seen", c0."tag", c0."is_combined", c0."is_removed", c0."last_sent_by",
c0."has_phone", c0."recent_phone_number", c0."reply_paging", c0."sync_succeed_at", c0."page_id",
c0."post_id", c0."inserted_at", c0."updated_at" FROM "conversations" AS c0 WHERE 
((c0."page_id" = $1) AND (c0."id" = $2))

pg_worker_1  | ERROR:  there is no parameter $1 at character 280
pg_worker_1  | STATEMENT:  COPY (SELECT id, snippet, "from", type, message_count,
unread_count, seen, tag, is_combined, is_removed, last_sent_by, has_phone, recent_phone_number,
reply_paging, sync_succeed_at, page_id, post_id, inserted_at, updated_at FROM
conversations_102038 c0 WHERE (((page_id)::text = $1) AND ((id)::text = $2))) TO STDOUT
```

**Comment by saicitus** [comment]
Just copying comments from #789 and closing it because it seems to be a duplicate.

**Comment 1**:
Running a special test locally, with extra elog() calls, it seems that multi_planner.c receives the standard plan, but NeedsDistributedPlanning() returns false. NeedsDistributedPlanning() returns false because it only walks simple relation references to determine hasDistributedRelation. I don't know much about SQL function inlining, but pull_up_subqueries_recurse claims to do it and the test functions above seem to meet the criteria for function inlining. But the resulting Query* from the standard planner is below and it doesn't look like an inlining of the function SQL. NeedsDistributedPlanning returns false for this query, of course.

{QUERY :commandType 1 :querySource 0 :canSetTag true :utilityStmt <> :resultRelation 0 :hasAggs false :hasWindowFuncs false :hasSubLinks false :hasDistinctOn false :hasRecursive false :hasModifyingCTE false :hasForUpdate false :hasRowSecurity false :cteList <> :rtable ({RTE :alias <> :eref {ALIAS :aliasname count_rows :colnames ("a")} :rtekind 3 :functions ({RANGETBLFUNCTION :funcexpr {FUNCEXPR :funcid 16895 :funcresulttype 20 :funcretset true :funcvariadic false :funcformat 0 :funccollid 0 :inputcollid 0 :args ({CONST :consttype 23 :consttypmod -1 :constcollid 0 :constlen 4 :constbyval true :constisnull false :location 29 :constvalue 4 [ 1 0 0 0 0 0 0 0 ]}) :location 14} :funccolcount 1 :funccolnames <> :funccoltypes <> :funccoltypmods <> :funccolcollations <> :funcparams (b)}) :funcordinality false :lateral false :inh false :inFromCl true :requiredPerms 2 :checkAsUser 0 :selectedCols (b) :insertedCols (b) :updatedCols (b) :securityQuals <>}) :jointree {FROMEXPR :fromlist ({RANGETBLREF :rtindex 1}) :quals <>} :targetList ({TARGETENTRY :expr {VAR :varno 1 :varattno 1 :vartype 20 :vartypmod -1 :varcollid 0 :varlevelsup 0 :varnoold 1 :varoattno 1 :location 7} :resno 1 :resname a :ressortgroupref 0 :resorigtbl 0 :resorigcol 0 :resjunk false}) :onConflict <> :returningList <> :groupClause <> :groupingSets <> :havingQual <> :windowClause <> :distinctClause <> :sortClause <> :limitOffset <> :limitCount <> :rowMarks <> :setOperations <> :constraintDeps <>}

**Comment 2:**
There are other query types where parameterized SQL functions fail. I added list here: #306 (comment)

**Comment by marcocitus** [comment]
This seems fixed in both SQL and PL/pgSQL.
