### ISSUE TITLE
Cannot drop indexes on detached partitions

### ISSUE THREAD

**Issue by colton-trm** [citusdata/citus#5138]
If I create a partitioned distributed table with an index, detach one partition, and try to remove the index on that partition, I get the following error:

```
ERROR:  index "index_test_fix_1_col1_idx_102073" does not exist
CONTEXT:  while executing command on HOSTNAME:5432
```

My use case involves bulk loads of data into new partitions, so I need to be able to disable indexes to improve COPY times. 

Reproduction script:

```
create table index_issue (col1 int, col2 int) partition by list(col2);
create table index_issue_1 partition of index_issue for values in (1);
select create_distributed_table('index_issue','col1');
create index index_issue_idx1 on index_issue(col1);
alter table index_issue detach partition index_issue_1;
drop index index_issue_1_col1_idx;

```

Using fix_pre_citus10_partitioned_table_constraint_names as shown in this PR doesn't seem to fix this issue. 
https://github.com/citusdata/citus/pull/4410

**Comment by colton-trm** [comment]
Workaround for anyone with a similar use case. This got me ~5x better times than loading with indexes enabled, but my CPU/RAM footprint is low for my data volume. 

1. Disable indexes on all shards of the partition
```
select run_command_on_placements($$ public.index_issue_1 $$,$$update pg_index set indisready = false where indrelid = '%s'::regclass$$);
```
2. Load data
3. REINDEX partition to create and enable indexes

**Comment by hanefi** [comment]
Thanks for sharing this bug here, along with very clear steps to reproduce the issue.

#4410 fixed a problem where Citus misnamed some constraints before 10.0, and it appears that we have a similar problem with index names on partitioned tables.

For future reference, I suggest we do the following:
1. Fix the index names on newly created shards
2. Introduce a new UDF similar to `fix_pre_citus10_partitioned_table_constraint_names()` that will fix the index names on the shards that are created on earlier versions of Citus.

**Comment by naisila** [comment]
#5291 follows suggestion (2) from here
>Introduce a new UDF similar to fix_pre_citus10_partitioned_table_constraint_names() that will fix the index names on the shards that are created on earlier versions of Citus.
