### ISSUE TITLE
Implement SQL window functions for multi-shard queries that are pushdownable

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#52]
When the window function's `PARTITION BY` column and the distribution column are the same (or inclusive), we should be able to pushdown the query as-is.

We're already doing it for the window functions that are wrapped in a subquery, such as the following is supported:

```SQL
SELECT
   user_id, time, rnk
FROM
(
  SELECT
    *, rank() OVER my_win as rnk
  FROM
    events_table
    WINDOW my_win AS (PARTITION BY user_id ORDER BY time DESC)
) as foo
ORDER BY
  3 DESC, 1 DESC, 2 DESC
LIMIT
  10;
```
However, the same query where the window function is on the top as follows fail:
```SQL
SELECT *,
       rank() OVER my_win AS rnk
FROM events_table WINDOW my_win AS (PARTITION BY user_id
                                    ORDER BY TIME DESC)
ORDER BY 3 DESC,
         1 DESC,
         2 DESC
LIMIT 10;
ERROR:  could not run distributed query because the window function that is used cannot be pushed down
HINT:  Window functions are supported in two ways. Either add an equality filter on the distributed tables' partition column or use the window functions inside a subquery with a PARTITION BY clause containing the distribution column
```

Note that Citus already supports all window functions for queries that hit single node (i.e., distribution key filter on the query)
```SQL

SELECT row_number() OVER() FROM users_table WHERE user_id = 1;
 row_number 
------------
          1
          2
```

**Comment by lithp** [comment]
This came up in citus-users

**Comment by lukashes** [comment]
I did not see plans of window-functions implementation in citus-users group. This plans are exist?

**Comment by marcocitus** [comment]
Note that window functions are supported for SELECT queries that, based on filter conditions, hit a single shard, co-located shards, and/or reference tables, but not for SELECT queries that hit multiple shards.

**Comment by ssky1** [comment]
Hi,

I am trying to get this query work, but I am getting the same error  

I need to get for each row (id) a unique key distri that's why I didn't use partition by in my windowing 

select tmp.key_distri, tmp.id from (
SELECT ROW_NUMBER() OVER (ORDER BY V.id desc) AS key_distri, 
to_char(V.date,'YYYYMMDD') AS key_filter, 
 V.* FROM V 
 )tmp

this query already work on Postgres (not a distributed system) but don't work on citus, but do work on Teradata too (with is a distributed database like Citus) !

ERROR:  could not run distributed query because the window function that is used cannot be pushed down
HINT:  Window functions are supported in two ways. Either add an equality filter on the distributed tables' partition column or use the window functions inside a subquery with a PARTITION BY clause containing the distribution column

Any help,how to make this query work even writing it otherwise !

thanks

**Comment by furkansahin** [comment]
Hey @ssky1 ,
Currently the query you provide is not supported. However, you can use CTE to re-write the query as;
```
with cte_q (SELECT * FROM V)
SELECT tmp.key_distri, tmp.id from (
SELECT ROW_NUMBER() OVER (ORDER BY cte_q.id desc) AS key_distri,
to_char(cte_q.date,'YYYYMMDD') AS key_filter,
cte_q.* FROM cte_q
)tmp
```

I didn't have chance to try the query out myself but I guess it gives an idea.

**Comment by ssky1** [comment]
It works, with an "AS" between  with cte_q and (SELECT * FROM V)

thnaks furkansahin

**Comment by ssky1** [comment]
Hi Furkan Sahin ,
the problem with the clause WITH AS is that  it brings all rows to the coordinator (not the workers) because the query is not pushed down, so one it's question to do a select on a big table with millions or billions of rows, it can't hold all selected rows in the coordinator  and i get this error even when 

SQL Error [XX000]: ERROR: the intermediate result size exceeds citus.max_intermediate_result_size (currently 3145728 kB)
  Détail : Citus restricts the size of intermediate results of complex subqueries and CTEs to avoid accidentally pulling large result sets into once place.
  Indice : To run the current query, set citus.max_intermediate_result_size to a higher value or -1 to disable.

And I can't have more RAM to the workers or coordinator !

Is there a solution to push down this function to the workers ?

**Comment by furkansahin** [comment]
Hey @ssky1 ,
The limit that you are hitting is set by Citus not by the amount of memory you have. You may disable the limitation to pull all the rows to the coordinator by running;
```
SET citus.max_intermediate_result_size=-1;
```
Apparently, that may result in very poor execution times.

However, as far as I can see, you do not have any filters in your query, so, your query is scanning the whole data set, applying row_number for the full table and the end-result will have the same amount of rows as you have. Therefor, you cannot really run away from pulling the whole data to the coordinator.
Additionally, the window you define is applied in a table wide manner. Hence, the executor of the function needs to be able to see all of the rows. If we try to push it down to the workers, the row_number window will not be applied in a table wide manner but shard.

I will tag one of my colleagues from the engine team in case they have anything else to add.
@onderkalaci 

Cheers,
-Furkan

**Comment by onderkalaci** [comment]
The following query only needs  `V.id` and `V.date` 

```SQL
select tmp.key_distri, tmp.id from (
SELECT ROW_NUMBER() OVER (ORDER BY V.id desc) AS key_distri,
to_char(V.date,'YYYYMMDD') AS key_filter,
V.* FROM V
)tmp
```

So, getting only the relevant columns could help reducing the total data move (see https://github.com/citusdata/citus/issues/3118 as Citus doesn't optimize it yet)
```SQL
WITH cte_q AS (SELECT id, date FROM V) 
SELECT tmp.key_distri, tmp.id from (
SELECT ROW_NUMBER() OVER (ORDER BY cte_q.id desc) AS key_distri,
to_char(cte_q.date,'YYYYMMDD') AS key_filter,
cte_q.* FROM cte_q
)tmp
```

Also, if you do not hit `max_intermediate_result_size `, using Citus 9.2 could help as we've improved it via #3410. On Citus 9.2, Citus would execute the final query on the coordinator, meaning that it doesn't need to push the results back to a worker node and execute it on a worker as in Citus 9.1-.
