### ISSUE TITLE
select from generate_series… not supported "complex table expression"

### ISSUE THREAD

**Issue by will** [citusdata/citus#521]
It's often useful to select from generate_series then outer join in rows to bucket things by time, but also have 0s when there is no data in that bucket. Unfortunately this is not supported:

```
citus=> select count(*), v, event.name from 
generate_series(now()-'1 week'::interval, now(), '1 hour') v 
left outer join events on created_at <@ tstzrange(v, v+'1 hour'::interval) 
group by v, name;
ERROR:  cannot perform distributed planning on this query
DETAIL:  Complex table expressions are currently unsupported
Time: 78.005 ms
```

Additionally the error here "complex table expression" is _very_ close to "common table expression" which is a bit confusing

**Comment by marcocitus** [comment]
This query would be pretty hard to distribute. Because of the left join, the full generate_series output would be repeated for every shard if we simply pushed it down. Instead, we'd have to do a repartition join, though we don't currently support re-partitioned left joins. Ideally, we'd have some custom logic for generate_series to do the partitioning by argument, but we'd still have to re-partition events.

Since the series can start at arbitrary offsets, you would probably need to define a bucketing function that determines to which range an event belongs and do the left join locally.

Without offsets, it would be something like:

    create temporary table event_agg as                                                                                                           
    select count(*), date_trunc('hour', created_at) as v, events.name
    from events
    where created_at between date_trunc('hour', now() - interval '1 week') and date_trunc('hour', now())
    group by date_trunc('hour', created_at), events.name;

    select s, event_agg.name, event_agg.count
    from generate_series(date_trunc('hour', now()-'1 week'::interval), date_trunc('hour',now()), '1 hour') s
    left outer join event_agg on s = event_agg.v;
