### ISSUE TITLE
master_append_table_to_shard() UDF ignores CTRL_C

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#526]
The steps for re-produce:

``` SQL
CREATE TABLE test (a int);
CREATE TABLE test_local (a int);

COPY test_local FROM '/tmp/test_local' WITH CSV;
COPY 7254016

postgres=# select master_create_empty_shard('test');
 master_create_empty_shard 
---------------------------
                    102008
(1 row)

Time: 130.409 ms


postgres=# select master_append_table_to_shard(102008, 'test_local', 'localhost', 5432);
^CCancel request sent
^CCancel request sent
^CCancel request sent
WARNING:  cancel requests are ignored during metadata update
Time: 208411.369 ms
```

In one of our conversations @ozgune mentioned that this is intentional and a known issue. For now, I opened the issue and wanted to start a discussion to understand why Citus does this intentionally.

@sumedhpathak also asked any reason not to fix/implement this issue.

**Comment by ozgune** [comment]
@onderkalaci / @sumedhpathak -- I remember we made an intentional decision to ignore Ctrl+C commands, but I don't know if that decision is still applicable.

IIRC, our intention was to reduce the code paths where the distributed table metadata and the data on the worker nodes could be inconsistent. For example, let's say we have two worker nodes that have shard placements. If we go ahead and append to the first worker node, the user Ctrl+Cs, we check for interrupts and bail out, then the first worker node would have more data than the second one. We also wouldn't capture this relation in the distributed table's metadata.

The exact scenario could have been more complex. However, our intent was to reduce the probability of having inconsistencies between distributed metadata and worker node data.

One assumption ``master_append_table_to_shard`` made was that the master node wouldn't fail while the append operation was in progress.

**Comment by metdos** [comment]
I reproduced this. One possible solution would be to behave similarly to failure cases. If we copy to none of the shards, we don't commit individual rows. If we copy to one shard but not others, we mark others as inactive.

**Comment by marcocitus** [comment]
master_append_table_to_shard can be cancelled as of 6.1
