### ISSUE TITLE
Server errors out after using generate_series() to generate series of string

### ISSUE THREAD

**Issue by kotsachin** [citusdata/citus#533]
Hi,

I am trying to install and test citus v5.1.0-rc.2 and PostgreSQL 9.4.7 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-4), 64-bit

I am getting following error:

---

=# insert into test2 values(generate_series(10,100));
TRAP: FailedAssertion("!(((((const Node*)(targetEntry->expr))->type) == T_Const))", File: "planner/multi_router_planner.c", Line: 738)
server closed the connection unexpectedly
    This probably means the server terminated abnormally
    before or while processing the request.
The connection to the server was lost. Attempting reset: LOG:  server process (PID 3607) was terminated by signal 6: Aborted
DETAIL:  Failed process was running: insert into test2 values(generate_series(10,100));

---

Please let me know why it why it is happening and is there fix for this?

regards,
Sachin

**Comment by mtuncer** [comment]
This happens when we are retrieving the value of partition column to determine the target shard interval.

Call stack is
MultiRouterPlanCreate()->RouterModifyTask()->TargetShardInterval()->ExtractInsertPartitionValue()

We expect a constant value for partition column during insert operation to determine the target shard. 

A work around is to provide a constant value for partition column. Above query can be written as
```insert into test2 values (10, generate_series(20, 100));``` assuming partition column is the first column.

We should return an error here instead of asserting.

**Comment by ozgune** [comment]
@mtuncer / @lithp -- Once we merge in #488, could we check if it also resolves this issue?

**Comment by lfittl** [comment]
@ozgune Since I've just been doing some testing on master: 

First of all, this doesn't crash the backend anymore, so thats good.

Example schema:

```
postgres=# \d test2
      Table "public.test2"
  Column  |  Type   | Modifiers 
----------+---------+-----------
 id       | integer | 
 position | integer | 
```

Inserting into the partition column doesn't work (intentional, see `Non-constant partition columns are not allowed, the planner must be able to route a query.
` in https://github.com/citusdata/citus/pull/488), but errors out cleanly:

```
postgres=# insert into test2 (id) values(generate_series(10,100));
ERROR:  values given for the partition column must be constants or constant expressions
```

Inserting with a constant value for the partition column, and the generate_series on a non-partition column works:

```
postgres=#  insert into test2 (id, position) values(10, generate_series(10,100));
INSERT 0 91
```

So my suggestion is we close this issue, since its fixed in 5.2.

**Comment by anarazel** [comment]
On 2016-07-15 16:15:20 -0700, Lukas Fittl wrote:
> Inserting with a constant value for the partition column, and the generate_series on a non-partition column works:
> 
> ```
> postgres=#  insert into test2 (id, position) values(10, generate_series(10,100));
> INSERT 0 91
> ```

I'm pretty sure that's actually breaks column defaults / sequences...

**Comment by lfittl** [comment]
@anarazel Yeah, it errors out, which maybe is ok?

```
postgres=# CREATE TABLE test3 (id uuid DEFAULT uuid_generate_v4() NOT NULL, customer_id integer, position integer);
postgres=# SELECT master_create_distributed_table('test3', 'customer_id', 'hash');
postgres=# SELECT master_create_worker_shards('test3', 16, 1);
```

```
postgres=# insert into test3 (customer_id, position) values(10, generate_series(10,100)) RETURNING id, customer_id;
ERROR:  set-valued function called in context that cannot accept a set
postgres=# insert into test3 (id, customer_id, position) values(uuid_generate_v4(), 10, generate_series(10,100)) RETURNING id, customer_id;
ERROR:  set-valued function called in context that cannot accept a set
```
```
postgres=# insert into test3 (customer_id, position) values(10, 10) RETURNING id, customer_id;
                  id                  | customer_id 
--------------------------------------+-------------
 ac47ff13-3571-4e0a-8b72-9499db5197b9 |          10
(1 row)

INSERT 0 1
```
```
postgres=# insert into test3 (id, customer_id, position) values('ac47ff13-3571-4e0a-8b72-9499db5197b9', 10, generate_series(10,100)) RETURNING id, customer_id;
                  id                  | customer_id 
--------------------------------------+-------------
 ac47ff13-3571-4e0a-8b72-9499db5197b9 |          10
 ac47ff13-3571-4e0a-8b72-9499db5197b9 |          10
...
```

**Comment by anarazel** [comment]
On 2016-07-15 16:27:32 -0700, Lukas Fittl wrote:
> @anarazel Yeah, it errors out, which maybe is ok?

Ah, perfect. I was afraid we'd end up with the same sequence value in
all of the rows.

**Comment by marcocitus** [comment]
> insert into test2 values(generate_series(10,100));

this gives an error in Postgres, but `insert into test2 select * from generate_series(1,100)` is supported in Citus
