### ISSUE TITLE
Unify Modify Logics

### ISSUE THREAD

**Issue by aamederen** [citusdata/citus#558]
Citus has several parts that modify(INSERT/UPDATE/DELETE) data in shards:
- Plain INSERT/UPDATE/DELETE queries: Router Planner/Executor
- COPY FROM
- master_apply_delete_command
- master_modify_multiple_shards
- (?) multi insert

We may need to step back and unify them.

**Comment by marcocitus** [comment]
What does unifying mean? I think there may be several separate issues here.

One thing that comes to mind is integrating the master_apply_delete_command logic into master_modify_multiple_shards. If someone runs SELECT master_modify_multiple_shards('DELETE FROM events WHERE event_time < ''2016-01-01'' ') and events is append-partitioned, then we could send a drop command instead of a delete for shards that fall completely within the filters. A slight downside is that this takes an exclusive lock on the shard placement, which could block multi-shard SELECT queries unless they filter out those shards.

Another thing that comes to mind is having regular DELETE/UPDATE commands that touch multiple shards go through the modify_multiple_shards logic. This will probably conflict with the RETURNING logic a bit. We should also find a good way to communicate the transactional semantics and make some decisions around the future of the replication model, e.g. do we still need logic to mark placements as inactive. Before diving too deeply into 2PC land, it might also be worthwhile investing in automatic recovery.

**Comment by ozgune** [comment]
@aamederen / @marcocitus -- is this issue covered by the transaction unification work that we're doing in #704?

**Comment by anarazel** [comment]
@aamederen Ping?

**Comment by marcocitus** [comment]
I think there is yet more we can do, but the issue description is not specific enough to determine whether or not it's covered. Closing it in favour of actionable issues such as #873.
