### ISSUE TITLE
Error Cannot open new connections after the first modification command within a transaction (Based on #5501). 

### ISSUE THREAD

**Issue by Mileev2008** [citusdata/citus#5658]
Dear colleagues, good afternoon!
Earlier, we registered a request https://github.com/citusdata/citus/issues/5501.
We have updated Citus to the current version 10.2.3:

   PostgreSQL 13.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1), 64-bit
   Citus 10.2.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4), 64-bit

Unfortunately, the restriction remains. 
Can you tell me if it is planned to support this transaction block in the next versions ? If so, when?
Thank you for your help!

**Comment by Mileev2008** [comment]
Good morning. 
I would be grateful for any information on my question. 
Thanks.

**Comment by Sahismail** [comment]
😡 500$ kzybim oldu lütfen daha dikkatli yapalım

**Comment by onderkalaci** [comment]
hi @Mileev2008,

I think I confused you with my early comment [here](https://github.com/citusdata/citus/issues/5501#issuecomment-984467330). What I meant was the fix is going to be in the next Citus release, which is Citus 11. Not with the current release Citus 10.2. Sorry for the confusion.

But, there is an important gotcha here about the answer to your specific question, which you have not answered yet. Citus throws that error for several different cases. The most common case we hear from the users is [these](https://github.com/citusdata/citus/issues/5501#issuecomment-984467330) kinds of transaction blocks where a `SELECT` is followed by a modification.  

Citus 11 will resolve errors for these kinds of transaction blocks. So:

(a) Please verify that you get the errors because of such transaction blocks. If your application gets the errors because of other complex transaction patterns, it might not be resolved in Citus 11. 
(b) Until Citus 11 is released, try to break such transaction blocks (e.g., if possible do not run those `SELECT` queries in the transaction, such as:
```SQL
SELECT ....
BEGIN;
   INSERT ..
    INSERT...
    ...
COMMIT;
```

**Comment by Mileev2008** [comment]
Good afternoon @onderkalaci !
Thank you for your prompt and detailed response. 
In our case, we definitely get an error due to just such a transactional block. 
We will try to implement your proposal to split the block and wait for the release of version 11. 
Please specify the release dates of version 11?
Thanks.

**Comment by metdos** [comment]
The release date is not certain yet. Linked to #5400.

**Comment by Mileev2008** [comment]
Good afternoon. 
I understand, thanks for the information. 
We will be waiting for an update. 
The request can be closed.
