### ISSUE TITLE
Feature request: json_agg support

### ISSUE THREAD

**Issue by rickyspeak** [citusdata/citus#571]
postgres=# select json_agg(event) from events group by (uid);
ERROR:  unsupported aggregate function json_agg

For our data model this feature is pretty critical. I hope this is a pretty easy to implement.

Edit:  Forgot to mention that the shards are hash distributed on uid.  Though I doubt that matters very much for this issue.

**Comment by ozgune** [comment]
@rickyspeak -- thanks for getting in touch with us. We'll look into the details of ``json_agg`` and will post an update in a few days.

Could you elaborate a bit more on your use-case? If you have an example table schema, could you share that with us too?

**Comment by rickyspeak** [comment]
Thanks for getting back to me @ozgune .  We are exploring moving away from MongoDB to Postgres and the Citus sharding support is a major contributor there.  Our use-case is that we have event data in json format.  New events types with unknown fields can be added by end users, so our tables will primarily be a jsonb.  Events are coded by a uid and we want to query against many events that share the same uid and then return the collections of events that meet our query conditions. The table will just be these two columns.  Hash sharding on the uid column. With a GIN index on the event column.

For example:
uid | event
---------------
'1' | '{"a":1}'
'2' | '{'"a":1}'
'2' | '{"b":3}'

We would like to query for a uid that matches {"a":1} AND {"b":3}.  In order to do this query we'll select a good condition like {"a":1} query on that.  json_agg(event) on all the returned uid.  And then filter on the full condition {"a":1} AND {"b":3}.  Something like:
SELECT result FROM (
  SELECT json_agg(my_events.event) as result 
  FROM (
    (SELECT uid FROM my_events WHERE event @> '{"a":1}') as uids 
    LEFT JOIN my_events 
    ON my_events.uid = uids.uid 
    GROUP BY uids.uid
  )
) as intermediate
WHERE result @> '[{"a":1}]' AND  result @> '[{"b":3}]'

I'm sure there is a typo in there somewhere, but that is the gist.

At the innermost layer ideally we'd like to do multiple SELECT's on the shard key column (uid) and perform an INTERSECT on this value that is performed on the shard.

We will be exploring UPSERT models which would negate this issue, but our ingestion rate is on the order of 20-50k events per second and we've found ingestion to be a major issue and would rather stick with an INSERT only data model.

**Comment by marcocitus** [comment]
Thanks for sharing the details of your use-case. The upsert model is indeed likely to lead to ingestion issues because it typically requires a lock on the key, which means your throughput for a given key can never be more than 1/query time.

Citus has subtle restrictions around subqueries, but you should be able to run your query with jsonb_agg like this:

    SET citus.subquery_pushdown TO on;
    SELECT events AS result FROM 
      (SELECT jsonb_agg(my_events.event) AS events FROM 
        (SELECT uid FROM my_events WHERE event @> '{"a":1}') as uids 
        LEFT JOIN 
        (SELECT * FROM my_events) my_events
        ON my_events.uid = uids.uid
        GROUP BY uids.uid
      ) as intermediate
      WHERE events @> '[{"a":1}]' AND events @> '[{"b":3}]';

You want to make sure that you use jsonb in the function names, otherwise you'd first cast (deparse) to the json type and then back, which is much slower.

**Comment by marcocitus** [comment]
For completeness, a few notes on json_agg/jsonb_agg.

There is a distinction between having an aggregate in the outer query, which requires aggregate results from several shards to be merged, and having it in a subquery that can be pushed down to a shard and does not require any merging. In the former case, we need to explicitly implement merging logic and we currently do this for avg, min, max, sum, count, array_agg. In the latter case, any aggregate can be supported.

I ran into the lack of jsonb_agg support when I was writing: https://www.citusdata.com/blog/14-marco/410-scalable-real-time-product-search-using-citus . I ended up using to_json(array_agg(...)) as a workaround.

It seems that the code change for adding jsonb_agg to outer queries is relatively small. I added it on another branch: https://github.com/citusdata/citus/tree/feature/json_agg . It currently only supports jsonb_agg and not json_agg, which would require a little more work because postgres does not have a built-in concatenation function for the json type.

**Comment by rickyspeak** [comment]
@marcocitus I totally understand.  My major need is to push the jsonb_agg down to the worker.  We aren't concerned about aggregating between shards in this use case.

**Comment by rickyspeak** [comment]
@marcocitus Got it working and my query is doing what it's supposed to.  I did notice that citus--5.1-2--5.1-3.sql  is missing from the branch.

**Comment by lithp** [comment]
Dropping a comment to link this to #120, which would fix this without requiring a subquery.

**Comment by ozgune** [comment]
@rickyspeak -- We're currently doing our product planning and I had a quick question about your use-case. This is in addition to @marcocitus and @lithp's notes.

You mentioned that you ingested 20-50K events/sec and that was one of the reasons for choosing ``INSERT`` over ``UPSERT``. We heard of a similar pattern multiple times before and tried to capture this in #509. If we had native support for #509, would you have considered using it?

For example, let's say you created two distributed tables, ``uid-event-raw`` and ``uid-event-upserted``. Both tables are hash distributed on ``uid`` and their shards are therefore co-located on the same machine. You'd insert raw events into ``uid-event-raw``, and roll them up through #509 or a trigger into ``uid-event-upserted``. What do you think?

**Comment by rickyspeak** [comment]
@ozgune That is definitely a use case we have explored.  The goal here was to explore the efficiency of doing joins on the fly for our data set which might be less of a total burden on our server.  Our use case is one where any given record might never be looked at, but we don't know at insert time which ones will be important.  It's not clear if preprocessing the whole database is a net negative or a net positive.

More aggressive sharding and prepocessing using batch upserts could be an option.

**Comment by ozgune** [comment]
@rickyspeak -- thanks a bunch for your input. I know @lithp will also find this conversation interesting.

For similar workloads, we usually see three different methods of data ingest. Which of the following resonates with you the most?

1. Creating an uid-event-raw table that's distributed on ``uid``. Then, running join queries on the fly.
2. Creating an uid-event-upserted table that's distributed on ``uid``. Then, UPSERTing each event into this table. (if we assume that Citus delivered on throughput)
3. Creating two distributed tables, uid-event-raw and uid-event-upserted. Both are distributed on ``uid``. Then inserting into uid-event-raw and rolling up from uid-event-upserted

Also, if Citus documented an easy way to expire and/or compress old events data, would that change your preferred method of data ingest?

**Comment by ozgune** [comment]
Hi @marcocitus, we now have support for json / jsonb aggregate functions with #2015. What's the difference between having the json aggregate function in the outer vs inner query?

@metdos / @rickyspeak -- Could we test if Citus 7.3 support the example query in this issue? If it does, could we close the issue?

**Comment by rickyspeak** [comment]
I'm no longer setup to test this. Regardless, I'm fine with closing the issue.
