### ISSUE TITLE
Support PREPARE statements with parameters: Non-distribution column

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#572]
When making Citus an extension, we temporarily removed support for `PREPARE` statements with parameters, where the prepare statement runs for more than five times and has a cheaper plan.

We're tracking adding support for `PREPARE` statements in #306. We decided to break up that issue into two: (1) `prepare` statements with parameters on the distribution column and (2) `prepare` statements with parameters on the non-distribution column.

We're tracking `prepare` statements with parameters on the non-distribution column in this issue.

When we start working on this, we should also look into how users' drivers are running `PREPARE`. @a-bro, if you have a few example queries, could you post them here?

**Comment by metdos** [comment]
One solution is to use PQsendQueryParams() instead of PQsendQuery(), and to send query parameters to worker nodes in the executor. The problem with this approach is that we wrap select queries within a COPY command in real-time and task-tracker executors, and COPY command is not a parametrizable query type. We can still use this approach for router executor because we don't wrap queries with a COPY statement there.

We intend to remove the use of temporary tables in real-time executor with the issue #372. If we also stop wrapping queries with COPY, we can also parameterize worker queries for the real-time executor.

@anarazel proposed an alternative approach for the time being but he also noted that this be would less advantageous for architectural and performance reasons. Here are the related parts of emails;

Whenever parameters are set, re-parse the query, replace all PARAM_EXTERN
node with constants using a expression_tree_mutator, and deparse it again.
Would have the advantage of also supporting params on partition clauses.

I've spent a run thinking about this. It's unfortunately not entirely as
trivial as that.  The problem with the simplistic approach is that
pg_get_query_def() expects a analyzed/transformed query - but after
replacing the shard-id we can't do that anymore, because parse-analysis
would error out due to the non-existant tables.

The better approach is to simply delay deparsing of the query until
execution, i.e. store the query, not the queryString in struct Task
(except for the things that are plain queries).  I've very quickly
(noticeable by the variable name ;)) prototyped that in the attached
patch.

To support parametrized plans ontop of this, we'll need to do an
query_tree_mutator()/expression_tree_mutator() run that'd iterate over
the plan, replacing all Param (w/ paramkind == PARAM_EXTERN) nodes with
a Const node, containing the appropriate value from
QueryDesc->params. That should be fairly easy, you can pretty easily
adapt the code from postgres' ExecEvalParamExtern(), and call
makeConst() on the result.

As far as I can see, the only step after that would be (if we want to
support that), to move part of the work in MapTaskList() to
task_tracker_executor.c, so we can use the query string without
parameters when sending it to the worker.

**Comment by metdos** [comment]
As following the discussions above, we followed the approach-1 and fixed the router executor part with PR #651. But, we still have the problem for real-time and task-tracker executors. Therefore, I'm keeping this issue open, and removing the 5.2 Release tag.

**Comment by anarazel** [comment]
@ozgune @sumedhpathak I think we can close this issue for now? We're going further than this via other issues?

**Comment by sumedhpathak** [comment]
@anarazel I presume we now support this? If so we can close it. Worth linking our top-level prepare tracking issue before closing though.

**Comment by marcocitus** [comment]
Remaining items tracked in #1179
