### ISSUE TITLE
ALTER TEXT SEARCH fails with CaseInsensitive = 1 argument

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#5829]
From `make installcheck`:
```
CREATE TEXT SEARCH DICTIONARY synonym (
                        Template=synonym,
                        Synonyms=synonym_sample
);
ALTER TEXT SEARCH DICTIONARY synonym (CaseSensitive = 1);
ERROR:  unexpected argument during deparsing of TEXT SEARCH DICTIONARY definition
```

**Comment by hanefi** [comment]
This error is due to a limitation in one of our helper functions. I will extend that function to allow integers and all other allowed text search dictionary option value types.

https://github.com/citusdata/citus/blob/c18c63a930268e40f454ed2c51efe78d71f3371b/src/backend/distributed/deparser/deparse_text_search.c#L77-L86
