### ISSUE TITLE
Managed citus on google cloud sql

### ISSUE THREAD

**Issue by maingoh** [citusdata/citus#6134]
Is there any plan to provide a fully managed citus on other clouds, especially on GCP ?

**Comment by mulander** [comment]
Hi @maingoh,
I am the product manager for the Citus engine here at @Microsoft. We have seen great growth of Hyperscale (Citus) since it was released in 2019 and continue highly active development of the product to keep up with the growing demand. We do not have immediate plans to invest in bringing Citus technology as a managed service to other clouds. However, we keep following our customers' needs as far as managed distributed Postgres service is concerned. Citus is open source, and you are of course welcome to host it yourself on whatever platform you prefer, and you can count on our help if you ever decide to migrate your workload to the Azure managed service.
