### ISSUE TITLE
Explain Analyze makes a distributed query go much slower

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#621]
When the user runs a distributed query in Citus, Citus breaks up the query into query fragments and executes those query fragments in parallel.

Running `EXPLAIN ANALYZE` on a distributed query changes that behavior by running query fragments in serial. This significantly increases the distributed query's runtime. The behavior also diverges from the one users are accustomed to with Postgres. We're documenting this behavior in https://github.com/citusdata/citus_docs/issues/69.

In a meeting yesterday, we also talked about adding a `WARNING` or `NOTICE` message to immediately inform the user of this change in behavior. I'm opening this issue to add a log message to the `EXPLAIN ANALYZE` output.

@samay-sharma and @anarazel -- if you have additional feedback, could you comment on this issue?

**Comment by marcocitus** [comment]
Minor note: this mainly applies when explain_all_tasks is on, otherwise only one task is executed serially.

**Comment by lfittl** [comment]
@marcocitus Practically speaking, when I want to understand the performance of a query - why wouldn't I want to see all tasks?

Otherwise there is no guarantee that depending on the distribution of the data, one task might be much slower or much faster than the other ones, correct? (i.e. we choose a random task to show, as I understand it)

**Comment by marcocitus** [comment]
>  why wouldn't I want to see all tasks?

@lfittl you might not be a computer ;). explain_all_tasks shows a lot of information and it doesn't necessarily get more useful than a single task, since the query plan will rarely vary. Moreover, it might swamp your terminal since there can be thousands of task. This is purely usability-related, for an external tool you would probably always want to get all the information.

A minor advantage of serially executing the tasks (at least per worker) is that the execution time is more representative of the amount of work being done for that task and not a result of resource contention between tasks. I think faster explain analyze is more valuable, but wanted to note this.

It's not very hard to do simple parallelization using PQsendQuery, though there are some concerns like throttling and the execution overhead and thus resource contention not being the same as when you run the query. There might be a case for "analyze light", which shows you the real execution times of tasks gathered during execution, but not the explain analyze plans of each task.

**Comment by ozgune** [comment]
@lfittl, @marcocitus -- I had two notes and a question on this issue.

(1) At the time, when we surveyed people on ``EXPLAIN ANALYZE``, they mentioned that they wanted to see the slowest task.

(2) @samay-sharma and @anarazel brought up adding a ``NOTICE`` or ``WARNING`` message --  particularly when ``citus.explain_all_tasks`` is enabled. What do you think about this proposal?

(3) I'm personally a bit split on the ``citus.explain_all_tasks`` flag for the following reasons.

The benefit to having this flag is that the user can visualize each task's execution time and see if there are any outliers. 

Potential usability drawbacks to enabling this flag it could be:
* When the user runs EXPLAIN ANALYZE, they are likely investigating a performance problem. By enabling this flag, they are making any performance issues much worse.
* Postgres' ``EXPLAIN ANALYZE`` performance characteristics are inconsistent with that of Citus'.
* When we run these tasks serially, tasks' performance characteristics could be different than running them concurrently.

**Comment by lfittl** [comment]
@ozgune 

Re: (1) That seems reasonable, and is also why I think that its important we inform users that we show one of the tasks (presumably from the first shard in the list?), rather than the slowest one.

Re: (2) Maybe we should have notice messages for both execution modes - i.e. with explain_all_tasks=1 we tell you that its being run synchronously, and with explain_all_tasks=0 we tell you that it only shows the first task and you need to use "explain_all_tasks=1" to see all of them.

Re: (3) I think its reasonable to default to explain_all_tasks=0, if we have a NOTICE and/or very visible documentation explaining how EXPLAIN ANALYZE works with Citus.

**Comment by anarazel** [comment]
On 2016-07-07 13:15:56 -0700, Ozgun Erdogan wrote:
> * When the user runs EXPLAIN ANALYZE, they are likely investigating a performance problem. By enabling this flag, they are making any performance issues much worse.

It's not like that flag makes the actual performance problem worse, it
just make the investigation slower...

**Comment by jmehnle** [comment]
Is distributed `EXPLAIN ANALYZE` still sequential? If not, what Citus release made it parallel?

**Comment by seamusabshere** [comment]
hey @marcocitus ^^ can we make `EXPLAIN ANALYZE` parallel in 2019?

**Comment by pykello** [comment]
hey @seamusabshere probably in 2020 :) https://github.com/citusdata/citus/pull/3833
