### ISSUE TITLE
\d+ shows incorrect table size

### ISSUE THREAD

**Issue by craigkerstiens** [citusdata/citus#631]
\d+ shows a distributed table as essentially having no data. While you can reason about why, from a user experience stand point it's still confusing.

**Comment by lithp** [comment]
\dt+ calls `pg_catalog.pg_table_size()`, which looks at the size of the files on disk and gives us no opportunity to hook in. To fix this we'd have to replace `pg_table_size` with our own function.

The new pg_table_size calls the original when called on a non-distributed table. When called on a distributed table it runs a query on each of the workers to run pg_table_size on each shard. Not trivial but not difficult.

I think we should call the workers and incur round-trip delays but it's also possible to read from shardlength.

**Comment by saicitus** [comment]
+1
Came up in a prospect engagement. Wanted to check if the \COPY succeeded.
On a more generic note, supporting size functions for relations/indexes is for sure a nice to have feature.

**Comment by lithp** [comment]
An easy first step is to replace pg_table_size with a function which returns an error if you query a distributed table, so you at least aren't given. It could even give some advice on how to determine the size yourself?

**Comment by marcocitus** [comment]
Workaround:
```
CREATE OR REPLACE FUNCTION citus_table_size(table_name regclass)
RETURNS bigint LANGUAGE plpgsql
AS $function$
DECLARE
        table_size bigint;
BEGIN
        PERFORM master_update_shard_statistics(shardid)
        FROM pg_dist_shard
        WHERE logicalrelid = table_name;

        SELECT sum(shard_size) INTO table_size
        FROM (
                SELECT min(shardlength) AS shard_size
                FROM pg_dist_shard JOIN pg_dist_shard_placement USING (shardid)
                WHERE logicalrelid = table_name
                GROUP BY shardid
        ) shard_sizes;

        RETURN table_size;
END;
$function$;

SELECT logicalrelid, pg_size_pretty(citus_table_size(logicalrelid)) FROM pg_dist_partition;
```

**Comment by saicitus** [comment]
@begriffs and @sumedhpathak May be add the above in the list of workarounds on docs. It doesn't come up too frequently, but it did come up 2-3 times in the SE process for prospects.It might not be too important, but would still be handy and useful content on the docs.

**Comment by lithp** [comment]
This just came up again in citus-users

**Comment by francisco1844** [comment]
+1 for \dt+ or some other way to get info.. which gets done as part of the install.
Perhaps have a .sql file that loads commonly used functions.

**Comment by ozgune** [comment]
We talked about this and decided to add a new Citus user-defined function (UDF) that returns the size of distributed tables.

**Comment by lithp** [comment]
@ozgune Why not replace `pg_table_size` with our own? That way users won't need to re-learn how to query table size.

**Comment by ozgune** [comment]
@lithp -- IIRC, we talked about replacing ``pg_table_size`` with our own function and decided that the effort involved of doing this right didn't justify the benefit.

We therefore decided to go with adding new user-defined functions.

**Comment by lithp** [comment]
The benefit definitely justifies the effort because I did it today in 2
hours, there's a branch in the repo with it already done :)
https://github.com/citusdata/citus/commit/c2ae9e1526d9cf1dedfa30912f19fe70d83300b7

But I talked with Andres and he's convinced me that the world is dumb and
it's not a good idea to replace pg_table_size, advanced users might be
using monitoring tools which rely on knowing the local disk space used by
each node and they use functions like pg_table_size for that.

**Comment by jasonmp85** [comment]
But… why not a GUC to opt-out (or -in) to the overridden behavior 😈?

**Comment by lithp** [comment]
Yeah, making it opt-out sounds nice. That satisfies every constraint I've been told exists but maybe someone else should write it, I don't want to draw any more of Andres' ire :smirk:

**Comment by marcocitus** [comment]
If we have a citus_table_size function and it also handles regular tables, then users could opt-in by running CREATE OR REPLACE pg_catalog.pg_table_size... with citus_table_size as the C implementation.

I don't think we should do this by default. Apart from introducing failure scenarios and timeouts in a critical system administration function, replacing pg_catalog functions in an extension is unlikely to place nicely with pg_upgrade, while replacing calls in the planner hook adds unnecessary overhead to every PostgreSQL query (and is a bit of a slippery slope).

**Comment by lithp** [comment]
I don't think CREATE OR REPLACE is a good idea because the function
disappears once you DROP EXTENSION and it's going to be very hard to
remember you did the REPLACE. I'm also not sure how you could recreate the
original function.

You're right that this would require more care when writing
citus_table_size, you'd definitely need a timeout! And to support \d+ you
probably don't want to wait for that timeout for each table while you're in
the same statement. But I think that's surmountable.

I'll admit I haven't profiled but I'd be very surprised if this added
noticeable overhead. You're walking the query once, where PG already
doesn't just walk but copies the tree quite a few times: "parsed ->
analyzed -> path -> plan -> execution state". This is indeed a slippery
slope, and if there were a harder way which also worked I'd say we should
do that. But if we replace pg_table_size at all I think this is the route
with the least gotchas.

**Comment by lithp** [comment]
Backing up a bit, I'm not going to argue too hard because it seems everyone disagrees with me and replacing something so core is indeed dangerous. I'm okay with us not replacing by default, or even with us not replacing. But I'm also a little confused.

Just a few weeks ago I was talked to about how the fancy distributed systems stuff isn't a priority because most users don't come to Citus expecting multi-shard UPDATEs to be super fast, they instead expect multi-shard UPDATES to work at all and are surprised when they receive an error message. That leaves a bad impression of Citus. Anything which makes the early experience nicer is important because it keeps new users engaged long enough to start becoming interested in the more complicated parts, or so I was told.

This seems like /exactly that/. Someone who is trying out citus runs `\d+` and is confused. We don't even give them a warning, we just give them the wrong answer. If we make `pg_table_size` "just work" for the new user, that makes their early experience better and can only be good news for Citus.

And from where I'm sitting, I don't see how doing this is significantly harder than writing `citus_table_size`. Yes, we have to be careful about timeouts. But, we should always be careful about timeouts?

**Comment by lfittl** [comment]
@lithp I'll add a quick note on the multi-shard UPDATE vs \d:

Multi-shard UPDATEs are part of making your application work with Citus, and one of the issues we see users run into where the app development team has to spend time fixing them (e.g. by including the tenant_id), and modifying their ORM since they don't write SQL directly.

\d is more of a maintenance / "How is my database doing?" thing, and afaik rarely part of anything thats called from an application or ORM.

That said, I wish there was away to make this work, but I don't think its something important enough to warrant breaking pg_upgrade and other scenarios. If we can add something to our docs that says, "devops person, please run this UDF" that should be fine.

**Comment by marcocitus** [comment]
> I don't think CREATE OR REPLACE is a good idea because the function disappears once you DROP EXTENSION

Yep, it would cascade to the re-defined pg_table_size function. On the other hand, the extension is never dropped on say, cloud, so if they really want \d+ to show distributed table sizes...

(btw, didn't mean to use OR REPLACE there. You can just CREATE FUNCTION pg_catalog.pg_table_size after renaming the old function.)

> But if we replace pg_table_size at all I think this is the route with the least gotchas.

What if we just provide some meaningful view that gives you the size of distributed tables?

> If we make pg_table_size "just work" for the new user, that makes their early experience better and can only be good news for Citus.

The objections come from the fact that we're not changing Citus behaviour, but rather changing  PostgreSQL behaviour and then there are a lot of different expectations and experiences that we don't know about or control and things that may break as a result. For example, is a 5 second connection timeout (or a multiple of that) in \d+ when a worker is temporarily unreachable / failing over something a user expects? Or would the user Ctrl+C and feel like we broke their database? What if monitoring tools time out due to failures in pg_table_size and throw unexpected errors? What if the disk usage adds up to more than the size of the disks? What if create_distributed_table loads data, but we no longer show the size on disk? etc.

**Comment by velioglu** [comment]
Since some users care about only the table size while others care about the disk space, two different UDFs will be implemented. 

- citus_table_size(relation_name text) : Returning the size of relation without including replicas of each shard. Goal of that UDF is informing the user about how much data will be handled for any query run over it.

- citus_total_relation_size(relation_name text) : That UDF include the size of all replicas and indices. Goal of that UDF is informing user about how much space is used for that relation on the disk. 

Neither of these UDFs will update the pg_dist_shard_placement table. Although updating the table make the system more consistent, it will cause a time delay. By the way, inconsistency between \d and the result of these UDFs is still there.

If master can not connect to any of the worker, it will try to estimate the size of shards using replications of the same shard on different nodes (by giving a warning). If there is only one replication for a given shard or the master can not connect to any of the node holding a given shard UDF will give an error.

You can find the design document on https://docs.google.com/a/citusdata.com/document/d/1sY0c5hAx4uOpQJi2vGXym8Ir4Il-WWNbITZOWS_7tnE/edit?usp=sharing .

**Comment by metdos** [comment]
> Neither of these UDFs will update the pg_dist_shard_placement table. Although updating the table make the system more consistent, it will cause a time delay. By the way, inconsistency between \d and the result of these UDFs is still there.

@velioglu, do you plan to call master_update_shard_statistics()? If yes, updating metadata in pg_dist_shard_placement would take negligible amount of time compared to master_update_shard_statistics().

**Comment by metdos** [comment]
> Since some users care about only the table size while others care about the disk space, two different UDFs will be implemented.
> 
> citus_table_size(relation_name text) : Returning the size of relation without including replicas of each shard. Goal of that UDF is informing the user about how much data will be handled for any query run over it.
> 
> citus_total_relation_size(relation_name text) : That UDF include the size of all replicas and indices. Goal of that UDF is informing user about how much space is used for that relation on the disk.

@ozgune, are you OK with this API?

**Comment by anarazel** [comment]
I think it should be citus_relation_size not table size, and it should work when invoked on indexes of distributed tables. Knowing the size of individual indexes is operationally pretty important.   This also would mirror the known postgres functions more closely.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by velioglu** [comment]
> @velioglu, do you plan to call master_update_shard_statistics()? 
@metdos  No, I don't plan to call it.

**Comment by marcocitus** [comment]
> I think it should be citus_relation_size not table size, and it should work when invoked on indexes of distributed tables. 

Maybe both?

**Comment by anarazel** [comment]
On 2017-02-27 08:29:44 -0800, Marco Slot wrote:
> > I think it should be citus_relation_size not table size, and it should work when invoked on indexes of distributed tables. 
> 
> Maybe both?

WFM. For reference, these are the size related functions in postgres
proper:

```
                                   List of functions
   Schema   |          Name          | Result data type | Argument data types |  Type
------------+------------------------+------------------+---------------------+--------
 pg_catalog | pg_column_size         | integer          | "any"               | normal
 pg_catalog | pg_database_size       | bigint           | name                | normal
 pg_catalog | pg_database_size       | bigint           | oid                 | normal
 pg_catalog | pg_indexes_size        | bigint           | regclass            | normal
 pg_catalog | pg_relation_size       | bigint           | regclass            | normal
 pg_catalog | pg_relation_size       | bigint           | regclass, text      | normal
 pg_catalog | pg_size_bytes          | bigint           | text                | normal
 pg_catalog | pg_size_pretty         | text             | bigint              | normal
 pg_catalog | pg_size_pretty         | text             | numeric             | normal
 pg_catalog | pg_table_size          | bigint           | regclass            | normal
 pg_catalog | pg_tablespace_size     | bigint           | name                | normal
 pg_catalog | pg_tablespace_size     | bigint           | oid                 | normal
 pg_catalog | pg_total_relation_size | bigint           | regclass            | normal
(13 rows)
```

pg_column_size, pg_size_bytes, pg_size_pretty don't need any adaption to
work with citus.  pg_tablespace_size is probably uninteresting for now,
given our tablespace support.  But the rest probably makes sense?

**Comment by ozgune** [comment]
@velioglu / @metdos / @anarazel -- We prioritized this issue as a quick fix. From a requirements standpoint, I think we must at least hit (1).

1. citus_total_relation_size(relation_name): (a) This function returns a distributed table and its indexes' total relation size. (b) The function only works with streaming replication and adds up total sizes on primary nodes. (c) If the function can't connect to a node, it errors out.

2. citus_table_size(relation_name): (a) This function returns a distributed table's total relation size. (b) and (c) are the same.

The following are good to haves, but we don't need to hit them in this cycle.

3. citus_relation_size(relation_name): (a) This function returns a relation's 'main' fork's size. A relation can be the name of a table or an index. (b) and (c) are the same.

4. We remove any restrictions associated with (b) or (c).

**Comment by velioglu** [comment]
While discussing the implementation of these UDFs with @onderkalaci, he reminded me reference tables. Although they are not streaming replicated tables, calculating their sizes with these UDFs makes the implementation more useful. 

Since each node holds the same data for each reference table, I'm planning to calculate result of all 3 UDFs by finding the value of related UDF for one of the node and multiplying it by the node count. Functions error out only if they can not connect to any node.

Does this implementation make sense for reference tables ?

**Comment by ozgune** [comment]
@velioglu -- This approach for reference tables works.

I had two clarification questions.

* When you say "I'm planning to calculate result of all 3 UDFs by finding the value of related UDF for one of the node and multiplying it by the node count.", do you mean 3 nodes? Could we start by first implementing the ``citus_total_relation_size()`` udf? We could then move to other udfs?
* Depending on ``VACUUM``, if you calculate a reference table's size on one machine and then multiply it by the node count, you may have slightly misleading numbers. That is, the on-disk size for the same table could be different across different machines. This is minor, but I just wanted to make a note of it.

**Comment by velioglu** [comment]
No, I mean multiplying the size of a reference table located on a node with the number of worker nodes. I have implemented all three UDFs with the same logic by just changing the query run on worker nodes. I will analyze the result with different VACUUM options.

**Comment by metdos** [comment]
@ozgune, @velioglu I have a clarification question. For all udfs, as a user, I will expect to see total disk space used in the cluster, right?

For example, if I load my 10GB PostgreSQL table into a distributed table with replication count = 2, I should expect to see 20GB for citus_total_relation_size(). Am I right?

**Comment by metdos** [comment]
PostgreSQL functions and their meanings for reference:
https://www.postgresql.org/docs/9.6/static/functions-admin.html#FUNCTIONS-ADMIN-DBSIZE

**Comment by velioglu** [comment]
@metdos, as @ozgune  mentioned in his comment 

> The function only works with streaming replication and adds up total sizes on primary nodes.

the use case you mentioned is not covered by the current implementation. In fact, with the replication count = 1 you will still see the disk space for the table.  Only exception for this implementation is reference table. Implementation details of size functions on reference tables : 

https://github.com/citusdata/citus/issues/631#issuecomment-283324806
