### ISSUE TITLE
Unexpected error when querying a distributed partitioned table with statistics

### ISSUE THREAD

**Issue by naisila** [citusdata/citus#6329]
PG15beta4, Relevant PG commits: https://github.com/postgres/postgres/commit/20b9fa308ebf7d4a26ac53804fce1c30f781d60c https://github.com/postgres/postgres/commit/269b532aef55a579ae02a3e8e8df14101570dfd9

```SQL
-- create parent table
CREATE TABLE stxdinp(i int, a int, b int) PARTITION BY RANGE (i);

-- create partition
CREATE TABLE stxdinp1 PARTITION OF stxdinp FOR VALUES FROM (1) TO (100);

-- populate table
INSERT INTO stxdinp SELECT 1, a/100, a/100 FROM generate_series(1, 999) a;

-- create extended statistics
CREATE STATISTICS stxdinp ON a, b FROM stxdinp;

-- distribute parent table
SELECT create_distributed_table('stxdinp', 'i');

-- run select query, works fine
SELECT a, b FROM stxdinp GROUP BY 1, 2;
 a | b
---+---
 1 | 1
 3 | 3
 7 | 7
 2 | 2
 8 | 8
 0 | 0
 5 | 5
 6 | 6
 9 | 9
 4 | 4
(10 rows)

-- partitions are processed recursively
VACUUM ANALYZE stxdinp;

-- UNEXPECTED ERROR FACED
SELECT a, b FROM stxdinp GROUP BY 1, 2;
ERROR:  cache lookup failed for statistics object 17135
```

**Note: it doesn't matter whether the statistics is created before or after distributing the table**

**Comment by onderkalaci** [comment]
This is due to our hack on `AdjustPartitioningForDistributedPlanning()` while running standard_planner. In essence, PG expects statistics object to be owned by a parent table, whereas `AdjustPartitioningForDistributedPlanning` removes the `inh` field and breaks the planning. 

Postgres checks `pg_statistic_ext_data` with `OID` and `stxdinherit`. As we change `inh` field, postgres cannot find the given statistics object and throws error.

Looking for a way to avoid this.

**Comment by onderkalaci** [comment]
Cause by this commit: https://github.com/postgres/postgres/commit/269b532aef55a579ae02a3e8e8df14101570dfd9

**Comment by onderkalaci** [comment]
It turns out that even if the statistics object created on PG 14(or earlier) and then upgraded to PG 15, we hit this error, which prevents the option of only disabling this command on PG 15
