### ISSUE TITLE
hostname error coord.example.com:5432

### ISSUE THREAD

**Issue by ren2014** [citusdata/citus#6460]
I'm new to citus. 
I wanted to back a distributed table,but i found pg_dump in CN node couldn't get any data.
I ran pg_dump on that table in a worker.Then the error occured:

pg_dump: error: query failed: ERROR:  connection to the remote node coord.example.com:5432 failed with the following error: could not translate host name "coord.example.com" to address: Name or service not known
pg_dump: error: query was: LOCK TABLE test.back1 IN ACCESS SHARE MODE

i can't find any about  coord.example.com:5432 in databases/servers
Did I do something wrong during the installation?
And how can i back distributed table.

PG_VERSION:PostgreSQL 14.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit
CITUS_VERSION:Citus 11.0.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit

**Comment by ren2014** [comment]
Thank you for your reply.

I find this in pg_dist_node. And same thing happen when i update a reference table from a local table, but not when i select a distributed table in worknode(select * limit 100).

This PG-DB was not empty before i installed citus extension. I did it for the data analysis.  Now the cluster has a CN and two workers. And after i installed success , I calling citus_add_node and distributing table for test. Would this cause `coord.example.com`  to happen? t

In my scenario, the only thing run by citus is some of data analysis  with mass data. And applications that use these data will access that worker. Other queries still run on CN. Is that going to cause some problems?

How do i fix this .

**Comment by thanodnl** [comment]
To solve this issue you will need to change the connection information for the coordinator node in the node metadata. This is easiest done via [`citus_update_node`](https://docs.citusdata.com/en/v11.1/develop/api_udf.html#citus-update-node). You will want to update the nodeid for the node that is registered to `groupid=0`.

By changing the hostname from `coord.example.com` to the actual address of the coordinator, all the workers will know how to connect to the coordinator when they need to. This happens when querying worker nodes for shards that have placements on the coordinator, but also during some data copy operations.

It is good hygiene to have all the node metadata in your cluster working so that every node can use the nodename and nodeports to connect and authenticate to each other.

Hope this helps.

**Comment by ren2014** [comment]
Thank you,Thanodnl
Your advice helped me a lot.
