### ISSUE TITLE
incorrect error: column "…" does not exist

### ISSUE THREAD

**Issue by will** [citusdata/citus#652]
```
citus=> select master_create_distributed_table("not a table", 'whatever');
ERROR:  column "not a table" does not exist
LINE 1: select master_create_distributed_table("not a table", 'whate...
```
The table is the thing that doesn't exist, not the column.

**Comment by lithp** [comment]
The problem is that you're using double quotes instead of single quotes. The parser is throwing the error before citus gets involved. (You can also tell because this function doesn't exist, you need the third parameter telling it which distribution method to use)

Using single quotes works correctly:

```
brian=# SELECT master_create_distributed_table('noexist', 'somekey', 'hash');
ERROR:  relation "noexist" does not exist
LINE 1: SELECT master_create_distributed_table('noexist', 'somekey',...
                                               ^
```
