### ISSUE TITLE
Dependency tracking in transaction blocks with serial columns

### ISSUE THREAD

**Issue by YMikheev** [citusdata/citus#6614]
```SQL
BEGIN;
    create schema test_1;

    create table test_1.test ( id bigserial constraint test_pk primary key );
    select create_reference_table('test_1.test');
COMMIT;

[3F000] ERROR: schema "test_1" does not exist
```

**Comment by agedemenli** [comment]
thanks for reporting that @YMikheev 
It's because we create dependencies on workers nodes OUTSIDE transaction.

Here we have a sequence because of the bigserial field. So the dependency chain is like:
table -> sequence -> schema
When `create_reference_table` is called, `EnsureDependenciesExistOnAllNodes` tries to create the sequence on worker nodes, before replicating the table itself. Some commands to create the sequence goes to the worker but they error out as the schema does not exist on the worker. Because we send dependency creation commands OUTSIDE transaction. However, the transaction that the schema was created in is not committed yet.

**Comment by YMikheev** [comment]
Can you fix it?

**Comment by YMikheev** [comment]
PR - https://github.com/citusdata/citus/pull/6622

**Comment by marcocitus** [comment]
One workaround is to `set citus.create_object_propagation = 'deferred'` . See https://www.citusdata.com/blog/2022/03/26/test-drive-citus-11-beta-for-postgres/ for more details on this setting.

We do the dependency creation in a subtransaction for good reasons. In particular, the objects may have to be created as different users, which fundamentally cannot use the same transaction.

Still, this example shows a shortcoming in the current approach that we should seek to address. It might be specific to sequences.

**Comment by YMikheev** [comment]
Thanks for workaround.

But I found same issue with comments:

BEGIN;
    set citus.create_object_propagation = 'deferred';
    create schema test_1;

    create table test_1.test ( id bigserial constraint test_pk primary key );
    comment on column test_1.test.id is 'test comment';

    select create_reference_table('test_1.test');
COMMIT;

[3F000] ERROR: schema "test_1" does not exist

Do you now some workaround with comments?

**Comment by marcocitus** [comment]
I don't see that error. As far as I know, Citus does not currently propagate comments, so this should not affect the outcome.

**Comment by YMikheev** [comment]
Try it please inside a function:

create function create_schema_test() returns text as $$
begin
    set citus.create_object_propagation = 'deferred';

    create schema test_1;

    create table test_1.test (
        id bigserial constraint test_pk primary key,
        creation_date timestamp constraint test_creation_date_df default timezone('UTC'::text, CURRENT_TIMESTAMP)    not null
    );

    select create_reference_table('test_1.test');
end;
$$ language plpgsql;

select create_schema_test();

[3F000] ERROR: schema "test_1" does not exist
