### ISSUE TITLE
Distributed INSERT SELECT might mistakenly push-down / not push-down some SELECT queries that we shouldn't / could

### ISSUE THREAD

**Issue by onurctirtir** [citusdata/citus#6749]
```sql
-- create two distributed tables that belong to same colocation group
create table dist_c1_t1 (a int, b int);
create table dist_c1_t2 (a int, b int);

SELECT create_distributed_table('dist_c1_t1', 'a', shard_count=>4);
SELECT create_distributed_table('dist_c1_t2', 'a', colocate_with=>'dist_c1_t1');

-- create another distributed table that belong to a different colocation group
create table dist_c2_t1 (a int, b int);
SELECT create_distributed_table('dist_c2_t1', 'a', shard_count=>3);

-- and create a reference table
create table ref(a int, b int);
SELECT create_reference_table('ref');
```

----

Example - 1: Incorrect query push-down due to missing colocation check.

As long as we're inserting into target rel's distribution column from the distribution column of a colocated distributed rel, we consider given INSERT .. SELECT command as distributed. However, this might not be always correct.
```sql
-- Below, we create two join tasks based on same shard (public.dist_c2_t1_102016) due to shard count mismatch.
explain insert into dist_c1_t1 select dist_c1_t2.* from dist_c1_t2 join dist_c2_t1 using(a);
DEBUG:  distributed statement: INSERT INTO public.dist_c1_t1_102008 AS citus_table_alias (a, b) SELECT dist_c1_t2.a, dist_c1_t2.b FROM (public.dist_c1_t2_102012 dist_c1_t2(a, b) JOIN public.dist_c2_t1_102016 dist_c2_t1(a, b) USING (a)) WHERE (dist_c1_t2.a IS NOT NULL)
DEBUG:  distributed statement: INSERT INTO public.dist_c1_t1_102009 AS citus_table_alias (a, b) SELECT dist_c1_t2.a, dist_c1_t2.b FROM (public.dist_c1_t2_102013 dist_c1_t2(a, b) JOIN public.dist_c2_t1_102016 dist_c2_t1(a, b) USING (a)) WHERE (dist_c1_t2.a IS NOT NULL)
DEBUG:  distributed statement: INSERT INTO public.dist_c1_t1_102010 AS citus_table_alias (a, b) SELECT dist_c1_t2.a, dist_c1_t2.b FROM (public.dist_c1_t2_102014 dist_c1_t2(a, b) JOIN public.dist_c2_t1_102017 dist_c2_t1(a, b) USING (a)) WHERE (dist_c1_t2.a IS NOT NULL)
DEBUG:  distributed statement: INSERT INTO public.dist_c1_t1_102011 AS citus_table_alias (a, b) SELECT dist_c1_t2.a, dist_c1_t2.b FROM (public.dist_c1_t2_102015 dist_c1_t2(a, b) JOIN public.dist_c2_t1_102018 dist_c2_t1(a, b) USING (a)) WHERE (dist_c1_t2.a IS NOT NULL)
```

Also see https://github.com/citusdata/citus/issues/6749#issuecomment-1470874911.

----

Example - 2: Incorrect query push-down because MultiTaskRouterSelectQuerySupported lacks of some push-down checks that we normally perform for SELECT queries, via DeferErrorIfUnsupportedSubqueryPushdown.

Besides that, MultiTaskRouterSelectQuerySupported also enforces some restrictions that we don't need and hence prevents pushing down some forms of INSERT .. SELECT.
See https://github.com/citusdata/citus/issues/6749#issuecomment-1470681280.

```sql
-- I don't think we normally allow pushing down such an outer join.
-- Normally, we should handle such a join via recursive planning.
--
-- Root-cause: 
explain insert into dist_c1_t2 select t1.* from dist_c1_t1 t1 right join ref using(a);
DEBUG:  distributed statement: INSERT INTO public.dist_c1_t2_102012 AS citus_table_alias (a, b) SELECT t1.a, t1.b FROM (public.dist_c1_t1_102008 t1(a, b) RIGHT JOIN public.ref_102019 ref(a, b) USING (a)) WHERE (t1.a IS NOT NULL)
DEBUG:  distributed statement: INSERT INTO public.dist_c1_t2_102013 AS citus_table_alias (a, b) SELECT t1.a, t1.b FROM (public.dist_c1_t1_102009 t1(a, b) RIGHT JOIN public.ref_102019 ref(a, b) USING (a)) WHERE (t1.a IS NOT NULL)
DEBUG:  distributed statement: INSERT INTO public.dist_c1_t2_102014 AS citus_table_alias (a, b) SELECT t1.a, t1.b FROM (public.dist_c1_t1_102010 t1(a, b) RIGHT JOIN public.ref_102019 ref(a, b) USING (a)) WHERE (t1.a IS NOT NULL)
DEBUG:  distributed statement: INSERT INTO public.dist_c1_t2_102015 AS citus_table_alias (a, b) SELECT t1.a, t1.b FROM (public.dist_c1_t1_102011 t1(a, b) RIGHT JOIN public.ref_102019 ref(a, b) USING (a)) WHERE (t1.a IS NOT NULL)
```

**Comment by onurctirtir** [comment]
Maybe we should call DeferErrorIfUnsupportedRouterPlannableSelectQuery somewhere in DistributedInsertSelectSupported.

**Comment by onderkalaci** [comment]
> -- example - 1:
-- Below, we create two join tasks based on same shard (public.dist_c2_t1_102016) due to shard count mismatch.
-- Normally, the SELECT query should be handled via repartition join planner.
explain insert into dist_c1_t1 select dist_c1_t2.* from dist_c1_t2 join dist_c2_t1 using(a);
DEBUG:  distributed statement: INSERT INTO public.dist_c1_t1_102008 AS citus_table_alias (a, b) SELECT dist_c1_t2.a, dist_c1_t2.b FROM (public.dist_c1_t2_102012 dist_c1_t2(a, b) JOIN public.dist_c2_t1_102016 dist_c2_t1(a, b) USING (a)) WHERE (dist_c1_t2.a IS NOT NULL)
DEBUG:  distributed statement: INSERT INTO public.dist_c1_t1_102009 AS citus_table_alias (a, b) SELECT dist_c1_t2.a, dist_c1_t2.b FROM (public.dist_c1_t2_102013 dist_c1_t2(a, b) JOIN public.dist_c2_t1_102016 dist_c2_t1(a, b) USING (a)) WHERE (dist_c1_t2.a IS NOT NULL)
DEBUG:  distributed statement: INSERT INTO public.dist_c1_t1_102010 AS citus_table_alias (a, b) SELECT dist_c1_t2.a, dist_c1_t2.b FROM (public.dist_c1_t2_102014 dist_c1_t2(a, b) JOIN public.dist_c2_t1_102017 dist_c2_t1(a, b) USING (a)) WHERE (dist_c1_t2.a IS NOT NULL)
DEBUG:  distributed statement: INSERT INTO public.dist_c1_t1_102011 AS citus_table_alias (a, b) SELECT dist_c1_t2.a, dist_c1_t2.b FROM (public.dist_c1_t2_102015 dist_c1_t2(a, b) JOIN public.dist_c2_t1_102018 dist_c2_t1(a, b) USING (a)) WHERE (dist_c1_t2.a IS NOT NULL)


Ops, we only seem to do the colocation check with the source and target tables: https://github.com/citusdata/citus/blob/ab71cd01eea9ca86ed9fcbce2878999fc3db1c67/src/backend/distributed/planner/insert_select_planner.c#L733

We should make sure all tables are colocated (and backport it as much as possible).


> -- example - 2:
-- I don't think we normally allow pushing down such an outer join.
-- Normally, we should handle such a join via recursive planning.
explain insert into dist_c1_t2 select t1.* from dist_c1_t1 t1 right join ref using(a);

Luckily, the query on the shards are not outer joins due to NOT NULL, but we can probably find queries that'd produce wrong results

```SQL
explain insert into dist_c1_t2 select t1.* from dist_c1_t1 t1 right join ref using(a);
┌──────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                              QUERY PLAN                                              │
├──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0)                                       │
│   Task Count: 4                                                                                      │
│   Tasks Shown: One of 4                                                                              │
│   ->  Task                                                                                           │
│         Node: host=localhost port=9700 dbname=postgres                                               │
│         ->  Insert on dist_c1_t2_102012 citus_table_alias  (cost=316.32..708.77 rows=0 width=0)      │
│               ->  Merge Join  (cost=316.32..708.77 rows=25414 width=8)                               │
│                     Merge Cond: (t1.a = ref.a)                                                       │
│                     ->  Sort  (cost=157.81..163.44 rows=2249 width=8)                                │
│                           Sort Key: t1.a                                                             │
│                           ->  Seq Scan on dist_c1_t1_102008 t1  (cost=0.00..32.60 rows=2249 width=8) │
│                                 Filter: (a IS NOT NULL)                                              │
│                     ->  Sort  (cost=158.51..164.16 rows=2260 width=4)                                │
│                           Sort Key: ref.a                                                            │
│                           ->  Seq Scan on ref_102019 ref  (cost=0.00..32.60 rows=2260 width=4)       │
└──────────────────────────────────────────────────────────────────────────────────────────────────────┘
(15 rows)
```

**Comment by onurctirtir** [comment]
> Luckily, the query on the shards are not outer joins due to NOT NULL, but we can probably find queries that'd produce wrong results

Yes, this would become a problem if we do `INSERT .. SELECT ref.*` instead.

**Comment by onderkalaci** [comment]
> Yes, this would become a problem if we do INSERT .. SELECT ref.* instead.

That goes through INSERT .. SELECT via repartitioning, so should be fine

**Comment by onderkalaci** [comment]
related to https://github.com/citusdata/citus/issues/1428

**Comment by onurctirtir** [comment]
https://github.com/citusdata/citus/issues/1428 not only causes incorrectly pushing down some queries we normally don't, but also causes not pushing down some of the queries that we could, e.g., set operations.

**Comment by onurctirtir** [comment]
> -- example - 1:
-- Below, we create two join tasks based on same shard (public.dist_c2_t1_102016) due to shard count mismatch.
-- Normally, the SELECT query should be handled via repartition join planner.

I'd expect RouterModifyTaskForShardInterval to already throw an error by detecting that some of the tasks do reference multiple shards (due to shard interval mismatch).

**Comment by onurctirtir** [comment]
Another problem with insert .. select pushdown is documented in another issue: https://github.com/citusdata/citus/issues/3156

That one is about the way we handle the ctelist of insert.
