### ISSUE TITLE
Memory leak even if NOT using repartition-join

### ISSUE THREAD

**Issue by kot8891** [citusdata/citus#7250]
Problem:
When executing the insert/select query, I have a memory leak and one of the Postgresql server shuts down

Configuration

Postgresql:
PostgreSQL 16.0 (Debian 16.0-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

CITUS:
Citus 12.1.0 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
citus.enable_repartition_joins=off   !!!

Hardware:
Coordinator node: 6 CPU, 8GB RAM, 20 GB available storage space
4 worker nodes each: 4 CPU, 16 GB RAM 300GB available storage space

All scripts ro reproduce the error are here: 

[sql_to_reproduce_mem_leak.txt](https://github.com/citusdata/citus/files/12840760/sql_to_reproduce_mem_leak.txt)

I have  7 joins. table1_dist, table2_dist and table3_dist,  table4_dist, table7_dist, table8_dist are columnar and collocated and table5_ref, table6_ref are heap reference tables. My_flat_table is columnar and distributed. All details are in the arrached file. Every table has not more than 3 million rows.  

```
insert into my_flat_table
select
		dhc.id
	,	left(dscpctikcvced.text_val1, 4) || '**** ****' || right(dscpctikcvced.text_val3, 4)
	,	case
			when dscpctikcvced.text_val4 = 'T'
				then	'ssssss'
			else	'rrrrrr'
		end										as _type
	,	dscpctikcvced.date_val2
	,	dscpctikcvced.text_val5
	,	coalesce(dscpctikcvced.text_val5, 'EEEEEEE')
	,	dscpctikcvced.date_val1
	,	dscpctikcvced.date_val2
	,	dscssi.text_val1
	,	dscssi.text_val3
	,	rscpnas.m_text1
	,	rscpnas.m_text3

from

		table1_dist																		dhc
		join	table2_dist																dscpctikcvced
		on	dscpctikcvced.m_hashkey = dhc.m_hashkey
			join	table3_dist																dscssi
			on	dscssi.m_hashkey = dhc.m_hashkey
				join	table4_dist														dlc2cp
				on		dlc2cp.m_hashkey = dhc.m_hashkey
					join	table5_ref												rhcp
					on	rhcp.m_hashkey = dlc2cp.m_hashkey
						join	table6_ref										rscpnas
						on	rscpnas.m_hashkey = rhcp.m_hashkey
						
					join	table7_dist										dlc2ca
					on	dlc2ca.m_hashkey = dhc.m_hashkey
				join	table8_dist 												dhca
				on	dhca.m_hashkey = dlc2ca.m_hashkey
```
After running the query above, I have a sharp decrease in RAM, and this leads to a full swap, and then one or two worker nodes fail. **In fact, in my product data, the coordinator always crashes at an even faster pace**. Perhaps it depends on how correlated the data is in the columns that are used in the join clause, because table structures and types, as well as row counts are the same.

![image](https://github.com/citusdata/citus/assets/81918162/fc442f73-53bb-4085-b197-4fe39e393660)

The next second Postgresql server fails because of OOM killer;

**Comment by onurctirtir** [comment]
The query plan doesn't change based on "citus.enable_repartition_joins" because the query doesn't have a join that requires doing a "repartitioned join", but it requires doing a "repartitioned insert .. select", which can be controlled by "citus.enable_repartitioned_insert_select". It requires "repartitioned insert .. select" because the query inserts "id" column of "table1_dist" into "id" column of "my_flat_table" and while "id" is the distribution column of "my_flat_table", this is not the case for "table1_dist".

You can disable "citus.enable_repartitioned_insert_select" but this would mean pulling result of the SELECT query to the coordinator and then sending the returned tuples back to the workers; though you might then experience excessive memory / disk usage problem on the coordinator.

You might want to shard your other tables based on "id" column if that fits to your data model. I don't see any better option other than this.

Feel free to re-open the issue if those don't help to you.

**Comment by onurctirtir** [comment]
Closed due to https://github.com/citusdata/citus/issues/7249#issuecomment-1755170488.
