### ISSUE TITLE
Error in master_disable_node/citus_disable_node

### ISSUE THREAD

**Issue by Green-Chan** [citusdata/citus#7454]
master_disable_node has only two arguments
`CREATE FUNCTION master_disable_node(nodename text, nodeport integer)`
but its realization is
```
Datum
master_disable_node(PG_FUNCTION_ARGS)
{
	return citus_disable_node(fcinfo);
}
```
while citus_disable_node has three arguments and always reads all of them
```
Datum
citus_disable_node(PG_FUNCTION_ARGS)
{
	text *nodeNameText = PG_GETARG_TEXT_P(0);
	int32 nodePort = PG_GETARG_INT32(1);
	bool synchronousDisableNode = PG_GETARG_BOOL(2);
...
```

Thus when master_disable_node is called, memory outside of the function call info is accessed, and further behavior is undefined

**Comment by JelteF** [comment]
@Green-Chan is correct here. This is a bug. FunctionCallInfoBaseData is sized based on the amount of arguments. So reading past that allocation would be undefined behaviour. My guess why valgrind doesn't catch it is because maybe the memory right after is still valid memory, just part of a different allocation/stack variable.

It's not a security issue though, since `master_disable_node` can only be called by superusers anyway. But it would be good to fix this.
