### ISSUE TITLE
 FATAL:  could not load server certificate file "server.crt": ee key too small

### ISSUE THREAD

**Issue by adnanhamdussalam** [citusdata/citus#7666]
I have setup 1 coordinator, and 2 workers nodes then planned to create standby of coordinator (Streaming Physical Replication).
While creating the standby node using pg_basebackup but when I start the service on standby node facing below error:

 FATAL:  could not load server certificate file "server.crt": ee key too small
 
 But when I comment out the ssl parameters from postgresql.auto.conf the service gets started but I want to start the service with ssl

Can anyone help me out in this regard?

**Comment by emelsimsek** [comment]
Can you make sure that postgres reads the correct certificate files that are 2048 bit long.

**Comment by adnanhamdussalam** [comment]
Solution:

On standby:
			-- Removed the files server.key , server.csr, server.crt
			Executed below commands:
			-- openssl genpkey -algorithm RSA -out server.key -pkeyopt rsa_keygen_bits:4096
			-- openssl req -new -key server.key -out server.csr
			-- openssl x509 -req -in server.csr -signkey server.key -out server.crt -days 365
			-- chmod 600 /var/lib/pgsql/data/server.*
			-- openssl dhparam -out dhparams.pem 4096
                        -- chmod 0600 dhparams.pem
Then edit the file postgresql.auto.conf set below parameter:
ssl_dh_params_file = '/data/ctdatabase/dhparams.pem'

The standby database has been started successfully.

**Comment by emelsimsek** [comment]
@adnanhamdussalam,  your solution looks good.

Note that:
-- openssl dhparam -out dhparams.pem 4096
-- chmod 0600 dhparams.pem
-- ssl_dh_params_file = '/data/ctdatabase/dhparams.pem'

 are optional and were not required to solve the issue. (They are good for hardening your server further though).
 
As a general recommendation, it is not a good practice to edit postgresql.auto.conf manually. (https://www.postgresql.org/docs/current/config-setting.html#:~:text=In%20addition%20to,postgresql.conf.)

 I believe the original issue was likely due to wrong server.key , server.crt files and/or permissions on them which you have fixed as above.
