### ISSUE TITLE
Memory leak in shard connection hash

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#767]
@jasonmp85 found this while doing #764 

In [CreateShardConnectionHash](https://github.com/citusdata/citus/blob/master/src/backend/distributed/transaction/multi_shard_transaction.c#L97) we pass the HASH_CONTEXT flag to hash_create, but we do not specify info.hcxt, which ends up creating a parentless memory context (like TopMemoryContext) and thus creates a session-level memory leak.

**Comment by jasonmp85** [comment]
Is this really a 1–2 day fix? Seems like it's just "set the context correctly", no?

**Comment by jasonmp85** [comment]
I mean, the current context, at least in the 5.2 line, is `TopTransactionContext` (see the diff for #764 for removed lines that wrapped all of `OpenTransactionsToAllShardPlacements`'s work in a switch to that context), but that context should work just fine.

I'm asking because if this is low-impact/high-confidence enough, I'm building 5.2.1 for another reason and we might as well rush this in, too.

**Comment by marcocitus** [comment]
Eh, I guess I labeled it with 1-2 days to mark it as a quick fixe, but in practice I see no reason for it to take more than 1-2 minutes.
