### ISSUE TITLE
Citus version in control file do not match the version tag

### ISSUE THREAD

**Issue by teoincontatto** [citusdata/citus#7688]
The latest 12.1.4 version of citus has the [`citus.control` version set to 12.1-1](https://github.com/citusdata/citus/blob/v12.1.4/src/backend/distributed/citus.control). It seems that it is the case also for version 12.1.2 and 12.1.3. In our case ([StackGres](https://gitlab.com/ongresinc/stackgres)) this make it difficult to allow the users to upgrade to the latest version since the version is the same as the previous. It is also a bit confusing when it comes to report an issue since it is not clear which version it is used.

Can this be fixed? Should we patch the code to set correctly the `citus.control` version? Is this done so in order to avoid some other issue I am not aware of?

**Comment by hanefi** [comment]
There is nothing wrong with the codebase in the latest 12.1 releases. At least not technically.
 
There is a high number of confused users and sometimes developers of this extension as it is not clear to people how our versioning works.
 
There are 2 separate versions:

## 1. The version of the extension.

- This one has the form X.Y.Z where Z starts from 0.
- It is stored in the OS package version
- You can use `citus_version()` guc to see the version.

## 2. The schema version of the extension

- This one has the form X.Y-Z and Z starts from 1.
- It shows the state of the database schema. If a patch release did not really update database objects, there is no reason to bump the schema.
- You can see `\dx` output or `pg_extension*` catalogs for the migration version or the control file content.

I admit this is not so easy to grasp. However, it is consistently this way since 5+ years.

```
SELECT citus_version();
+-----------------------------------------------------------------------------------------------------+
|                                            citus_version                                            |
+-----------------------------------------------------------------------------------------------------+
| Citus 12.1.5 on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit gitref: v12.1.5 |
+-----------------------------------------------------------------------------------------------------+
```
