### ISSUE TITLE
SQL functions with parameterized variables throw errors

### ISSUE THREAD

**Issue by saicitus** [citusdata/citus#789]
**Setting up the table**

```
CREATE TABLE lineitem(id integer, org_id integer);

select master_create_distributed_table('lineitem','org_id','hash');

select master_create_worker_shards('lineitem',16,1);

INSERT INTO lineitem VALUES(1,1);
INSERT INTO lineitem VALUES(3,4);
INSERT INTO lineitem VALUES(2,2);
```

**Parameterized partition column.**

```
CREATE TABLE lineitem(id integer, org_id integer);

select master_create_distributed_table('lineitem','org_id','hash');

select master_create_worker_shards('lineitem',16,1);

INSERT INTO lineitem VALUES(1,1);
INSERT INTO lineitem VALUES(3,4);
INSERT INTO lineitem VALUES(2,2);


CREATE OR REPLACE FUNCTION count_rows(org_id_val integer)
RETURNS TABLE (a bigint)
AS $$
  SELECT count(*) AS count_val from lineitem where org_id=org_id_val;
$$ LANGUAGE SQL STABLE;
```

The below test throws wrong results. The query doesn't run on the distributed table.

```
select * from count_rows(1);
 a

---
 0
```

The below test doesn't identify parameterized variables.

```
select count_rows(1);
CONTEXT:  while executing command on 10.0.0.12:5432
SQL function "count_rows" statement 1
WARNING:  there is no parameter $1
CONTEXT:  while executing command on 10.0.0.12:5432
SQL function "count_rows" statement 1
WARNING:  there is no parameter $1
CONTEXT:  while executing command on 10.0.0.12:5432
SQL function "count_rows" statement 1
WARNING:  there is no parameter $1
CONTEXT:  while executing command on 10.0.0.12:5432
SQL function "count_rows" statement 1
```

**Parameterized non-partition column: Exactly same thing as above even with non-partition column.**

```
CREATE OR REPLACE FUNCTION count_rows(id_val integer)
RETURNS TABLE (a bigint)
AS $$
  SELECT count(*) AS count_val from lineitem where id_val=id_val;
$$ LANGUAGE SQL STABLE;

select * from count_rows(1);
 a

---
 0

select count_rows(1);
SQL function "count_rows" statement 1
WARNING:  there is no parameter $1
CONTEXT:  while executing command on 10.0.0.12:5432
SQL function "count_rows" statement 1
WARNING:  there is no parameter $1
CONTEXT:  while executing command on 10.0.0.12:5432
SQL function "count_rows" statement 1
WARNING:  there is no parameter $1
CONTEXT:  while executing command on 10.0.0.12:5432
SQL function "count_rows" statement 1
WARNING:  there is no parameter $1
CONTEXT:  while executing command on 10.0.0.12:5432
SQL function "count_rows" statement 1
WARNING:  there is no parameter $1
CONTEXT:  while executing command on 10.0.0.12:5432
SQL function "count_rows" statement 1
WARNING:  there is no parameter $1
CONTEXT:  while executing command on 10.0.0.12:5432
SQL function "count_rows" statement 1
WARNING:  there is no parameter $1
CONTEXT:  while executing command on 10.0.0.12:5432
SQL function "count_rows" statement 1
WARNING:  there is no parameter $1
CONTEXT:  while executing command on 10.0.0.12:5432
SQL function "count_rows" statement 1
```

**Comment by robin900** [comment]
Running a special test locally, with extra `elog()` calls, it seems that `multi_planner.c` receives the standard plan, but `NeedsDistributedPlanning()` returns false. `NeedsDistributedPlanning()` returns false because it only walks simple relation references to determine `hasDistributedRelation`. I don't know much about SQL function inlining, but `pull_up_subqueries_recurse` claims to do it and the test functions above seem to meet the criteria for function inlining. But the resulting `Query*` from the standard planner is below and it doesn't look like an inlining of the function SQL. `NeedsDistributedPlanning` returns false for this query, of course.

{QUERY :commandType 1 :querySource 0 :canSetTag true :utilityStmt <> :resultRelation 0 :hasAggs false :hasWindowFuncs false :hasSubLinks false :hasDistinctOn false :hasRecursive false :hasModifyingCTE false :hasForUpdate false :hasRowSecurity false :cteList <> :rtable ({RTE :alias <> :eref {ALIAS :aliasname count_rows :colnames ("a")} :rtekind 3 :functions ({RANGETBLFUNCTION :funcexpr {FUNCEXPR :funcid 16895 :funcresulttype 20 :funcretset true :funcvariadic false :funcformat 0 :funccollid 0 :inputcollid 0 :args ({CONST :consttype 23 :consttypmod -1 :constcollid 0 :constlen 4 :constbyval true :constisnull false :location 29 :constvalue 4 [ 1 0 0 0 0 0 0 0 ]}) :location 14} :funccolcount 1 :funccolnames <> :funccoltypes <> :funccoltypmods <> :funccolcollations <> :funcparams (b)}) :funcordinality false :lateral false :inh false :inFromCl true :requiredPerms 2 :checkAsUser 0 :selectedCols (b) :insertedCols (b) :updatedCols (b) :securityQuals <>}) :jointree {FROMEXPR :fromlist ({RANGETBLREF :rtindex 1}) :quals <>} :targetList ({TARGETENTRY :expr {VAR :varno 1 :varattno 1 :vartype 20 :vartypmod -1 :varcollid 0 :varlevelsup 0 :varnoold 1 :varoattno 1 :location 7} :resno 1 :resname a :ressortgroupref 0 :resorigtbl 0 :resorigcol 0 :resjunk false}) :onConflict <> :returningList <> :groupClause <> :groupingSets <> :havingQual <> :windowClause <> :distinctClause <> :sortClause <> :limitOffset <> :limitCount <> :rowMarks <> :setOperations <> :constraintDeps <>}

**Comment by metdos** [comment]
There are other query types where parameterized SQL functions fail. 
I added list here: https://github.com/citusdata/citus/issues/306#issuecomment-250475341

**Comment by metdos** [comment]
This seems like a duplicate #499. @sumedhpathak, shall we close one, or keep both open?

**Comment by ozgune** [comment]
@saicitus -- Could you look at #499 and confirm that it's a duplicate?

If #789 and #499 are duplicates, could you copy/paste the comments here to #499 and close this one as a duplicate?

**Comment by saicitus** [comment]
Closing this issue and created a new related issue #981
