### ISSUE TITLE
Add worker sequence number generation logic

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#794]
To generate unique sequence numbers for bigserial columns from workers, generate sequence numbers as: [16-bit group ID][48-bit sequence number] by setting the minvalue and maxvalue on each sequence on the worker. Monotonic worker-generated sequence numbers are not and probably never will be supported. Tuples can be ordered by a (timestamp,sequence number) tuple if a consistent chronologic order is required.

**Comment by marcocitus** [comment]
An issue came up while trying to use sequences in MX, namely that the owner of the sequence is not correctly set during metadata syncing.

**Comment by aamederen** [comment]
One thing about the sequences is about workers without metadata.

Unlike distributed tables and metadata, sequences (serial columns) are already propagated to non-metadata workers as well. This brings some problems:

- Upon syncing metadata to a worker node, the sequence will probably already exist on the worker. One solution in this case a `CREATE SEQUENCE IF NOT EXIST` followed by `ALTER SEQUENCE` command would be required. The `ALTER SEQUENCE` command can set `MINVALUE`, `MAXVALUE` and `START` parameters and also issue a `RESTART`.

- AFTER `stop_metadata_sync_to_node` is called on a worker, if a `DROP TABLE` is issued to the mx table, it will error out since the distributed table will stay dependent on the sequence on the worker. Solutions could be cleaning up the worker on `stop_metadata_sync_to_node` or issuing the drop sequence with `CASCADE` option.

**Comment by aamederen** [comment]
@marcocitus should this task cover the sequences of (BIG)SERIAL columns only, or all sequences? I belive, if we would like to cover all sequences, then it could be a separate PR with separate UDFs.

**Comment by aamederen** [comment]
Also:

- ALTER TABLE ... ADD COLUMN with BIGSERIAL
- ALTER TABLE ... SET DEFAULT
- ALTER SEQUENCE commands (both from the Schema node and worker nodes)

**Comment by marcocitus** [comment]
> should this task cover the sequences of (BIG)SERIAL columns only, or all sequences?

Bigserial only.

I think the scope is what we have in the citus-mx repo.
