### ISSUE TITLE
Provide sensible default for shard count

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#802]
The shard count setting is the one we receive the most number of questions on from early users. We should look to calculate a sensible value here if we can infer the cluster size and total number of cpu cores. This is easier to do on the Cloud. If we can't compute a good value for this, we might pick a good enough default value for new users.

This issue is also related to #694

**Comment by ozgune** [comment]
We talked about picking a sensible default for shard count (for hash distributed tables). Picking this default setting has two dimensions to it:

1. Who are we picking this default setting for? For new users who're trying things out on their laptops, users who deployed Citus in a test environment of multiple machines, or those who are deploying clusters in prod?
2. What considerations impact the shard count? (a) ``max_connections``, (b) ``COPY`` concurrency, (c) Scalability and future scalability, (d) Query parallelism, (e) Read/write concurrency and whether we recommend setting up PgBouncer by default.

**Comment by fdr** [comment]
Per meatspace request:

When tuning based on one variable, a technique I have found useful is to use curve fitters to convert conventional wisdom into (typically) logarithmic fits.

Logarithmic fits tend to be a good candidate because there are nearly always scalability limits at the high end, and at the low end of a scale fixed costs begin to dominate, shrinking values faster as one moves to smaller values.  Furthermore, most systems do not have large volatile swings when there is a small change in input values.

Finally, logarithmic fits are implemented in a lot of software, e.g. Wolfram Alpha, which I used to get going quickly. Other reasonable fits, like arctan, are not so frequently implemented.  Often the errors of the fit are not large, so, "good enough" can apply. I try a few fits to see how the residuals are affected.

For example, based on fitting to the conventional wisdom, the following fit is used in Citus Cloud for these two settings:

maintenance_work_mem = 327.668 * Math.log(`mem_gib`) + 157.138
work_mem = 116 * Math.log(`mem_gib`) + 10

I have found the fitting exercise useful because it can expose non-sensical outliers in the conventional wisdom (e.g. a tuning for a 10GiB system that is suspiciously off-trend from a 5GiB and 15GiB system).

**Comment by ozgune** [comment]
We ran a mini-survey for a sensible default setting; and I'm including results here. It's also worth noting that Cloud's mini test plan comes with a default of ``max_connections = 20``.

| Initial shard count | Vote count |
| ------------- | ------------- |
| 16 | 1 |
| 32 | 1 |
| 64 | 0.5 |
| max(64, 2*core count) | 1.5 |
| 2.5*core count | 2 |
| 120/128 | 3 |
| 256 | 1 |

**Comment by anarazel** [comment]
I think adding cpu core detection is more complicated than it's
worth. Thus I propose that we use a default shardcount based on a guc,
with a sane default (64 or 128 basically). Managed environments can
adapt that default based on the setup, and it's sane for others.

**Comment by ozgune** [comment]
@samay-sharma, @saicitus, @will and I talked about this more today.

For picking a default value, we first identified the audience as: community testers (single laptop), cloud testers, community, and hands-on engineering sessions. For users who are more advanced or customers moving into production, we'd adjust the shard count setting as needed.

We then noted that shard count relates to the following variables: ``max_connections`` on workers, parallelism, read concurrency, write concurrency (and ``COPY``), and future scalability. PostgreSQL sets ``max_connections`` to 100 by default. In Citus Cloud's test plan, we set this setting to 20 on the leader node and 300 on worker nodes.

We then looked at three values for the initial shard count using survey results: 32, 64, and 128. We then looked into the default behavior we offer in our documentation (``max_connections`` set to 100, replication factor set to 2, and 2 worker nodes). In this set up, using ``COPY`` with 128 shards runs into ``max_connections`` issues and we run into connection limits.

We then focused on 32 and 64 as initial defaults. After a lengthy conversation, we decided that setting the default to 32 works well for single machine test environments; and 64 works better for cloud testers.

**Comment by marcocitus** [comment]
The emphasis on powers of 2 is a bit strange to me.

Divisors of 60: 1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30, 60
Divisors of 64: 	1, 2, 4, 8, 16, 32, 64

Divisors of 120: 1, 2, 3, 4, 5, 6, 8, 10, 12, 15, 20, 24, 30, 40, 60, 120
Divisors of 128: 1, 2, 4, 8, 16, 32, 64, 128

Which means there are many more real-world set-ups in which 60/120 shards will give you an even shard placement distribution than 64/128 shards, which can make a significant performance difference.

> We then noted that shard count relates to the following variables: max_connections on workers, parallelism, read concurrency, write concurrency (and COPY), and future scalability. 

and shard rebalancer, skew in data distribution.

**Comment by ozgune** [comment]
We chatted more about this thread yesterday and this morning. @samay-sharma and @saicitus will look more into setting initial shards counts to 60/120 for production deployments.

We then talked about our target audience for the default value - users who are testing their deployments on smaller clusters. For that audience, we decided to provide an initial default of 32.

**Comment by onderkalaci** [comment]
@ozgune 

> For that audience, we decided to provide an initial default of 32 for hash distributed tables.

Just a note, we're implementing this with #867.

**Comment by metdos** [comment]
@ozgune 

> For that audience, we decided to provide an initial default of 32 for hash distributed tables.
> Just a note, we're implementing this with #867.

I'm closing this. We added shard count to guc variables and set the default to 32 with this commit https://github.com/citusdata/citus/commit/d04f4f593511b07e5ff6df90609d6391ddc84ad2
