### ISSUE TITLE
Introduce the notion of reference tables at the API level

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#827]
We currently enable reference tables in an indirect manner: if the user specifies a shard count less than ``citus.large_table_shard_count``, we assume during query planning that the table can be broadcasted. This introduces confusion and we should enable creating reference tables in an intuitive way.

The current API proposal is the following.

<pre>
CREATE TABLE region (...);
SELECT create_reference_table('region');
</pre>

This API will create a reference table that only has one shard. The API will pick a distribution column for the reference table (any column will do). Although not required, we could pick one of the primary key columns and if not, any column that has a base type.

This issue is also related to #694.

**Comment by ozgune** [comment]
We have two small open questions around this table.

(1) What name do we want to pick for this function? Some alternatives are: ``create_reference_table``, ``create_replicated_table``, ``create_dimension_table``, ``create_distributed_reference_table``, ``citus_create_reference_table``.

I'm also noting two consideration points for the function name.

* Citus replicates all tables. If we use "replicated" in our function name, does it introduce the question in user's mind about other tables not being replicated?
* Our users asked us numerous times about joining regular Postgres tables and distributed Citus tables. This is primarily due to our lack of documentation. If we simply pick the name ``create_reference_table``, does it reinforce that expectation?

(2) For reference tables, we will use a default shard count of 1. What should we use as the default for the replication factor?

We have two options. We could read this value from our GUC config and keep symmetry between distributed and reference tables for the v6.0 release. In cases where we need to override this value, we then provide instructions to do so. This is the option I'm leaning towards for this release cycle.

Alternatively, we look at the number of nodes in pg_worker_list.conf and set the replication factor to that value. This may be a bigger change for this release, and may require coordination with the Cloud team.

**Comment by robin900** [comment]
👎  on introducing a new concept ("reference table") to the API at this point in time. Reasons:

1. I can imagine use cases for such a table in which the table is not a "reference table", but instead represents a set of facts that just happen not to be very large and don't have a clear favorite for a partition column.
1. Will Citus (core or Enterprise) ever support the idea of reorganizing a hash-distributed table so that it has fewer or more shards after the reorganization? From what I see in the docs, `rebalance_table_shards` only moves shards; it does not consolidate or divide shards for hash-distributed tables during rebalancing. If it *does* support shard reduction/increase now or in future, then users may wish to change a hash-distributed table from a single shard to multiple shards, or vice versa; and then what becomes of the "reference table" concept?
1. A "permanently single-shard" table seems more like a new distribution method than a "table type". I can imagine a very different, and possibly much improved, planning treatment for "permanently single-shard tables" if they are indicated by a distribution method (named perhaps 'all' or 'single'), that does not specify a partition column at all.
1. A regular master-only table is arguably also broadcastable, in the same way as a single-shard table; the shard connections can dblink() to the "master node" and reference the regular table; the only difference would be that the table identifier isn't resolved to a shard table identifier during multi-planning. Given the "mostly masterless" aspect of MX, I perceive that Citus is moving in a direction where non-temporary tables must always be "distributed" in some way; non-distributed regular tables will somehow be inaccessible by policy to multi-planned queries. 

Given all of the above, I would rather just have the existing workaround (hash distribute the table, pick whatever partition column you want, choose shard count 1, whatever replication factor you want), until a solution to the larger issues becomes clear.

**Comment by onderkalaci** [comment]
@ozgune I've a question on this:

* Do you think should we `somehow` represent the reference tables on the metadata? I'm asking this because if we go with `number of workers` replication model, we should probably want to keep that during `replicate_table_shards`. What is your thought on that?

**Comment by robin900** [comment]
To clarify my previous thoughts further: This sounds more like a new _distribution method_, named perhaps `'none'`. A none-distributed table _has no partition column_, always has a single shard, and attempts to create more than one shard must fail. A none-distributed table could be colocated with other tables if your colocation feature focuses on ensuring that table shards reside on workers together; or, if the colocation facility wouldn't like it, then forbid the participation of none-distributed tables in colocations. The replication_factor can increase the data's availability on workers for node-local joins and avoid broadcasts.

I'd note that with this additional distribution method:

- Citus provides parity with Redshift's distribution style of `ALL`. (The existing distribution methods cover, and improve on, the other Redshift styles `KEY` and `EVEN`.)
- For any non-temporary table that can fit in its undistributed form on some node of a Citus cluster, there is a viable distribution method; and thus Citus can enforce a policy in future of forbidding any non-temporary table to be undistributed, since keeping it undistributed offers no benefits to an application.

**Comment by ozgune** [comment]
@robin900 -- I'll write a detailed comment on your notes in this issue shortly.

@onderkalaci -- For this issue (#827), providing a wrapper UDF to create a table with shard count = 1 is probably good enough.

For #760, I remember that we decided to add an additional column to ``pg_dist_partition`` to represent the replication model (re: Adding iscluster column to Citus). Could we leverage that column to represent the concept of reference tables?

If we replicate a reference table to all nodes, we're then going to use the "coordinator replication model". If we save the replication factor somewhere, then we could be in good shape. We're also going to expand on our implementation of reference tables in v6.1.

**Comment by metdos** [comment]
> @onderkalaci / @metdos -- For this issue (#827), providing a wrapper UDF to create a table with shard count = 1 is probably good enough. What do you think?

We also want the replication count to be equal to the number of nodes, right?

> We're also planning to expand on our implementation for reference tables in v6.1 (#760). For #760, I remember that we decided to add an additional column to pg_dist_partition to represent the replication model (re: Adding iscluster column to Citus). Could we leverage that column to represent the concept of reference tables?
> 
> If we replicate a reference table to all nodes, we're then going to use the "coordinator replication model". If we save the replication factor somewhere, then we could be in good shape.

Isn't "coordinator replication model" to distinguish between the current replication model from MX replication model. Currently, we set "c" for regular Citus tables. @marcocitus any comments?

We will add a metadata table for co-location, and keep the shard count and replication count there. We can simply infer that shard count = 1 means a reference table.

**Comment by marcocitus** [comment]
> Isn't "coordinator replication model" to distinguish between the current replication model from MX replication model. Currently, we set "c" for regular Citus tables. @marcocitus any comments?

Yep, that model isn't supported by MX, but making a set of single-shard, co-located tables with replication factor 1 actually makes a lot of sense in MX, so preferably we wouldn't prevent that.

**Comment by marcocitus** [comment]
We could actually introduce a new replication model that uses 2PC instead of shard placement state to keep replicas in sync, because that would be the only way we can honour things like foreign keys and not give stale join results. More importantly it would be compatible with MX.

**Comment by metdos** [comment]
> Isn't "coordinator replication model" to distinguish between the current replication model from MX replication model. Currently, we set "c" for regular Citus tables. @marcocitus any comments?
> Yep, that model isn't supported by MX, but making a set of single-shard, co-located tables with replication factor 1 actually makes a lot of sense in MX, so preferably we wouldn't prevent that.

I'm trying to understand the proposal. In this scenario, for reference table, we will have shard count=1 and replication factor = 1. Therefore, for joins, we will need to cache the reference table. Right?

> We could actually introduce a new replication model that uses 2PC instead of shard placement state to keep replicas in sync, because that would be the only way we can honour things like foreign keys and not give stale join results. More importantly it would be compatible with MX.

Here, we will have  shard count=1 and replication factor = n (the number of shards). Therefore, we will need to use 2PC for reference table updates. This will enable us to force foreign keys also with reference tables. Right?

**Comment by marcocitus** [comment]
> I'm trying to understand the proposal. In this scenario, for reference table, we will have shard count=1 and replication factor = 1. Therefore, for joins, we will need to cache the reference table. Right?

If you join with a large table, yes. You could also just join the single shard tables (use them as if they were regular postgres tables).

> Here, we will have shard count=1 and replication factor = n (the number of shards). Therefore, we will need to use 2PC for reference table updates. This will enable us to force foreign keys also with reference tables. Right?

Partially. We need to be careful about foreign keys that modify the reference table.

**Comment by ozgune** [comment]
@metdos -- I had a quick clarification note. We're likely going to improve on reference tables in the v6.1 release. These improvements will include figuring out the replication factor/model for reference tables and supporting foreign keys.

For v6.0, we're planning to provide a simple API to create a reference table. This API in turn will create a distributed table and its shards with a shard count = 1 and the default replication factor we read from config. Does this help clarify things?

**Comment by ozgune** [comment]
@robin900 -- I read through your comments and had a clarification note.

We're planning on providing this api as a starting point and we intend to notably improve on the concept / implementation in our v6.1 release. For example, you mentioned that we could offer more sophisticated features, such as unique or exclusion constraints, for a "permanently single sharded" table ([note 3](https://github.com/citusdata/citus/issues/827#issuecomment-251137198)) We intend to do that as part of #760.

I also agree that this UDF offers a different distribution method. As you mentioned, Redshift calls this method ``ALL``. When we surveyed other distributed database solutions, we found that they referred to these tables as "reference", "replicated", or "dimension". We couldn't find a single name that captures how this table could be used -- for example, we're likely going to replicate this type of tables to all nodes and we were therefore thinking of "replicated". However, Citus replicates all tables so we thought this name was confusing.

Apart from the name, I think you're also noting that rather than introducing a separate UDF, we could make the "reference" table type an argument to the new ``create_distributed_table``. Is that correct?

**Comment by metdos** [comment]
> For v6.0, we're planning to provide a simple API to create a reference table. This API in turn will create a distributed table and its shards with a shard count = 1 and the default replication factor we read from config. Does this help clarify things?

Yes, it does.

**Comment by robin900** [comment]
@ozgune My thoughts were more that the Citus model is lacking a third ('all' or 'none' or 'single') distribution method rather than a reference table concept. If the distribution method were added instead of a "reference table" concept, the challenges related to "reference tables" become clearer and the solutions to those challenges become clearer. And I don't see any challenge being removed or clarified by adding the reference table concept; perhaps I am misunderstanding what your reference table implementation will do.

I consider how Citus might behave for reference tables with the 'all' method available:
- Such tables have no partition column, and neither Citus code nor Citus users will be tempted to misunderstand that a partition column exists and is somehow meaningful.
- Such tables can never have more than one logical shard, and Citus can enforce that invariant simply by checking the distribution method for the table.
- Users clearly see, up front, the benefits and restrictions of hash-distributed vs. all-distributed: partition column needed or not, foreign key references to the table dependent on partition column and relationships with referencing tables, or instead are unrestricted (except for replication requirements) because there's no partitioning.
- Such tables are easily targeted by shard management code or techniques: "first, when you add a new worker, replicate every 'all'-distributed table to the new worker first; then address the other tables via colocation groups."
- Such tables make other possible decisions clear: would you like to declare that Citus only supports single-shard tables that are replicated to all workers, and never allows the user to define an all-distributed table with a replication_factor less than num_workers? Or would you like to allow an all-distributed table with replication_factor = 1 in some cases? This decision impacts whether FK constraints are possible, and under which conditions. Adding a reference table concept does not remove the need for such decisions, and if the reference table concept actually implies a particular decision, the decision can simply be made without the reference table concept.

**Comment by robin900** [comment]
@ozgune I look forward to trying out the reference table API and seeing how it works.

I'm thinking about the differences between a reference table that is 

- a hash-distributed table, with an arbitrary partition column, and created with a single shard; and
- an "all-distributed table", with no partition column, and a single shard.

I grant that there's not much difference between the two in terms of query planning or DML, given the current capabilities of Citus. But it occurs to me that a big difference would appear...if Citus's design allows a hash-distributed table to be changed after creation to increase its shard count. Reading the documentation, it seems that current Citus does not allow a hash-distributed table to have its shard count changed after the initial shard(s) are created via `master_create_worker_shards`. However, I can imagine writing my own code that works on a single-shard hash-distributed table and redistributes its data into two shards, with a new logical shard in pg_dist_shard and a new placement for that shard in pg_dist_shard_placement. And I can imagine a future Citus Enterprise offering that reorganizes distributed tables on the fly to have a larger shard count.

So I guess my thinking is that if there is a new "all"/"none"/"single" distribution method, it prevents subsequent management of the table in ways that erroneously think its hash distribution method means that it's actually hash-distributable.

**Comment by ozgune** [comment]
@robin900 -- I think what we have in mind with a "reference table" aligns closely with an "all" distribution method. I'll first open a new issue that captures our plans for a proper implementation of reference tables in v6.1. I'll then update this comment with a detailed reply in 1-2 days.
