### ISSUE TITLE
Missing cstore_fdw from YUM on Amazon CloudFormation

### ISSUE THREAD

**Issue by habibc** [citusdata/citus#842]
Install a stack using CloudFormation template for citus-5.2.1 fails with error:

> Output: Could not determine package contained by rpm at https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-6-x86_64/pgdg-ami201503-95-9.5-2.noarch.rpm Could not determine package contained by rpm at https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-6-x86_64/pgdg-ami201503-95-9.5-2.noarch.rpm cstore_fdw_95 is not available to be installed Error encountered during build of PackagesAndCommands: Yum does not have cstore_fdw_95 available for installation -----------------------BUILD FAILED!------------------------ Unhandled exception during build: Yum does not have cstore_fdw_95 available for installation

Would you please take a look?

**Comment by sumedhpathak** [comment]
Can reproduce. It appears the repo itself: https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-6-x86_64/pgdg-ami201503-95-9.5-2.noarch.rpm is missing. We kept a copy of the repo previously in our own S3 bucket, which we changed to point to a PostgreSQL repo: https://github.com/citusdata/cloudformation/commit/1e56cd73140be7eee5a933d88921f0f24e144ad3. 

Running manually, I get this:
```
[ec2-user@ip-10-169-152-33 ~]$ sudo yum install https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-6-x86_64/pgdg-ami201503-95-9.5-2.noarch.rpm
Loaded plugins: priorities, update-motd, upgrade-helper
Cannot open: https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-6-x86_64/pgdg-ami201503-95-9.5-2.noarch.rpm. Skipping.
Error: Nothing to do
```

**Comment by jasonmp85** [comment]
I think the `2` just needs to be bumped to a `3`. I had thought they kept previous versions around, but maybe not.

I'll update the template shortly.

**Comment by jasonmp85** [comment]
So this ended up being a little bit of a rabbit hole…

Basically, there was a confluence of issues all around last week. As noted above, the `download.postgresql.org` rpm file was removed. Simply changing it to `-3` sets up the repo correctly; however…

Amazon added PostgreSQL 9.5 to its own repositories last week, which it has configured at a _very_ high priority. So even with the PGDG repo RPM fixed, we end up with an Amazon-packaged PostgreSQL 9.5. Which puts its binaries in the wrong place, breaking all our scripts.

I first wrote some scripts to set all repo priorities to what we want, but ultimately decided just hardcoding the priorities in repo configuration files we ourselves maintain and host would avoid this kind of problem in the future (i.e. having PGDG remove a repo config RPM we were using without notifying anyone).

_However…_

It turns out our use of EPEL is problematic. It fails non-deterministically if a bad mirror is selected (the `fastestmirror` `yum` plugin is enabled. This is pretty annoying if it occurs at the end of the formation creation (for instance during the master node creation). So I'm exploring paring down some of those pieces. Will update shortly!

**Comment by anarazel** [comment]
On 2016-10-05 16:11:24 -0700, Jason Petersen wrote:
> It turns out our use of EPEL is problematic. It fails non-deterministically if a bad mirror is selected (the `fastestmirror` `yum` plugin is enabled. This is pretty annoying if it occurs at the end of the formation creation (for instance during the master node creation). So I'm exploring paring down some of those pieces. Will update shortly!

Just to clarify: That's not a new issue though, right?

**Comment by jasonmp85** [comment]
> Just to clarify: That's not a new issue though, right?

I didn't know about it, though it's probably not new. It make verifying my changes very difficult as the error message it produces is identical to other repo problems (_yum makecache failed_ or whatnot).
