### ISSUE TITLE
Add `colocate_with` option to create_distributed_table()

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#847]
This is related to #846.

On `create_distributed_table()` we want to add a `colocate_with` option which enables users to override the default inferred behaviour. 

---

Some of the questions that @ozgune asked previously:

 I have a clarification question on the `colocate_with` option. What do we use as the default value for `colocate_with`?

Looking at how this option could be used, we have three scenarios:
1. Default value. In this mode, we colocate the distributed table based on column type, shard count, etc. Is the default in this case then `colocate_with => ''` or `colocate_with => 'all'` (a reserved identifier that signals to colocate with all other tables)?
2. User explicitly specifies the table to colocate with. This one's easy.
3. User asks to _not_ colocate this table with others. In this mode, do we use `colocate_with => ''` or `colocate_with => 'none'` (a reserved identifier that signals to colocate with nothing)?

---

Based on our last meeting:

Note that each default (shard count, replication factor and data type) triplet has a single `DEFAULT` colocation configuration. 

I'd expect that we pick the first table as being part of the `DEFAULT` colocation configuration for  (shard count, replication factor and data type) triplet.

We probably need a new column on `pg_dist_colocation` name `default`, which is boolean column. It is only true for a single unique (shard count, replication factor and data type) triplet. For the others, the default column is false.

We may even provide a **very low level** UDF to change that `SELECT mark_default_colocation(colocationId)` which simply updates the default (shard count, replication factor and data type) triplet. 

This is just a safety belt in case a user starts with a non-default co-location configuration and then switches back to the default colocated configuration. Another use-case could be that user implements a new use case and expects his new tables to be colocated with each other by default, without specifying the `colocate_with` option.

---

**Comment by metdos** [comment]
> colocate_with => 'all' (a reserved identifier that signals to colocate with all other tables)?

I think that  colocate_with => 'all' means "create a reference table". Therefore, I'm keeping 'all' option out of the scope of this issue. Or do we want to create reference tables also with create_distributed_table() UDF?

**Comment by metdos** [comment]
I think @onderkalaci has a good summary of what to be implemented above. Here is what I'm planning to implement with minor updates above.

**1- Default option:**

This is the current behavior of the distributed colocated table creation. If there is a collocation group with the same configuration, use it. Otherwise, create a new colocation group. Both of following two options will be implemented:

i. Provide colocate_with => '' 
```sql
select create_distributed_table('orders', 'o_orderkey', colocate_with => '');
```

ii. Or does not provide colocate_with at all and use '' as the default value.
```sql
select create_distributed_table('orders', 'o_orderkey');
```
**2- Colocate with a specific table**

Colocate with the given table. If not possible, error out.
```sql
select create_distributed_table('orders', 'o_orderkey', colocate_with => 'lineitem');
```
**3- Create a new colocation group**

Without checking if there is a colocation group for the colocation configuration, create a new configuration group.
```sql
select create_distributed_table('orders', 'o_orderkey', colocate_with => 'none');
```


**Default group selection**

Now, with the introduction of colocate_with => 'none', we may have different colocation groups with the same configuration. Therefore, there is the question of which colocation group to chose for the default table creation. We are planning to solve this problem by adding a new column (default_group) to pg_dist_colocation to differentiate default colocation group from others. The first group created for the same configuration will be the default colocation group and we may provide a UDF, mark_default_colocation(colocationId), to change the default group.

@ozgune, how does this sound? Any comments?

**Comment by ozgune** [comment]
I'm noting #694 and #695 as related issues for documentation purposes.

**Comment by ozgune** [comment]
@samay-sharma, @saicitus, and I just looked at this api proposal. Here's a summary of our conversation.

* We all agreed that ``colocate_with -> ''`` could signal that the current table shouldn't be colocated with any of the other tables. We therefore decided to use ``colocate_with -> 'default'`` to provide the default colocation behavior. (Section 1: Default option)

* For ``colocate_with => 'none'``, @saicitus asked if we should change the parameter to ``''``. @samay-sharma said that this value would be ambiguous. He had a minor suggestion for ``nothing`` instead of ``none``. I'm cool with both ``nothing`` or ``none``. (Section 3: Create a new colocation group)

These decisions also mean that our users can't create distributed tables with the name ``none`` (or ``nothing``) and override the default colocation behavior.

**Comment by metdos** [comment]
@ozgune, @samay-sharma, @saicitus 

I updated my comment https://github.com/citusdata/citus/issues/847#issuecomment-259300740 above to reflect our meeting at SF. I'm going to implement it. Let me know if I missed anything.

**Comment by begriffs** [comment]
Requires documentation in https://github.com/citusdata/citus_docs/issues/226

**Comment by aamederen** [comment]
For this, we may consider disallowing colocation of mx and non-mx tables. We have discussed this with @metdos and @marcocitus and found these problems with colocation of mx and non-mx tables:

- In foreign keys, an mx table cannot refer to a non-mx table, since the distributed table of non-mx table will not exist in the worker. Can this be solved by not propagating the foreign key constraints to distributed tables on workers and let shards handle the FK constraints?
- Since it is not possible to change the replication factor of an mx table, changing the replication factor of a non-mx table would break the colocation with the non-mx table. This can also be solved by erroring out if a colocated mx table exists.

If we go that way, then the question of differentiating different colocation groups of mx and non-mx tables arises. One possible way to hande this could be adding a new `repmodel` column to `pg_dist_colocation` and instead of searching for (shard_count, replication_factor), we can search for (shard_count, replication_factor, replication_model).

@marcocitus, @metdos what do you think? Were there other reason for disallowing mx and non-mx tables?

**Comment by metdos** [comment]
> One possible way to hande this could be adding a new repmodel column to pg_dist_colocation and instead of searching for (shard_count, replication_factor), we can search for (shard_count, replication_factor, replication_model).

I think that this is the proper way to follow. However, there is a discussion here https://github.com/citusdata/citus/pull/1012#issuecomment-266675565 about changing metadata in minor releases. @marcocitus, do you have any comment on that?

**Comment by marcocitus** [comment]
I think adding `repmodel` to `pg_dist_colocation` makes sense if we're ok with metadata changes in this release. I'd like to start viewing pg_dist_colocation as a table of 'distributed table configurations' and each configuration should have its own entry (at some point it might make sense to remove the GUCs and their strange side-effects and allow you to create a configuration with one existing by default).

**Comment by metdos** [comment]
We had a meeting with @ozgune and @marcocitus, and decided to decouple the implementation of this feature from the minor-major release decision. This effectively means not updating the metadata tables (pg_dist_colocation).

We agreed that there will be some side effects but they are ok for now. These are:

- We will have only default configuration groups in pg_dist_colocation and we will not add a new configuration group if the user creates a new table with colocate_with => 'none'.
- We will not add mark_default_colocation(colocationId) udf, and the user will not be able to change default configuration group.
- We will not allow a configuration group to have different replication models. If the user tries to create a new table with an already existing configuration group but with a different `repmodel`, we will error out.

Update requirements;

**1- Default option:**

This is the current behavior of the distributed colocated table creation. If there is a collocation group with the same configuration, use it. Otherwise, create a new colocation group.

i. Provide colocate_with => 'default' 

``` sql
select create_distributed_table('orders', 'o_orderkey', colocate_with => 'default');
```

ii. Or does not provide colocate_with at all and use 'default' as the default value.

``` sql
select create_distributed_table('orders', 'o_orderkey');
```

**2- Colocate with a specific table**

Colocate with the given table. If not possible, error out.

``` sql
select create_distributed_table('orders', 'o_orderkey', colocate_with => 'lineitem');
```

**3- Create a new colocation group**

Create a new colocation group id, but don't add a line to pg_dist_colocation.

``` sql
select create_distributed_table('orders', 'o_orderkey', colocate_with => 'none');
```

**Comment by aamederen** [comment]
> `select create_distributed_table('orders', 'o_orderkey', colocate_with => 'default');`

Is there any chance that someone creates a table named "default" with `CREATE TABLE "default" (a int, b int);`. 

Spoiler Alter: It works :smile:

**Comment by metdos** [comment]
> Is there any chance that someone creates a table named "default" with CREATE TABLE "default" (a int, b int);.

There is always a theoretical chance, but we ignore it. If they insist, they can provide table name in schema-qualified way.
