### ISSUE TITLE
Prepare upgrade logic for existing users

### ISSUE THREAD

**Issue by byucesoy** [citusdata/citus#849]
As you guys know we are introducing explicit co-location concept in new release and we also add new metadata information. However some of existing users' clusters may not be completely ready for using explicit co-location directly and to do soit is required to do some manual operations in clusters. This issue is for deciding how and what will we provide to make these operations easy and sane as possible.

I think general consensus about upgrade is asking existing users who benefit from colocation to explicitly call a user-defined function during an upgrade. If you guys want to know about previous discussion, here are some highlights;

@onderkalaci and @samay-sharma had some brainstorming about the issue before;

@onderkalaci:
In summary, colocation would look like the following:

- Table colocation will be represented as a new column on pg_dist_partition, called `colocationid`
- Tables which have co-located placements are given the same colocation id.
- There'll a be new sequence, called pg_dist_colocation_id_seq, to generate the new colocation ids when necessary.
- All non-hash partitioned tables and tables without any shards will have INVALID_COLOCATION_ID which is 0. This would mean that do not apply colocation for those tables, and, they would basically work as pre 5.3.

Upgrade path:

- This is the [README ](https://gist.github.com/onderkalaci/b6547eb54cc68f86f08fbf1a54ddec79) file that includes the high-level and low-level functions that are applicable. Note that, the user would be able to dry run the actual upgrade function as described [here](https://gist.github.com/onderkalaci/b6547eb54cc68f86f08fbf1a54ddec79#file-readme-sql-L21)(which is the default). Basically, the user would be able to see psudo_ids instead of the actual ids, but, the output which includes all the colocated tables would be the same.
- This is the [file](https://gist.github.com/onderkalaci/b6547eb54cc68f86f08fbf1a54ddec79#file-update_table_colocation-sql) that includes the upgrade functions. The user simply needs to copy & paste the file to psql.
- Another important API function is [tables_have_colocated_placements(src_table, dest_table)](https://gist.github.com/onderkalaci/b6547eb54cc68f86f08fbf1a54ddec79#file-readme-sql-L20). Here is an [example](https://gist.github.com/onderkalaci/b6547eb54cc68f86f08fbf1a54ddec79#file-readme-sql-L159) usage.
- There are good number of tests which you can check [here](https://gist.github.com/onderkalaci/b6547eb54cc68f86f08fbf1a54ddec79#file-readme-sql-L24)
- Missing parts: I probably need to do some more testing and add some extra checks such that some UDFs should be called only for hash-partitioned tables, which could be called for non-hash partitioned tables for now.
- I plan to leave this process manual (i.e., not part of upgrade script). In other words, when a user upgrades to Citus 5.3, he'll get all tables to have INVALID_COLOCATION_ID . Then, if the user wants to have the co-location features, he can call the upgrade UDF. What do you think about that?

And @samay-sharma's feedback;

- The name of the function seems a bit low level to me (i.e. as a user I wouldn't know / wouldn't want to know what colocation id is). Once I saw colocation id in the name of the function, I felt that I had to understand what it was, what it represents, how it would be updated etc. which took some time.

I'll need to think more about better naming but maybe something like mark_tables_as_colocated?

- The behavior of the parameter dry_run wasn't very clear to me from the name / or the function comment at the outset. I had to read a bit and then understand what it was trying to do.

From what I understand now, it just outputs what tables will be marked as colocated as NOTICE messages and doesn't update pg_dist_partition. Is that right?

If so, could we rename the parameter as something on the lines of display_only / explain_only(?) or the like. (Definitely needs more thought :))

- Could we rename tables_have_colocated_placements to something like tables_are_colocated?

I think placements are a lower level concept which become relevant only when you're using Citus's current replication model. So, maybe we can avoid it in the higher level API?

- Could we call the table names in the tables_have_colocated_placements as table1 and table2 or something like that? The tables are equivalent in the way we approach them and calling them as source and destination gives an impression that they may not be.

- This may not need to be done at the code level, but I'm thinking if we should call colocation id as colocation group id or something which makes it clearer as to what a colocation id represents (An id for every group of tables which are colocated together).

**Comment by byucesoy** [comment]
Also related with #694 and #695

**Comment by byucesoy** [comment]
Also this issue is related with #694 and #695

**Comment by metdos** [comment]
Hey @ozgune, I have some high-level questions about requirements of this functionality:

i. Do we need shard move functionality? Or are we planning to just check if shard placements are colocated and error out if they aren't?

ii. Should API take two tables or multiple ones?

a. make_colocated_tables(sourceTable, targetTable)

b. make_colocated_tables(ARRAY[table1, table2, table3 ...])

iii. What is the expected result of the UDF?

a. For make_colocated_tables(sourceTable, targetTable)
- If sourceTable is in INVALID_COLOCATION_ID group, then create a new colocation group and assign both tables to same colocation group.
- Otherwise, add target table to colocation group of the source table.

b. For make_colocated_tables(ARRAY[table1, table2, table3 ...])
- Create a new colocation group, and assign all tables to this collection group.
- One question is that if we have a table such as tableX colocated with table3. When we colocate table3 with other tables, should we also move tableX to this new colocation group?

The questions is that if we call make_colocated_tables(ARRAY[table1, table2, table3]), should **X** be 2 or 3?

|Table Name | Colocation Group Before Upgrade | Colocation Group After Upgrade | 
| :--- | :--- | :--- | 
|table1|0|3| 
|table2|1|3| 
|table3|2|3| 
|tableX|2|**X**| 



iv. Should we create a SQL script or a C function?

v. Do we need dry-run functionality?

**Comment by metdos** [comment]
I'm planning to go with the simple solution ii.a mark_tables_colocated(sourceTable, targetTable), and don't move any shards and error out if two tables are not colocated already.

The user can pick a default table for every colocation group, and move all other tables into this group one by one. I'm planning to implement this as a SQL script, so we can provide it as a part of upgrade steps. Also, I'm planning to skip dry-run functionality because it is easy to change colocation groups with this API (Onder mentioned that the purpose of dry-run was to check movements which I don't plan to include).

Any objections?

**Comment by onderkalaci** [comment]
I think your suggestion makes sense. We could even come up with a simple SQL query that marks multiple (or all) table co-located in a single step.

**Comment by metdos** [comment]
Working on this a bit more and also talking with @onderkalaci and consulting to @sumedhpathak, we have decided to go with UDF approach. The PR is almost ready and I will create it tomorrow morning, and hopefully merge tomorrow.

We picked the UDF approach because of 
i. Code will be cleaner
ii. Also, these UDFs can be used for purposes other than upgrade process. Especially after colocate_with option is introduced to switch colocation groups between similar colocation configurations.

**Comment by metdos** [comment]
Just adding a note about the merged implementation.

Possible use-cases of mark_tables_colocated()

i. Upgrade from Citus 5.x to Citus 6.0. After the default upgrade process, all tables will have invalid colocation id. mark_tables_colocated() can be used to add colocation groups.

ii. We added create_distributed_table(), but didn't remove master_create_distributed_table() yet. Therefore, if somebody uses master_create_distributed_table() to create new tables, they can use mark_tables_colocated() to add colocation groups.

iii. We will add colocate_with option to create_distributed_table() in Citus 6.1 release cycle. This means, there would be different colocation groups with the same configuration, and mark_tables_colocated() can be used to moved tables from one colocation group to another colocation group.

How does it work?

mark_tables_colocated(source_table_name regclass, target_table_names regclass[])

It first checks if the source_table has a colocation group. If it does not, it creates a new one. Then, it moves all target tables to colocation group of the source table if they pass these colocation checks:

* Shard counts are same,
* Shard intervals match
* Matching shard intervals have the same number of shard placements
* Shard placements are colocated (on the same node)
* Shard placements have the same health states

How can it be used?

mark_tables_colocated('lineitem', ARRAY['orders']);
