### ISSUE TITLE
Provide UDF to map row/distribution column's value to shard

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#872]
Citus shard incoming queries by applying the following steps: (a) resolve the column's data type, (b) looks up that type's hash function in PostgreSQL, and (c) hash the value and compare it against the hash token ranges in the shard metadata tables.

Since Citus handles all sharding related operations, users don't need to know about this logic. Still, a few power users asked about mapping row/distribution column's value to shard for their internal debugging purposes.

An example question email thread: https://groups.google.com/forum/#!topic/pg_shard-users/ZXknsxutDAU

We also had email threads where we provided the following method -- I think the following technique  produces _incorrect_ results since it ignores signedness btw; we do a bitwise and in our hash regression tests to produce correct results: `select p.shardid as shard_id from pg_dist_shard s where s.logicalrelid='<table_name>'::regclass and hashint4(<value_of_the_column>)=s.shardminvalue::integer and hashint4(<value_of_the_column>)<=s.shardmaxvalue::integer;`

We should implement an internal UDF to map row/distribution column's value to a shard.

**Comment by begriffs** [comment]
Requires documentation in https://github.com/citusdata/citus_docs/issues/225

**Comment by byucesoy** [comment]
There are few points we need to decide on before implementing these.

1-) Should this function also support append and range distributed tables?

I think it is not difficult to support those. I just want to confirm. If yes, we will return shard id array instead of single shard.

Also we are adding new distribution type for reference tables, but it is a trivial case since there is single shard already.

2-) Do we have decided on any name for UDF? Some suggestions;

*map_value_to_shard
*shard_id_from_value
*get_shard_id

**Comment by ozgune** [comment]
@byucesoy - We quickly talked about this and I'm adding our notes.

>> 1) Should this function also support append and range distributed tables?

We think it doesn't needs to. In particular, @samay-sharma noted that this function is more relevant for multi-tenant deployments and if the function returned an array, it would introduce confusion.

>> 2) Do we have decided on any name for UDF? Some suggestions.

Could you quickly review the Citus codebase to see what names would be consistent with our UDF names? In particular, these names sound a bit generic. Do we want to include "distribution value" to be more specific?

Also, could you provide a few alternatives for full udf signatures -- with arguments and argument types? We're gusessing the naming will also become clearer with arguments passed into the function.

**Comment by byucesoy** [comment]
Constrast to our C codebase, for SQL UDFs we use get keyword in our functions which return some information. Therefore, in my opinion, get_distribution_value_shardid  or get_shardid_from_distribution_value are good candidates.

This function should take a distributed table name and a distribution value so that it will return a shard id which belongs to given table and contains given value. Full signature should be something like;

```c
int8 get_distribution_value_shardid(table_name regclass, value anyelement)
```

I think that UDF should take a distributed table name and a value.

**Comment by ozgune** [comment]
@byucesoy / @samay-sharma -- what do you think about renaming this function to ``get_shardid_for_distribution_value()`` or ``get_shardid_for_distribution_column``?

**Comment by samay-sharma** [comment]
I thought about it for a bit. Ideally, I think I'd like `get_shardid_for_distribution_column_value`, but it does seem too long.

Given that in mind, maybe we pick `get_shardid_for_distribution_column`? I think it is more inline with our docs.
