### ISSUE TITLE
EXPLAIN EXECUTE causes segmentation fault

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#886]
To reproduce:
```
CREATE TABLE test (x int, y int);
SELECT master_create_distributed_table('test', 'x', 'hash');
SELECT master_create_worker_shards('test', 8, 2);
PREPARE foo AS INSERT INTO test VALUES (1, 2);
EXPLAIN EXECUTE foo;
```

**Comment by lithp** [comment]
This will be tricky to deal with. The problem is in [ExplainOneQuery](https://github.com/postgres/postgres/blob/master/src/backend/commands/explain.c#L332) from postgres:

```
static void
ExplainOneQuery(Query *query, IntoClause *into, ExplainState *es,
				const char *queryString, ParamListInfo params)
{
	/* planner will not cope with utility statements */
	if (query->commandType == CMD_UTILITY)
	{
		ExplainOneUtility(query->utilityStmt, into, es, queryString, params);
		return;
	}

	/* if an advisor plugin is present, let it manage things */
	if (ExplainOneQuery_hook)
		(*ExplainOneQuery_hook) (query, into, es, queryString, params);
	else
	{
		PlannedStmt *plan;
		instr_time	planstart,
					planduration;

		INSTR_TIME_SET_CURRENT(planstart);

		/* plan the query */
		plan = pg_plan_query(query, into ? 0 : CURSOR_OPT_PARALLEL_OK, params);

		INSTR_TIME_SET_CURRENT(planduration);
		INSTR_TIME_SUBTRACT(planduration, planstart);

		/* run it (if needed) and produce output */
		ExplainOnePlan(plan, into, es, queryString, params, &planduration);
	}
}
```

We set `ExplainOneQuery_hook` however `EXECUTE` is a utility statement and caught by `ExplainOneUtility`. `ExplainOneUtility` looks up the cached plan but then calls `ExplainOnePlan` on it directly instead of calling back out to our hook. We're skipped entirely.

Some solutions:
- I haven't looked into why it crashes, maybe we can change the plans we emit so postgresql doens't choke on them
- multi_ProcessUtility catches `EXPLAIN` queries, we can special case `explain execute`

**Comment by marcocitus** [comment]
Ah, I vaguely remember this now. https://github.com/citusdata/citus/pull/414#r60610196

Yes, looks like we'd need to fix this in PostgreSQL.

**Comment by lithp** [comment]
This appears to happen because [`ExplainOnePlan`](https://github.com/postgres/postgres/blob/master/src/backend/commands/explain.c#L436) calls `ExecutorStart` which usually hits `standard_ExecutorStart` which eventually calls [`InitPlan`](https://github.com/postgres/postgres/blob/master/src/backend/executor/execMain.c#L778) which [sets some state](https://github.com/postgres/postgres/blob/master/src/backend/executor/execMain.c#L959) `ExplainOnePlan` later assumes exists. However, since this is a Citus plan we call the router executor and [never call `standard_ExecutorStart`](https://github.com/citusdata/citus/blob/master/src/backend/distributed/executor/multi_executor.c#L163). `ExplainOnePlan` crashes, I believe, because `InitPlan` is never called.

**Comment by lithp** [comment]
Is there a reason we never call `standard_ExecutorStart` if this is a router query? I seem to remember we used to call it, that might be why this used to work.

**Comment by marcocitus** [comment]
I guess it wasn't called for single-shard queries in pg_shard, but I don't know why. Now I'm a bit worried about the fact that we're not calling it, because it seems like we're not properly initialising the executor state and we might not take appropriate table locks either.

@anarazel , @jasonmp85 any thoughts?

**Comment by anarazel** [comment]
@marcocitus Yea, I think that's the reason. I think that's really a bad idea, and IIRC mentioned that during the integration, but we didn't want to change more than necessary...

**Comment by anarazel** [comment]
On 2016-10-25 02:55:17 -0700, Marco Slot wrote:
> I guess it wasn't called for single-shard queries in pg_shard, but I
> don't know why. Now I'm a bit worried about the fact that we're not
> calling it, because it seems like we're not properly initialising the
> executor state and we might not take appropriate table locks either.

Yea, I think that's the reason. I think that's really a bad idea, and
IIRC mentioned that during the integration, but we didn't want to change
more than necessary...
