### ISSUE TITLE
Use full libpq connection strings to configure Citus

### ISSUE THREAD

**Issue by fdr** [citusdata/citus#947]
Right now, Citus hard-codes how the connection string used to connect to another database is created, allowing host and port specification only.  Citus's current design assumes that it, somehow, can connect to other nodes without any apparent authentication.

This is cumbersome and carries usability problems and security risks when used in conjunction with other libpq-using functionality, e.g. dblink.

That is because when one is using authentication (in my case: passwords, and TLS hostname authentication) one must use `libpq`-universal features to get around Citus not allowing configuration of that connection string directly. An example would be use of `.pgpass` and the environment variable `PGSSLROOTCERT`. These settings are applied to all uses of libpq in a Postgres server.

Here are some scenarios to get a sense of what can happen:

* ~~~dblink allowing escalation to superuser without a password to any other citus cluster member.~~~
* TLS connections to other databases failing because they are not installed in the configured TLS trust chain.
* Similar issues with postgres_fdw

One possible fix would be to introduce a super-user only visible column that has "additional" connection information for each node that is mixed in the two call sites where Citus uses `CONN_INFO_TEMPLATE`.   That way `dblink` and `postgres_fdw` won't have access to/be affected by these libpq-universal approaches.

The reason that column must be censored from other users in the system is that it is liable to contain passwords.  In addition, a superuser connection string needs to be supplied as well, as the Citus extension makes use of that for things like dropping tables.

**Comment by marcocitus** [comment]
This would probably involve adding something like a pg_dist_user or pg_dist_connection_info table containing credentials and/or connection settings for different users for each of the nodes/groups. It would maybe be 1-2 weeks of work.

I think this is worth solving because of the operational complexity of maintaining a dynamically changing text file that needs to be in sync with the distributed database, though I don't immediately see how the current situation creates a security problem for dblink and postgres_fdw. 

> - dblink allowing escalation to superuser without a password to any other citus cluster member.
> - Similar issues with postgres_fdw

Only superuser can use .pgpass with dblink and postgres_fdw, regular users are *required* to provide a password in the connection string / server options and thus don't use .pgpass. An exception is if you explicitly grant users access to dblink_connect_u, but there seems to be no reason to do that and it's certainly not something you should ever do in a production environment. If you need to connect to a Citus worker via dblink, then you can simply specify an inline password in dblink_connect as always.

It's possible that relying on global settings inadvertedly enables some other (future) extension or function to make connections in unintended ways, but postgres_fdw and dblink are designed to deal with this specific situation.

> - TLS connections to other databases failing because they are not installed in the configured TLS trust chain.

I guess you could work around that by specifying sslmode=require (or lower) in dblink connection strings or postgres_fdw server options?

**Comment by fdr** [comment]
> Only superuser can use .pgpass

Incorrect? You have two choices of symbols to make use of dblink connections, `dblink_connect` and `dblink_connect_u`. The former's manual page says: `Only superusers may use dblink_connect to create non-password-authenticated connections. If non-superusers need this capability, use dblink_connect_u instead.`

If you look at the latter, as the manual suggests, it says:

`If the remote server selects an authentication method that does not involve a password, then impersonation and subsequent escalation of privileges can occur, because the session will appear to have originated from the user as which the local PostgreSQL server runs. Also, even if the remote server does demand a password, it is possible for the password to be supplied from the server environment, such as a ~/.pgpass file belonging to the server's user. This opens not only a risk of impersonation, but the possibility of exposing a password to an untrustworthy remote server. Therefore, dblink_connect_u() is initially installed with all privileges revoked from PUBLIC`

Unless you know of a symbol that is not `dblink_connect` or `dblink_connect_u` that performs a similarly crucial function, that leaves you with zero options for use of dblink.

> I guess you could work around that by specifying sslmode=require (or lower) in dblink connection strings or postgres_fdw server options?

You might think so, but try installing a `root.crt`, e.g. `touch ~/.postgresql/root.crt` will prevent you from connecting to any database with `sslmode=require` for me. You will get the same result for any trust chain that doesn't include whatever server you are connecting to, of which the empty file is zero such chains.

**Comment by marcocitus** [comment]
> You might think so, but try installing a root.crt, e.g. touch ~/.postgresql/root.crt will prevent you from connecting to any database with sslmode=require for me. You will get the same result for any trust chain that doesn't include whatever server you are connecting to, of which the empty file is zero such chains.

Uff, that is a problem. I guess we would want to set sslrootcert on all connections to workers. As a quick (1-2 day) fix, would it help if we added a GUC for injecting a partial connection string into Citus connections? e.g.

```
citus.node_connection_parameters = 'sslrootcert=/citus/worker/root.crt sslmode=verify-ca'
```

This doesn't prevent us from also introducing a separate authentication table/file, and would provide immediate relief for this issue and a couple of other ones.

**Comment by fdr** [comment]
On Fri, Nov 4, 2016 at 9:27 AM Marco Slot <notifications@github.com> wrote:

> You might think so, but try installing a root.crt, e.g. touch
> ~/.postgresql/root.crt will prevent you from connecting to any database
> with sslmode=require for me. You will get the same result for any trust
> chain that doesn't include whatever server you are connecting to, of which
> the empty file is zero such chains.
>
> Uff, that is a problem. I guess we would want to set sslrootcert on all
> connections to workers. As a quick (1-2 day) fix, would it help if we added
> a GUC for injecting a partial connection string into Citus connections? e.g.
>
Hmmm. It might not help enough relative to taking a bit longer to solve the
problem in one consistent way (the out-of-line table), provided we think
we're going to do it within six months.

There are some advantages to this approach outside its expeditiousness,
like the fact that it applies to all citus connections: this might be able
to clean up some configurations rather than engendering duplication. But if
one is to add it, I think it should be on its own merit.

**Comment by ozgune** [comment]
@fdr / @marcocitus / @craigkerstiens -- we're going to talk about this in our v6.1 reprioritization sync-up. Is my understanding of this thread accurate?

* We had three motivations for #947. The primary one was using dblink without needing to be super-user. @fdr then realized that we use dblink today without making this change.
* For the two other motivations, @marcocitus proposed a quick workaround (1-2 days). @fdr noted that if we are going to make this change, we may want to spend more time on it and do it the right way (1-2 weeks).

For our v6.1 meeting tomorrow, how important are the two other motivations for Citus Cloud? (low, medium, or high)

**Comment by fdr** [comment]
Medium. It's somewhat important and I'd like to see it solved within six
months, but it's not worth a hasty fix.

**Comment by marcocitus** [comment]
@ozgune Should we include this in the next release? I think we'll probably want to a number of metadata changes for HA as well.

**Comment by ozgune** [comment]
@fdr -- Is using full libpq connection strings to configure Citus still important to you?

**Comment by fdr** [comment]
On Thu, May 11, 2017 at 1:05 AM Ozgun Erdogan <notifications@github.com>
wrote:

> @fdr <https://github.com/fdr> -- Is using full libpq connection strings
> to configure Citus still important to you?
>
Yeah.

**Comment by marcocitus** [comment]
@fdr Would you want to be able to set the connection string per user or per node?

**Comment by fdr** [comment]
Per node. What would be the advantage of a per user setting?

Also as a reminder, connection strings can have passwords, so take a little
care with not making that over-visible.

**Comment by lithp** [comment]
@fdr one more question :)

The current plan is for `pg_dist_node` to keep `nodename` and `nodeport` and gain an extra superuser-visible column called `connopts`. The connection string when connecting workers would then be `"host=$nodename post=$nodeport $connopts"`. Does this work for you?

**Comment by fdr** [comment]
That does work.

**Comment by lithp** [comment]
@fdr, @marcocitus , and I had a meeting last week to talk about this. Adding notes on what we decided and tagging them so they can make any objections to my summary:

There are two driving use-cases:
- Specify tls settings for connections
- Specify passwords without managing a `.pgpass` file

With two respective solutions:
- For the first one adding a `connopts` column to `pg_dist_node` is sufficient. 
- For the second one we want a `pg_dist_user` which maps from `(host, port, database, user) -> (pass, connopts`

To be useful both of these need to be propagated to the workers, since the workers also open connections to each other. Although, now that I'm thinking about it here, it's probably also possible to refactor `worker_data_fetch_protocol.c` and pass connection strings to the workers.

**Comment by jasonmp85** [comment]
See #2019 for how we're planning to (finally) tackle this!

**Comment by sumedhpathak** [comment]
@jasonmp85 Can we close this issue now?

**Comment by jasonmp85** [comment]
Yes, between `node_conninfo`, `authinfo`, and `poolinfo`, users have a lot of options (in Enterprise, at the very least).
