### ISSUE TITLE
INSERT INTO ... SELECT error message needs to be more informative

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#949]
We're going to have ``INSERT INTO ... SELECT`` available with our upcoming release.

For example, let's say the user runs the following steps.

1. Create distributed table t1(a int, b int), populate table
2. Create distributed table t2(a int8, b int8)
3. Insert Into t2 Select * From t1;

We then display the following error message:

<pre>
ERROR:  SELECT query should return bare partition column on the same ordinal position as the INSERT's partition column
</pre>

We should revise this error message to be more informative.

**Comment by onderkalaci** [comment]
I was supposed to open this issue but ran a bit late. Let me update the issue with my understanding and some details.

First, some discussion on this on the testing document:

@onderkalaci says
>  I agree that the error message is confusing but that's correct :) Because, there is an implicit casing function call on the partition column (i.e., int is converted to int8), we error out as it doesn't return the bare partition column. But, we could consider to improve the message.

and @ozgune replies with the following:

> I've been working on Citus for years, and I don't understand what this means. :) Could we revise this error message so that it's more informative?
As it stands, it reads like a message from Star Trek that talks about warp core breaches and anti-matter.

Now, let me share my understanding on the issue in detail:

**Some definitions:**
* Target table: The table on which the data INSERTed
* Source table: The table which returns the partition column value in the subquery.

**The problem:** Since we're pushing down all the computation, we need to make sure that the target table's data and source table's data are located on the same machine for all shards. 

**Thoughts on the problem:** In this context, the first prerequisite is that the source and the target tables are colocated. That's already an another check/error message that we enforce. The second prerequisite is that the source table should include the partition column on the same (ordinal) position as the target table's partition column.

**Cases that we need to consider:**
 * Target table does not have the partition column on its target list
   * Example: ```INSERT INTO target_table (non_part_col) SELECT ... ```
 * Source table does not have the partition column on its target list
   * Example: ```INSERT INTO target_table (part_col) SELECT non_part_col ... ```
 * Both the source table and the target table do have the partition column on their target lists, but, the (ordinal) positions do not match:
   * Example: ```INSERT INTO target_table (part_col, non_part_col) SELECT non_part_col, part_col ... ```
 *  Both the source table and the target table do have the partition column on their target lists, and, the (ordinal) positions match. However, the partition column is a part of an explicit expression on the source target list:
   * Example: ```INSERT INTO target_table (part_col) SELECT (2 * part_col) ... ```
 *  Both the source table and the target table do have the partition column on their target lists, and, the (ordinal) positions match. However, the partition column is a part of an explicit type casting on the source target list:
   * Example: ```INSERT INTO target_table (part_col) SELECT part_col::int8 ... ```
 * Both the source table and the target table do have the partition column on their target lists, and, the (ordinal) positions match. However, the partition column is a part of an implicit expression on the source target list as already in the issue description (i.e., implicit type casting)
   * Example: ```INSERT INTO target_table (part_col) SELECT part_col... ```

**Current Implementation:** Does not enumerate all the above cases, and errors out with the confusing error message as mentioned in the issue description in case the query is not in the expected shape.

**Next step**: 
Do we want to keep the behavior the same as the current implementation such that we still have a single, but easy to understand error message?

Or, do we want to capture all (or some) of the cases mentioned above and add a separate error message for each? I think, this is not a trivial task and, requires 1-2 days of work.
