### ISSUE TITLE
Poll our users and ask them if they are using the shardalias field. If none are, consider killing shardalias

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#95]
Poll our users and ask them if they are using the shardalias field. If none are, consider killing shardalias for v4.0.

**Comment by ozgune** [comment]
@marcocitus -- quick clarification question.

Were you proposing to make shard placement names explicit in shard metadata or keep ``shardalias``?

On the ``shardalias`` column, we introduced it based on feedback from early users. We thought this column would be useful and give our users flexibility in working with shard placements. Instead, due to lack of well-defined use-case, missing documentation, and completeness of implementation, it lead to confusion and errors.

**Comment by marcocitus** [comment]
I was proposing introducing a shardname column as a replacement of shardid and shardalias, but it would have the same semantics as shardalias.

**Comment by robin900** [comment]
@ozgune Yes this issue was resolved by #739.
