### ISSUE TITLE
SQL functions(called by SELECT * FROM) with parameters throw wrong results

### ISSUE THREAD

**Issue by saicitus** [citusdata/citus#981]
```
CREATE TABLE lineitem(id integer, org_id integer);
select master_create_distributed_table('lineitem','org_id','hash');
select master_create_worker_shards('lineitem',16,1);

CREATE OR REPLACE FUNCTION count_rows(org_id_val integer)
RETURNS TABLE (a bigint)
AS $$
  SELECT count(*) AS count_val from lineitem where org_id=org_id_val;
$$ LANGUAGE SQL STABLE;
```
The below test throws wrong results. The query doesn't run on the distributed table.
```
select * from count_rows(1);
 a

---
 0
```

**Comment by byucesoy** [comment]
@sumedhpathak @metdos 

I thought this was a bugfix at first but after looking into it in more detail, I realized this is much more complex than simple bugfix. Fixing this issue means adding new behavior to Citus planner and supporting new type of query. I also talked with @onderkalaci and he also believes this is more than simple bugfix but new functionality.

My initial observation shows that PostgreSQL generated plan is very different plan for this query is than the plan generated for `SELECT count_rows(1); `

For `SELECT count_rows(1);`;
* PostgreSQL first generates a plan for `SELECT count_rows(1);`, we intercept it with our hook.
* `NeedsDistributedPlanning` returns false and we drop to standart planner.
* PostgreSQL extends the `count_rows(1)` to `SELECT count(*) AS count_val from lineitem where org_id=org_id_val;` and generates the plan for that query, we again intercept with our hook.
* `NeedsDistributedPlanning` returns true this time and we error out for some other reason.

However for `SELECT * FROM count_rows(1)`, PostgreSQL calculates the result without extending `count_rows(1)` and creating new plan. I think it does some optimizations and modifications to not generate and execute a plan, which makes it very difficult for us to realize there is a distributed table in the query and act accordingly. Because we only see query tree of `SELECT * FROM count_rows(1)`.

I am not sure about how to fix this yet, but it definitely needs some time to think on. How should we proceed on this issue? Should I spend more time to fix? I do not have time estimation for that but considering I am inexperienced with planner part of the Citus, fixing would take time.

I think, this issue just become more fun to work with :)

**Comment by sumedhpathak** [comment]
@byucesoy to clarify:

This works:
```SQL
select count_rows(1)
```

But the below doesn't?
```SQL 
select * from count_rows(1) 
``` 

Or does neither query work?

If the first option works, that may be sufficient as a workaround for now?

**Comment by byucesoy** [comment]
@sumedhpathak 

Well, `select count_rows(1)` does not return wrong result like `select * from count_rows(1) ` and goes to distributed planning, but it errors out for some other legitimate reason.

It says;

```
ERROR:  could not create distributed plan
DETAIL:  Possibly this is caused by the use of parameters in SQL functions, which is not supported in Citus.
HINT:  Consider using PLPGSQL functions instead.
CONTEXT:  SQL function "count_rows" statement 1
```

**Comment by sumedhpathak** [comment]
I see. So what is the current plan? Are you looking to investigate whether `select * from count_rows(1)` can be made to behave like `select count_rows(1)`? 

Since supporting parametrized queries for SQL functions is non-trivial, and not in our plan to fix I presume we wouldn't want to tackle that.

If we convert that to a PL/PGSQL function, do we encounter the same behavior / errors?

**Comment by anarazel** [comment]
On 2017-04-05 10:06:02 -0700, Sumedh Pathak wrote:
> I see. So what is the current plan? Are you looking to investigate whether `select * from count_rows(1)` can be made to behave like `select count_rows(1)`? 
> 
> Since supporting parametrized queries for SQL functions is non-trivial, and not in our plan to fix I presume we wouldn't want to tackle that.

I think a good idea would be to error out in that case. It's actually
fairly easy to detect:  In multi_planner we can crosscheck
NeedsDistributedPlanning() with
restrictionContext->hasDistributedRelation.

The former will have the non-inlined "distributedness", the latter the
version post inlining.

> If we convert that to a PL/PGSQL function, do we encounter the same behavior / errors?

That should work fine.

**Comment by byucesoy** [comment]
@sumedhpathak 
> Since supporting parametrized queries for SQL functions is non-trivial, and not in our plan to fix I presume we wouldn't want to tackle that.

Yes, our goal is make `select * from count_rows(1)` behave like `select count_rows(1)`. We do not want to support parametrized queries for SQL functions.

> If we convert that to a PL/PGSQL function, do we encounter the same behavior / errors?

If we write same function as PL/PGSQL function, we return correct result in both case. :+1: 

@anarazel 
I could not find any usages of hasDistributedRelation. It seems that we only set it but never use it. Why do we have hasDistributedRelation?

Overall, we looked the issue with @metdos. After standart_planner modifies the the parse tree, distributed table can be seen in the parse tree. Therefore if we call NeedsDistributedPlanning() second time after standart_planner runs, we can catch the existence of distributed tables which are "hidden" at the beginning. We can error out if such "hidden" tables exists for now and create distributed plan for such queries in the future.

**Comment by metdos** [comment]
@anarazel I think #1309 is a right fix, and we intend to ship it (after minor visual changes) unless you have an objection.

I also didn't get what you refer with `restrictionContext->hasDistributedRelation` - actually we never read `restrictionContext->hasDistributedRelation`, so I'm not sure why we have it?
