### ISSUE TITLE
EXPLAIN EXECUTE broken (parameters)

### ISSUE THREAD

**Issue by anarazel** [citusdata/citus#982]
Due to the fix for #900 EXPLAIN EXECUTE, now basically replans the query. The way that's currently done has two problems:
- If parameters are present, the query will fail to be preparable on workers, because the parameters are not present (as they're not extracted from the EXECUTE statement)
- Even if that issue weren't present, EXPLAIN would now give wrong query results, because we replan everytime, which prepared statements don't necessarily do. That has the potential to give quite confusing results.

ISTM that we need to
a) copy the section of ExplainExecuteQuery (including unfortunately EvaluateParams) to get at the parameters.
b) Split MultiExplainOneQuery into MultiExplainOneQuery and MultiExplainOnePlan. Then, instead of replanning like currently done, we have to call MultiExplainOnePlan / ExplainOnePlan (depending on distributedness), when intercepting the EXECUTE statement. That'll also fix the uglyness of replanning.

@lithp @marcocitus What do you guys think?

Longer term, I think we can better solve the whole EXPLAIN integration by using custom plans. There individual custom scan parts of the query can add information to the EXPLAIN. But that seems a bit off.

**Comment by anarazel** [comment]
Hm, also, doesn't the current approach also break this for non-distributed queries?

**Comment by anarazel** [comment]
FWIW, I have a prototype fix for this. It's a bit invasive, but I do think it's the solution. Will open PR.

**Comment by anarazel** [comment]
FWIW, I have a prototype fix for this. It's a bit invasive, but I do think it's the solution. Will open PR.

**Comment by pykello** [comment]
We recently changed the way we do EXPLAIN ANALYZE in https://github.com/citusdata/citus/pull/3890

We know change the task's worker query with two calls to udfs `worker_save_query_explain_analyze()` and `worker_last_saved_explain_analyze()`.

`worker_last_saved_explain_analyze(query, explain_analyze_options)` executes the query, saves its EXPLAIN ANALYZE in a variable in worker backend variable, and returns the queries results.

`worker_last_saved_explain_analyze()` returns the saved EXPLAIN ANALYZE.

We execute these 2 commands in a single `pqSendQuery` which won't work with prepared statements, since `pqSendQueryParams` doesn't accept multiple queries.

To fix this, steps are:

1. Modify adaptive executor to execute multi-query tasks by multiple invocations to `pqSendQuery` or `pqSendQueryParams` instead of just one.
2. Make sure when we have multiple commands we start a coordinated transaction.
3. On the worker somehow pass the received parameters to the `worker_last_saved_explain_analyze()` udf. It is not obvious how we should do this.

**Comment by metdos** [comment]
Hi @pykello, is this issue fixed with #4068?

**Comment by metdos** [comment]
Fixed by #4068
